-- ============================================================
-- Rollback for V10 medium-confidence A type_slug normalization
-- This only clears values written by the matching forward migration.
-- ============================================================

BEGIN;
UPDATE buildings SET type_slug = NULL WHERE slug = 'airman-memorial-chapel' AND type_slug = 'religious';
UPDATE buildings SET type_slug = NULL WHERE slug = 'hirshhorn-museum-and-sculpture-garden' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'european-court-of-human-rights' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'centre-georges-pompidou' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'pa-technology-cambridge-laboratory-pats-center' AND type_slug = 'research-institute';
UPDATE buildings SET type_slug = NULL WHERE slug = 'paleis-of-justice-in-antwerp' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'serpentine-gallery-pavilion-2005' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'logrono-town-hall' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'footbridge-of-the-science-museum' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'atocha-cercanias' AND type_slug = 'transportation';
UPDATE buildings SET type_slug = NULL WHERE slug = 'carlos-ramos-pavilion' AND type_slug = 'temporary';
UPDATE buildings SET type_slug = NULL WHERE slug = 'bank-of-spain-headquarters' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'r-dovre-town-hall' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'rudersdal-town-hall' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'nagano-city-arts-center' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'sydney-opera-house' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'aarhus-city-hall' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'kuwait-national-assembly-building' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'kirishima-international-concert-hall' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'de-la-warr-pavilion' AND type_slug = 'temporary';
UPDATE buildings SET type_slug = NULL WHERE slug = 'campbell-sports-center' AND type_slug = 'sports';
UPDATE buildings SET type_slug = NULL WHERE slug = 'madrid-puerta-de-atocha-almudena-grandes' AND type_slug = 'transportation';
UPDATE buildings SET type_slug = NULL WHERE slug = 'shangyin-opera-house' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'tschumi-pavilion' AND type_slug = 'temporary';
UPDATE buildings SET type_slug = NULL WHERE slug = 'french-embassy-building' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'dar-al-islam' AND type_slug = 'religious';
UPDATE buildings SET type_slug = NULL WHERE slug = 'sao-paulo-museum-of-art' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'sri-lankan-parliament-building' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'chiesa-di-nostra-signora-del' AND type_slug = 'religious';
UPDATE buildings SET type_slug = NULL WHERE slug = 'finnish-pavilion' AND type_slug = 'temporary';
UPDATE buildings SET type_slug = NULL WHERE slug = 'sports-hall-u2' AND type_slug = 'sports';
UPDATE buildings SET type_slug = NULL WHERE slug = 'grosse-pointe-public-library-central' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'helsinki-university-of-technology-main' AND type_slug = 'educational';
UPDATE buildings SET type_slug = NULL WHERE slug = 'rovaniemi-town-hall' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'robert-c-weaver-federal-building' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'chapelle-cumenique-de-flaine' AND type_slug = 'religious';
UPDATE buildings SET type_slug = NULL WHERE slug = 'murray-d-lincoln-campus-center' AND type_slug = 'educational';
UPDATE buildings SET type_slug = NULL WHERE slug = 'cleveland-museum-of-art-building' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'los-angeles-county-hall-of' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'government-service-center' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'new-york-public-library-for' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'niagara-falls-public-library' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'orange-county-government-center' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'jewett-arts-center' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'presidential-palace-damascus' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'hirosaki-city-hall' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'hiroshima-national-peace-memorial-hall' AND type_slug = 'monument';
UPDATE buildings SET type_slug = NULL WHERE slug = 'united-nations-university' AND type_slug = 'educational';
UPDATE buildings SET type_slug = NULL WHERE slug = 'kagawa-prefectural-government-office' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'former-tokyo-metropolitan-government-building' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'kuwait-embassy-building' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'kinokuniya-hall' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'kagawa-prefectural-government-office-main' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'hashima-city-hall-1959-2022' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'hirosaki-civic-hall' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'ishigaki-civic-hall' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'okayama-prefectural-government-building' AND type_slug = 'government';
UPDATE buildings SET type_slug = NULL WHERE slug = 'ibaraki-prefectural-culture-center' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'kanazawa-bunka-hall' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'okayama-symphony-hall' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'loceanografic' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'nuestra-senora-del-libano-montevideo' AND type_slug = 'religious';
UPDATE buildings SET type_slug = NULL WHERE slug = 'palacio-de-los-deportes' AND type_slug = 'sports';
UPDATE buildings SET type_slug = NULL WHERE slug = 'parroquia-maronita-de-nuestra-senora' AND type_slug = 'religious';
UPDATE buildings SET type_slug = NULL WHERE slug = 'esbjerg-performing-arts-centre' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'foundation-e-g-buhrle-collection' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'andre-malraux-cultural-centre' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'serpentine-gallery-pavilion-2017' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'bridge-of-peace' AND type_slug = 'transportation';
UPDATE buildings SET type_slug = NULL WHERE slug = 'groninger-museum-building' AND type_slug = 'cultural';
UPDATE buildings SET type_slug = NULL WHERE slug = 'chiesa-del-santo-volto' AND type_slug = 'religious';
COMMIT;
