-- ============================================================
-- V5: Normalize A-class orphan style_slugs
-- Generated from scripts/style-slug-aliases.json
-- This data migration is idempotent for the listed building slugs.
-- ============================================================

UPDATE buildings SET style_slugs = ARRAY['high-tech', 'eco-architecture']::text[] WHERE slug = 'apple-park';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'asakusa-culture-center';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'aspen-art-museum';
UPDATE buildings SET style_slugs = ARRAY['chicago-school']::text[] WHERE slug = 'auditorium-building';
UPDATE buildings SET style_slugs = ARRAY['modernism', '几何抽象']::text[] WHERE slug = 'bank-of-china-tower';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'international-style', 'minimalism']::text[] WHERE slug = 'barcelona-pavilion';
UPDATE buildings SET style_slugs = ARRAY['classical']::text[] WHERE slug = 'basilica-fano';
UPDATE buildings SET style_slugs = ARRAY['palladian']::text[] WHERE slug = 'basilica-palladiana';
UPDATE buildings SET style_slugs = ARRAY['bauhaus', 'modernism']::text[] WHERE slug = 'bauhaus-dessau';
UPDATE buildings SET style_slugs = ARRAY['contemporary-architecture', '结构表现主义']::text[] WHERE slug = 'beijing-national-stadium';
UPDATE buildings SET style_slugs = ARRAY['brazilian-modernism']::text[] WHERE slug = 'brasilia-cathedral';
UPDATE buildings SET style_slugs = ARRAY['contemporary-swiss', 'minimalism']::text[] WHERE slug = 'bruder-klaus-chapel';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese', '应急建筑']::text[] WHERE slug = 'cardboard-cathedral';
UPDATE buildings SET style_slugs = ARRAY['chicago-school', 'art-nouveau']::text[] WHERE slug = 'carson-pirie-scott';
UPDATE buildings SET style_slugs = ARRAY['catalan-modernisme', 'art-nouveau']::text[] WHERE slug = 'casa-batllo';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism']::text[] WHERE slug = 'casa-da-musica';
UPDATE buildings SET style_slugs = ARRAY['catalan-modernisme']::text[] WHERE slug = 'casa-mila';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'brutalism']::text[] WHERE slug = 'chandigarh';
UPDATE buildings SET style_slugs = ARRAY['minimalism', 'contemporary-japanese']::text[] WHERE slug = 'church-of-light';
UPDATE buildings SET style_slugs = ARRAY['brazilian-modernism']::text[] WHERE slug = 'copan-building';
UPDATE buildings SET style_slugs = ARRAY['contemporary-danish', 'eco-architecture']::text[] WHERE slug = 'copenhill';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism', '雕塑建筑']::text[] WHERE slug = 'dancing-house';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism', 'parametric']::text[] WHERE slug = 'dongdaemun-design-plaza';
UPDATE buildings SET style_slugs = ARRAY['english-baroque']::text[] WHERE slug = 'greenwich-hospital';
UPDATE buildings SET style_slugs = ARRAY['modernism', '结构表现主义']::text[] WHERE slug = 'gateway-arch';
UPDATE buildings SET style_slugs = ARRAY['modernism']::text[] WHERE slug = 'dulles-airport';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'bauhaus']::text[] WHERE slug = 'fagus-factory';
UPDATE buildings SET style_slugs = ARRAY['organic']::text[] WHERE slug = 'fallingwater';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'minimalism']::text[] WHERE slug = 'farnsworth-house';
UPDATE buildings SET style_slugs = ARRAY['renaissance']::text[] WHERE slug = 'florence-cathedral-dome';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese', 'minimalism']::text[] WHERE slug = 'gckeyaki-terrace';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism', 'parametric']::text[] WHERE slug = 'guangzhou-opera-house';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism', '雕塑建筑']::text[] WHERE slug = 'guggenheim-bilbao';
UPDATE buildings SET style_slugs = ARRAY['modernism', '雕塑建筑']::text[] WHERE slug = 'guggenheim-nyc';
UPDATE buildings SET style_slugs = ARRAY['organic']::text[] WHERE slug = 'guggenheim';
UPDATE buildings SET style_slugs = ARRAY['contemporary-architecture']::text[] WHERE slug = 'hamburg-elbphilharmonie';
UPDATE buildings SET style_slugs = ARRAY['english-baroque', 'classical']::text[] WHERE slug = 'hampton-court';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism', 'parametric']::text[] WHERE slug = 'heydar-aliyev-center';
UPDATE buildings SET style_slugs = ARRAY['postmodern', 'japanese-modern']::text[] WHERE slug = 'hiroshima-city-museum';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'house-na';
UPDATE buildings SET style_slugs = ARRAY['japanese-modern']::text[] WHERE slug = 'kagawa-prefectural-office';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese', 'minimalism']::text[] WHERE slug = 'kanazawa-museum';
UPDATE buildings SET style_slugs = ARRAY['high-tech']::text[] WHERE slug = 'kansai-airport';
UPDATE buildings SET style_slugs = ARRAY['modernism']::text[] WHERE slug = 'kimbell-art-museum';
UPDATE buildings SET style_slugs = ARRAY['contemporary-swiss', 'minimalism']::text[] WHERE slug = 'kolumba-museum';
UPDATE buildings SET style_slugs = ARRAY['high-tech', 'contemporary-architecture']::text[] WHERE slug = 'kuala-lumpur-airport';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism']::text[] WHERE slug = 'kunsthal';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'l-arbre-blanc';
UPDATE buildings SET style_slugs = ARRAY['mannerism', 'renaissance']::text[] WHERE slug = 'laurentian-library';
UPDATE buildings SET style_slugs = ARRAY['contemporary-danish']::text[] WHERE slug = 'lego-house';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism']::text[] WHERE slug = 'louis-vuitton-fondation';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'louvre-lens';
UPDATE buildings SET style_slugs = ARRAY['modernism', '几何抽象']::text[] WHERE slug = 'louvre-pyramid';
UPDATE buildings SET style_slugs = ARRAY['contemporary-danish']::text[] WHERE slug = 'marsk-tower';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'high-tech']::text[] WHERE slug = 'menil-collection';
UPDATE buildings SET style_slugs = ARRAY['modernism', '几何抽象']::text[] WHERE slug = 'miho-museum';
UPDATE buildings SET style_slugs = ARRAY['modernism']::text[] WHERE slug = 'mit-chapel';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'mt-fuji-center';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'musashino-art-museum';
UPDATE buildings SET style_slugs = ARRAY['metabolism', 'japanese-modern']::text[] WHERE slug = 'nakagin-capsule-tower';
UPDATE buildings SET style_slugs = ARRAY['minimalism', '清水混凝土']::text[] WHERE slug = 'naoshima';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'national-art-center-tokyo';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'brutalism']::text[] WHERE slug = 'national-assembly-dhaka';
UPDATE buildings SET style_slugs = ARRAY['brazilian-modernism']::text[] WHERE slug = 'national-congress-brazil';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'minimalism']::text[] WHERE slug = 'national-gallery-berlin';
UPDATE buildings SET style_slugs = ARRAY['自然材料', 'japanese-modern']::text[] WHERE slug = 'national-stadium-tokyo';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'new-museum-nyc';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese', 'minimalism']::text[] WHERE slug = 'new-national-stadium';
UPDATE buildings SET style_slugs = ARRAY['baroque']::text[] WHERE slug = 'oratorio-dei-filippini';
UPDATE buildings SET style_slugs = ARRAY['brazilian-modernism']::text[] WHERE slug = 'oscar-niemeyer-museum';
UPDATE buildings SET style_slugs = ARRAY['renaissance']::text[] WHERE slug = 'ospedale-innocenti';
UPDATE buildings SET style_slugs = ARRAY['catalan-modernisme']::text[] WHERE slug = 'palau-guell';
UPDATE buildings SET style_slugs = ARRAY['renaissance']::text[] WHERE slug = 'palazzo-rucellai';
UPDATE buildings SET style_slugs = ARRAY['catalan-modernisme']::text[] WHERE slug = 'park-guell';
UPDATE buildings SET style_slugs = ARRAY['renaissance']::text[] WHERE slug = 'pazzi-chapel';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'pompidou-metz';
UPDATE buildings SET style_slugs = ARRAY['high-tech', '历史建筑改造']::text[] WHERE slug = 'reichstag-dome';
UPDATE buildings SET style_slugs = ARRAY['minimalism', 'contemporary-japanese']::text[] WHERE slug = 'row-house-sumiyoshi';
UPDATE buildings SET style_slugs = ARRAY['catalan-modernisme', 'art-nouveau']::text[] WHERE slug = 'sagrada-familia';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'brutalism']::text[] WHERE slug = 'salk-institute';
UPDATE buildings SET style_slugs = ARRAY['palladian']::text[] WHERE slug = 'san-giorgio-maggiore';
UPDATE buildings SET style_slugs = ARRAY['baroque']::text[] WHERE slug = 'sant-andrea-al-quirinale';
UPDATE buildings SET style_slugs = ARRAY['renaissance']::text[] WHERE slug = 'sant-andrea-mantua';
UPDATE buildings SET style_slugs = ARRAY['baroque']::text[] WHERE slug = 'sant-ivo-alla-sapienza';
UPDATE buildings SET style_slugs = ARRAY['renaissance']::text[] WHERE slug = 'santa-maria-novella';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism', 'high-tech']::text[] WHERE slug = 'seattle-central-library';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'sendai-mediatheque';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'serpentine-pavilion-2013';
UPDATE buildings SET style_slugs = ARRAY['high-tech', 'contemporary-architecture']::text[] WHERE slug = 'shard';
UPDATE buildings SET style_slugs = ARRAY['classical']::text[] WHERE slug = 'sheldonian-theatre';
UPDATE buildings SET style_slugs = ARRAY['english-baroque', 'classical']::text[] WHERE slug = 'st-pauls-cathedral';
UPDATE buildings SET style_slugs = ARRAY['renaissance', 'baroque']::text[] WHERE slug = 'st-peters-dome';
UPDATE buildings SET style_slugs = ARRAY['baroque', '城市设计']::text[] WHERE slug = 'st-peters-square';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese']::text[] WHERE slug = 'taichung-metropolitan-opera';
UPDATE buildings SET style_slugs = ARRAY['organic']::text[] WHERE slug = 'taliesin-west';
UPDATE buildings SET style_slugs = ARRAY['contemporary-architecture', '工业改造']::text[] WHERE slug = 'tate-modern';
UPDATE buildings SET style_slugs = ARRAY['palladian']::text[] WHERE slug = 'teatro-olimpico';
UPDATE buildings SET style_slugs = ARRAY['contemporary-swiss', 'minimalism']::text[] WHERE slug = 'therme-vals';
UPDATE buildings SET style_slugs = ARRAY['japanese-modern', 'metabolism']::text[] WHERE slug = 'tokyo-metropolitan-government';
UPDATE buildings SET style_slugs = ARRAY['futurism', 'modernism']::text[] WHERE slug = 'twa-terminal';
UPDATE buildings SET style_slugs = ARRAY['自然材料', 'japanese-modern']::text[] WHERE slug = 'v-and-a-dundee';
UPDATE buildings SET style_slugs = ARRAY['palladian', 'renaissance']::text[] WHERE slug = 'villa-rotonda';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'international-style']::text[] WHERE slug = 'villa-savoye';
UPDATE buildings SET style_slugs = ARRAY['contemporary-architecture']::text[] WHERE slug = 'vitra-haus';
UPDATE buildings SET style_slugs = ARRAY['functionalism', 'nordic-modernism']::text[] WHERE slug = 'vyborg-library';
UPDATE buildings SET style_slugs = ARRAY['chicago-school', 'early-skyscraper']::text[] WHERE slug = 'wainwright-building';
UPDATE buildings SET style_slugs = ARRAY['minimalism', '清水混凝土']::text[] WHERE slug = 'water-temple';
UPDATE buildings SET style_slugs = ARRAY['high-tech', 'contemporary-architecture']::text[] WHERE slug = 'whitney-museum';
UPDATE buildings SET style_slugs = ARRAY['modernism']::text[] WHERE slug = 'yale-art-gallery';
UPDATE buildings SET style_slugs = ARRAY['nordic-modernism']::text[] WHERE slug = 'finlandia-hall';
UPDATE buildings SET style_slugs = ARRAY['functionalism', 'nordic-modernism']::text[] WHERE slug = 'paimio-sanatorium';
UPDATE buildings SET style_slugs = ARRAY['nordic-modernism', 'organic']::text[] WHERE slug = 'saynatsalo-town-hall';
UPDATE buildings SET style_slugs = ARRAY['contemporary-danish']::text[] WHERE slug = '8-house';
UPDATE buildings SET style_slugs = ARRAY['classical']::text[] WHERE slug = 'todaiji-temple';
UPDATE buildings SET style_slugs = ARRAY['parametric', 'deconstructivism']::text[] WHERE slug = 'beijing-daxing-airport';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism', 'contemporary-architecture']::text[] WHERE slug = 'cctv-headquarters';
UPDATE buildings SET style_slugs = ARRAY['high-tech', 'modernism']::text[] WHERE slug = 'centre-pompidou';
UPDATE buildings SET style_slugs = ARRAY['modernism', '表现主义']::text[] WHERE slug = 'chapel-of-notre-dame-du-haut';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'minimalism']::text[] WHERE slug = 'east-building-national-gallery';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'international-style']::text[] WHERE slug = 'gropius-house';
UPDATE buildings SET style_slugs = ARRAY['modernism']::text[] WHERE slug = 'hiroshima-peace-museum';
UPDATE buildings SET style_slugs = ARRAY['high-tech', '结构表现主义']::text[] WHERE slug = 'hongkong-bank';
UPDATE buildings SET style_slugs = ARRAY['contemporary-swiss', 'minimalism']::text[] WHERE slug = 'kunsthaus-bregenz';
UPDATE buildings SET style_slugs = ARRAY['high-tech', '结构表现主义']::text[] WHERE slug = 'millau-viaduct';
UPDATE buildings SET style_slugs = ARRAY['baroque']::text[] WHERE slug = 'san-carlo-alle-quattro-fontane';
UPDATE buildings SET style_slugs = ARRAY['minimalism', 'contemporary-japanese']::text[] WHERE slug = 'naoshima-chichu-art-museum';
UPDATE buildings SET style_slugs = ARRAY['baroque']::text[] WHERE slug = 'palazzo-barberini';
UPDATE buildings SET style_slugs = ARRAY['mannerism', '城市设计']::text[] WHERE slug = 'piazza-del-campidoglio';
UPDATE buildings SET style_slugs = ARRAY['contemporary-japanese', 'minimalism']::text[] WHERE slug = 'rolex-learning-center';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'international-style']::text[] WHERE slug = 'seagram-building';
UPDATE buildings SET style_slugs = ARRAY['high-tech', 'eco-architecture']::text[] WHERE slug = 'the-gherkin';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'brutalism']::text[] WHERE slug = 'unite-habitation';
UPDATE buildings SET style_slugs = ARRAY['contemporary-danish']::text[] WHERE slug = 'via-57-west';
UPDATE buildings SET style_slugs = ARRAY['modernism', 'metabolism']::text[] WHERE slug = 'yoyogi-national-gymnasium';
UPDATE buildings SET style_slugs = ARRAY['deconstructivism', '雕塑建筑']::text[] WHERE slug = 'walt-disney-concert-hall';
