-- Graduation Shiroiya Hotel batch 006: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=shiroiya-hotel-006).
-- Scope: 0 new architects, 1 buildings, 1 images,
-- 1 profiles, 2 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation Shiroiya Hotel batch 006 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('009373b5-61c8-4621-b128-9934f77d681c'::uuid, 'fujimoto', '藤本壮介', 'Sou Fujimoto', '藤本壮介', NULL, false);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('6ee56b07-11ef-5d25-a7a8-cfce9e76bf2f'::uuid, 'CASE-028', 'shiroiya-hotel', '白井屋酒店', 'Shiroiya Hotel', '白井屋ホテル', '009373b5-61c8-4621-b128-9934f77d681c'::uuid, 'fujimoto', 2020, 'published', '前桥', '日本', 'JP', 'commercial', 'https://www.shiroiya.com/en/stories/soufujimoto/');

CREATE TEMP TABLE reused_building_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE) ON COMMIT DROP;


CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('3127db3e-0bc3-59a6-ad3b-ddb527166ae2'::uuid, '6ee56b07-11ef-5d25-a7a8-cfce9e76bf2f'::uuid, 'shiroiya-hotel', 'CASE-028', '/images/graduation/cases/case-028-shiroiya-hotel.jpg', 'こやまひろ', 'Wikimedia Commons', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Shiroiya_Hotel.jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL, building_slug text NOT NULL, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-028', '6ee56b07-11ef-5d25-a7a8-cfce9e76bf2f'::uuid, 'shiroiya-hotel', '旧旅馆再生为住宿、艺术和半公共活动场，成为地方中心街区更新的触媒。', NULL, 'Shiroiya Hotel is a reference case for reading localregeneration, Design topic: 住宿, art, Design topic: center市街地. It can inform thesis thinking about mixed programs, operation, and place-making.', '既存建物、宿泊、アート、街の回遊を組み合わせた中心市街地再生の事例。空き建物を滞在体験へ変える方法を比較できる。', ARRAY['地方再生', '住宿', '艺术', '中心市街地', '再利用']::text[], '{}'::text[], ARRAY['localregeneration', 'Design topic: 住宿', 'art', 'Design topic: center市街地', 'reuse']::text[], ARRAY['地域再生', '宿泊', 'アート', '中心市街地', '再利用']::text[], NULL, NULL, 'https://www.shiroiya.com/en/stories/soufujimoto/', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('6ee56b07-11ef-5d25-a7a8-cfce9e76bf2f'::uuid, 'shiroiya-hotel', 'hotel', true, 1.000, 'https://www.shiroiya.com/en/stories/soufujimoto/', 'The official hotel page describes Sou Fujimoto''s renovation of the main building and the new hill-like building as one Shiroiya project completed in 2020. The operating complex includes guest rooms, restaurants, bakery, cafe, bar, art and sauna facilities, with hotel as the principal program.', '2026-07-12T00:00:00Z'::timestamptz),
  ('6ee56b07-11ef-5d25-a7a8-cfce9e76bf2f'::uuid, 'shiroiya-hotel', 'retail', false, 1.000, 'https://www.shiroiya.com/en/stories/soufujimoto/', 'The official hotel page describes Sou Fujimoto''s renovation of the main building and the new hill-like building as one Shiroiya project completed in 2020. The operating complex includes guest rooms, restaurants, bakery, cafe, bar, art and sauna facilities, with hotel as the principal program.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  reused_building_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  invalid_profile_buildings integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 1
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 0
    OR (SELECT count(*) FROM building_seed) <> 1
    OR (SELECT count(*) FROM reused_building_seed) <> 0
    OR (SELECT count(*) FROM image_seed) <> 1
    OR (SELECT count(*) FROM profile_seed) <> 1
    OR (SELECT count(*) FROM assignment_seed) <> 2 THEN
    RAISE EXCEPTION 'Graduation Shiroiya Hotel batch 006 seed count mismatch';
  END IF;

  SELECT count(*) INTO reused_building_matches
  FROM reused_building_seed seed JOIN public.buildings target USING (id, slug);
  IF reused_building_matches <> 0 THEN
    RAISE EXCEPTION 'Reused building UUID/slug pairs drifted: matched %', reused_building_matches;
  END IF;

  SELECT count(*) INTO invalid_profile_buildings
  FROM profile_seed profile
  LEFT JOIN building_seed created ON created.id = profile.building_id AND created.slug = profile.building_slug
  LEFT JOIN reused_building_seed reused ON reused.id = profile.building_id AND reused.slug = profile.building_slug
  WHERE created.id IS NULL AND reused.id IS NULL;
  IF invalid_profile_buildings <> 0 THEN
    RAISE EXCEPTION 'Profile seed references % unreviewed canonical buildings', invalid_profile_buildings;
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 1 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['hotel', 'retail']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['commercial']::text[]);
  IF required_function_matches <> 2
    OR required_type_matches <> 1 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation Shiroiya Hotel batch 006 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 0
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 1
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 1
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 1
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 2
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 1
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 1 THEN
    RAISE EXCEPTION 'Graduation Shiroiya Hotel batch 006 post-write verification failed';
  END IF;
END $$;

COMMIT;
