-- Graduation transport batch 001: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=transport-001).
-- Scope: 1 new architects, 3 buildings, 3 images,
-- 3 profiles, 5 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation transport batch 001 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('aa16eb77-f51a-418b-a464-d46ce25cc0d8'::uuid, 'shigeru-ban', '坂茂', 'Shigeru Ban', '坂茂', NULL, false),
  ('51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', '隈研吾', 'Kengo Kuma', '隈研吾', NULL, false),
  ('5d3c8548-eab2-5718-8f99-12743b0b9721'::uuid, 'foreign-office-architects', 'Foreign Office Architects', 'Foreign Office Architects', 'Foreign Office Architects', 'https://www.moma.org/artists/27436', true);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('9083a770-b66b-54b7-a553-89da21628820'::uuid, 'CASE-008', 'onagawa-station-yupoppo', '女川站与女川温泉 Yupoppo', 'Onagawa Station and Onagawa Onsen Yupoppo', '女川駅舎・女川温泉温浴施設ゆぽっぽ', 'aa16eb77-f51a-418b-a464-d46ce25cc0d8'::uuid, 'shigeru-ban', 2015, 'published', '女川', '日本', 'JP', 'transportation', 'https://shigerubanarchitects.com/works/cultural/onagawa-station/'),
  ('08ce470e-40f7-592d-806d-37b852eaafe1'::uuid, 'CASE-094', 'takanawa-gateway-station', '高轮 Gateway 站', 'Takanawa Gateway Station', '高輪ゲートウェイ駅', '51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', 2020, 'published', '东京', '日本', 'JP', 'transportation', 'https://kkaa.co.jp/en/project/takanawa-gateway-station/'),
  ('eda9faa2-e337-579d-a511-766ccee61d1c'::uuid, 'CASE-133', 'yokohama-international-passenger-terminal', '横滨国际客运码头', 'Yokohama International Passenger Terminal', '横浜港大さん橋国際客船ターミナル', '5d3c8548-eab2-5718-8f99-12743b0b9721'::uuid, 'foreign-office-architects', 2002, 'published', '横滨', '日本', 'JP', 'transportation', 'https://osanbashi.jp/en/about/');

CREATE TEMP TABLE reused_building_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE) ON COMMIT DROP;


CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('136fa1ba-e4e3-52cc-a922-3b78f341aa5c'::uuid, '9083a770-b66b-54b7-a553-89da21628820'::uuid, 'onagawa-station-yupoppo', 'CASE-008', '/images/graduation/cases/case-008-onagawa-station-yupopo.jpg', 'Mister0124', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:JR_East_Onagawa_Station_building%2C_Miyagi_Pref_20240420.jpg', 'exterior', true),
  ('99e66f2c-d094-583f-a8ed-d93cd04a53e1'::uuid, '08ce470e-40f7-592d-806d-37b852eaafe1'::uuid, 'takanawa-gateway-station', 'CASE-094', '/images/graduation/cases/case-094-takanawa-gateway-station.jpg', '江戸村のとくぞう', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Takanawa_Gateway_Station_200316a1.jpg', 'exterior', true),
  ('4c917d6d-f3be-562d-8a15-3e7a53440666'::uuid, 'eda9faa2-e337-579d-a511-766ccee61d1c'::uuid, 'yokohama-international-passenger-terminal', 'CASE-133', '/images/graduation/cases/case-133-yokohama-international-passenger-terminal.jpg', 'Syced', 'Wikimedia Commons', 'CC0', 'https://commons.wikimedia.org/wiki/File:Yokohama_International_Passenger_Terminal_11.jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL, building_slug text NOT NULL, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-008', '9083a770-b66b-54b7-a553-89da21628820'::uuid, 'onagawa-station-yupoppo', '车站与温浴设施复合，成为灾后城镇重建中的公共客厅。', NULL, 'Onagawa Station and Yupo''po is a reference case for reading station, Design topic: 温浴, Design topic: 复兴, transport. It can inform thesis thinking about mixed programs, operation, and place-making.', '駅、温浴、地域交流を復興後の生活動線に組み込んだ事例。移動の場所を待つだけの空間ではなく、滞在と再会の場へ変えている。', ARRAY['车站', '温浴', '复兴', '交通', '夜间安全', '步行']::text[], '{}'::text[], ARRAY['station', 'Design topic: 温浴', 'Design topic: 复兴', 'transport', 'nightsafety', 'Design topic: 步行']::text[], ARRAY['駅', '温浴', '復興', '交通', '夜間安全', '歩行']::text[], NULL, NULL, 'https://shigerubanarchitects.com/works/cultural/onagawa-station/', 'published'),
  ('CASE-094', '08ce470e-40f7-592d-806d-37b852eaafe1'::uuid, 'takanawa-gateway-station', '新车站以大屋顶和开放站厅回应再开发街区，把交通节点转为城市入口和活动平台。', NULL, 'Takanawa Gateway Station is a reference case for reading station, Design topic: transport枢纽, urbanentry, Design topic: 大roof. It can inform thesis thinking about mixed programs, operation, and place-making.', '駅を都市の移動拠点としてだけでなく、木架構、案内、滞留を含む公共空間として設計した事例。歩行支援の視点で読める。', ARRAY['车站', '交通枢纽', '城市入口', '大屋顶', '再开发']::text[], '{}'::text[], ARRAY['station', 'Design topic: transport枢纽', 'urbanentry', 'Design topic: 大roof', 'Design topic: 再开发']::text[], ARRAY['駅', '交通', '木架構', '歩行', '都市インフラ']::text[], NULL, NULL, 'https://kkaa.co.jp/en/project/takanawa-gateway-station/', 'published'),
  ('CASE-133', 'eda9faa2-e337-579d-a511-766ccee61d1c'::uuid, 'yokohama-international-passenger-terminal', '屋根、床、広場、動線が連続する港のターミナル。交通施設を都市の公共地形にする参考になる。', NULL, 'Reference case for Yokohama International Passenger Terminal: useful for comparing public program, urban interface, operation, and spatial experience.', '屋根、床、広場、動線が連続する港のターミナル。交通施設を都市の公共地形にする参考になる。', ARRAY['港', 'ターミナル', '公共地形', '歩行', '都市入口']::text[], '{}'::text[], ARRAY['港', 'ターミナル', '公共地形', '歩行', '都市入口']::text[], ARRAY['港', 'ターミナル', '公共地形', '歩行', '都市入口']::text[], NULL, NULL, 'https://osanbashi.jp/en/about/', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('9083a770-b66b-54b7-a553-89da21628820'::uuid, 'onagawa-station-yupoppo', 'transport-hub', true, 1.000, 'https://shigerubanarchitects.com/works/cultural/onagawa-station/', 'Shigeru Ban Architects records a completed 2015 new-built station in Japan. The official description confirms the three-storey railway and public-bath complex, curved LVL lattice roof and membrane structure visible in the reviewed image.', '2026-07-12T00:00:00Z'::timestamptz),
  ('9083a770-b66b-54b7-a553-89da21628820'::uuid, 'onagawa-station-yupoppo', 'mixed-use', false, 1.000, 'https://shigerubanarchitects.com/works/cultural/onagawa-station/', 'Shigeru Ban Architects records a completed 2015 new-built station in Japan. The official description confirms the three-storey railway and public-bath complex, curved LVL lattice roof and membrane structure visible in the reviewed image.', '2026-07-12T00:00:00Z'::timestamptz),
  ('08ce470e-40f7-592d-806d-37b852eaafe1'::uuid, 'takanawa-gateway-station', 'transport-hub', true, 1.000, 'https://kkaa.co.jp/en/project/takanawa-gateway-station/', 'Kengo Kuma and Associates identifies the completed Tokyo infrastructure project and its large membrane roof supported by origami-shaped steel and cedar frames. The station opened in March 2020; the architect page currently lists March 2021 completion for the full project, so year_start remains the public opening year while the evidence note preserves this distinction.', '2026-07-12T00:00:00Z'::timestamptz),
  ('eda9faa2-e337-579d-a511-766ccee61d1c'::uuid, 'yokohama-international-passenger-terminal', 'transport-hub', true, 1.000, 'https://osanbashi.jp/en/about/', 'The terminal operator and City of Yokohama confirm the current seventh-generation international passenger terminal completed in 2002, with a public rooftop plaza and passenger facilities. JA and MoMA identify Foreign Office Architects, Farshid Moussavi and Alejandro Zaera-Polo as the design authors.', '2026-07-12T00:00:00Z'::timestamptz),
  ('eda9faa2-e337-579d-a511-766ccee61d1c'::uuid, 'yokohama-international-passenger-terminal', 'mixed-use', false, 1.000, 'https://osanbashi.jp/en/about/', 'The terminal operator and City of Yokohama confirm the current seventh-generation international passenger terminal completed in 2002, with a public rooftop plaza and passenger facilities. JA and MoMA identify Foreign Office Architects, Farshid Moussavi and Alejandro Zaera-Polo as the design authors.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  reused_building_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  invalid_profile_buildings integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 3
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 1
    OR (SELECT count(*) FROM building_seed) <> 3
    OR (SELECT count(*) FROM reused_building_seed) <> 0
    OR (SELECT count(*) FROM image_seed) <> 3
    OR (SELECT count(*) FROM profile_seed) <> 3
    OR (SELECT count(*) FROM assignment_seed) <> 5 THEN
    RAISE EXCEPTION 'Graduation transport batch 001 seed count mismatch';
  END IF;

  SELECT count(*) INTO reused_building_matches
  FROM reused_building_seed seed JOIN public.buildings target USING (id, slug);
  IF reused_building_matches <> 0 THEN
    RAISE EXCEPTION 'Reused building UUID/slug pairs drifted: matched %', reused_building_matches;
  END IF;

  SELECT count(*) INTO invalid_profile_buildings
  FROM profile_seed profile
  LEFT JOIN building_seed created ON created.id = profile.building_id AND created.slug = profile.building_slug
  LEFT JOIN reused_building_seed reused ON reused.id = profile.building_id AND reused.slug = profile.building_slug
  WHERE created.id IS NULL AND reused.id IS NULL;
  IF invalid_profile_buildings <> 0 THEN
    RAISE EXCEPTION 'Profile seed references % unreviewed canonical buildings', invalid_profile_buildings;
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 2 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['transport-hub', 'mixed-use']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['transportation']::text[]);
  IF required_function_matches <> 2
    OR required_type_matches <> 1 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation transport batch 001 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 1
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 3
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 3
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 3
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 5
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 3
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 3 THEN
    RAISE EXCEPTION 'Graduation transport batch 001 post-write verification failed';
  END IF;
END $$;

COMMIT;
