-- Graduation library batch 001: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-001.mjs.
-- Scope: 4 new architects, 8 buildings, 8 images,
-- 8 profiles, 17 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation library batch prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('8f156f56-c53f-56d3-a52a-569c592e9d08'::uuid, 'coelacanth-kh', 'Coelacanth K&H建筑事务所', 'Coelacanth K&H Architects', 'シーラカンスK&H', 'http://www.coelacanth-kandh.co.jp/', true),
  ('51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', '隈研吾', 'Kengo Kuma', '隈研吾', NULL, false),
  ('c5b0b342-a782-443b-821c-e5c3f94fbf74'::uuid, 'toyo-ito', '伊东丰雄', 'Toyo Ito', '伊東豊雄', NULL, false),
  ('79dcf08b-8f73-4255-955e-dcd52332d30c'::uuid, 'tadao-ando', '安藤忠雄', 'Tadao Ando', '安藤忠雄', NULL, false),
  ('373cf2be-4c4d-5e22-9cd1-9413e3e77931'::uuid, 'kw-hg-architects', 'kw+hg建筑事务所', 'kw+hg architects', 'kw+hgアーキテクツ', 'https://kwhg.co.jp/', true),
  ('87c54689-8de6-59c8-9c44-03d542987e84'::uuid, 'mari-ito-uao', '伊藤麻理 + UAo', 'Mari Ito + UAo', '伊藤麻理 + UAo', 'https://www.u-a-o.jp/', true),
  ('9795da73-a3ea-5f28-bf04-bdc31d2dfa02'::uuid, 'mikami-architects', '三上建筑事务所', 'MIKAMI Architects', '三上建築事務所', 'https://mikami-arc.co.jp/', true);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('6fef359f-7296-5e99-b1b7-7dc580fdfed2'::uuid, 'CASE-018', 'kanazawa-umimirai-library', '金泽海未来图书馆', 'Kanazawa Umimirai Library', '金沢海みらい図書館', '8f156f56-c53f-56d3-a52a-569c592e9d08'::uuid, 'coelacanth-kh', 2011, 'published', '金泽', '日本', 'JP', 'cultural', 'https://www.lib.kanazawa.ishikawa.jp/umimirai/outline/architectural-information'),
  ('f53171cc-293c-579b-9425-1fc020b62542'::uuid, 'CASE-021', 'toyama-kirari', '富山KIRARI', 'Toyama Kirari', 'TOYAMAキラリ', '51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', 2015, 'published', '富山', '日本', 'JP', 'cultural', 'https://kkaa.co.jp/en/project/toyama-kirari/'),
  ('38b54039-7e4e-5318-a0e9-ef02e199c561'::uuid, 'CASE-022', 'minna-no-mori-gifu-media-cosmos', '大家的森林·岐阜媒体宇宙', 'Minna no Mori Gifu Media Cosmos', 'みんなの森 ぎふメディアコスモス', 'c5b0b342-a782-443b-821c-e5c3f94fbf74'::uuid, 'toyo-ito', 2015, 'published', '岐阜', '日本', 'JP', 'cultural', 'https://g-mediacosmos.jp/cosmos/about/'),
  ('2f80a130-04e2-594a-abbe-10d7ab138cd0'::uuid, 'CASE-023', 'nakanoshima-childrens-book-forest', '中之岛儿童书之森', 'Nakanoshima Children''s Book Forest', 'こども本の森 中之島', '79dcf08b-8f73-4255-955e-dcd52332d30c'::uuid, 'tadao-ando', 2020, 'published', '大阪', '日本', 'JP', 'cultural', 'https://kodomohonnomori.osaka/about/'),
  ('e619eac8-d46f-5df5-b630-1d030850ee75'::uuid, 'CASE-027', 'yusuhara-community-library', '梼原云上图书馆', 'Yusuhara Community Library / Yururi Yusuhara', '雲の上の図書館 / ゆすはら・夢・未来館', '51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', 2018, 'published', '梼原', '日本', 'JP', 'cultural', 'https://kkaa.co.jp/en/project/yusuhara-community-library-yururi-yusuhara/'),
  ('d5ad015d-93e2-5c1e-8cb3-174b5a6e098f'::uuid, 'CASE-029', 'musashino-place', '武藏野Place', 'Musashino Place', '武蔵野プレイス', '373cf2be-4c4d-5e22-9cd1-9413e3e77931'::uuid, 'kw-hg-architects', 2011, 'published', '东京', '日本', 'JP', 'cultural', 'https://www.musashino.or.jp/place/1001617/1001618.html'),
  ('d77dfe51-52a0-552a-b617-c8007b994bea'::uuid, 'CASE-042', 'nasushiobara-city-library-miruru', '那须盐原市图书馆 Miruru', 'Nasushiobara City Library Miruru', '那須塩原市図書館 みるる', '87c54689-8de6-59c8-9c44-03d542987e84'::uuid, 'mari-ito-uao', 2020, 'published', '那须盐原', '日本', 'JP', 'cultural', 'https://www.u-a-o.jp/project/20200401/a-public-library-at-the-heart-of-a-compact-vibrant-city'),
  ('d801abfc-1290-5935-836d-9059ba4fedb5'::uuid, 'CASE-070', 'tonami-public-library', '砺波市立砺波图书馆', 'Tonami Public Library', '砺波市立砺波図書館', '9795da73-a3ea-5f28-bf04-bdc31d2dfa02'::uuid, 'mikami-architects', 2020, 'published', '砺波', '日本', 'JP', 'cultural', 'https://mikami-arc.co.jp/work/%E7%A0%BA%E6%B3%A2%E5%B8%82%E7%AB%8B%E7%A0%BA%E6%B3%A2%E5%9B%B3%E6%9B%B8%E9%A4%A8');

CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('9e040c03-8489-5f91-9ff5-2b66ede13666'::uuid, '6fef359f-7296-5e99-b1b7-7dc580fdfed2'::uuid, 'kanazawa-umimirai-library', 'CASE-018', '/images/graduation/cases/case-018-kanazawa-umimirai-library.jpg', 'Asturio Cantabrio', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Kanazawa_Umimirai_Library_exterior_ac_(4).jpg', 'exterior', true),
  ('61a2c0d6-9476-5340-9aa6-9c43a7e9eb77'::uuid, 'f53171cc-293c-579b-9425-1fc020b62542'::uuid, 'toyama-kirari', 'CASE-021', '/images/graduation/cases/case-021-toyama-kirari.jpg', 'Asturio Cantabrio', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:TOYAMA_KIRARI_exterior_in_the_morning_ac_(3).jpg', 'exterior', true),
  ('00a43bf1-43b9-5208-b8b4-7df7040dcd72'::uuid, '38b54039-7e4e-5318-a0e9-ef02e199c561'::uuid, 'minna-no-mori-gifu-media-cosmos', 'CASE-022', '/images/graduation/cases/case-022-minna-no-mori-gifu-media-cosmos.jpg', 'Asturio Cantabrio', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Gifu_Media_Cosmos_exterior_ac_(1).jpg', 'exterior', true),
  ('8756d9f9-7a88-53ad-95e5-ee23768484a2'::uuid, '2f80a130-04e2-594a-abbe-10d7ab138cd0'::uuid, 'nakanoshima-childrens-book-forest', 'CASE-023', '/images/graduation/cases/case-023-nakanoshima-children-s-book-forest.jpg', 'KishujiRapid', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Nakanoshima_Children%60s_Book_Forest.jpg', 'exterior', true),
  ('3f92811e-131d-529a-b974-f419c6cc1ccf'::uuid, 'e619eac8-d46f-5df5-b630-1d030850ee75'::uuid, 'yusuhara-community-library', 'CASE-027', '/images/graduation/cases/case-027-yusuhara-community-library.jpg', 'Asset utilitist', 'Wikimedia Commons', 'CC0', 'https://commons.wikimedia.org/wiki/File:%E3%82%86%E3%81%99%E3%81%AF%E3%82%89%E9%9B%B2%E3%81%AE%E4%B8%8A%E3%81%AE%E5%9B%B3%E6%9B%B8%E9%A4%A8%EF%BC%88%E6%A2%BC%E5%8E%9F%E7%94%BA%E7%AB%8B%E5%9B%B3%E6%9B%B8%E9%A4%A8%EF%BC%89_02.jpg', 'interior', true),
  ('82e4073c-8163-5a23-8572-dfbf3333b0df'::uuid, 'd5ad015d-93e2-5c1e-8cb3-174b5a6e098f'::uuid, 'musashino-place', 'CASE-029', '/images/graduation/cases/case-029-musashino-place.jpg', 'Asturio Cantabrio', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Musashino_Place_exterior_ac_(1).jpg', 'exterior', true),
  ('136a8b47-ecf3-5e41-b901-a86135c9ac35'::uuid, 'd77dfe51-52a0-552a-b617-c8007b994bea'::uuid, 'nasushiobara-city-library-miruru', 'CASE-042', '/images/graduation/cases/case-042-nasushiobara-city-library-miruru.jpg', 'Miyuki Meinaka', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Nasushiobara_Library_Miruru_1.jpg', 'exterior', true),
  ('2f2e4851-8c76-5fbc-af0c-ee1916f53512'::uuid, 'd801abfc-1290-5935-836d-9059ba4fedb5'::uuid, 'tonami-public-library', 'CASE-070', '/images/graduation/cases/case-070-tonami-public-library.jpg', 'Whatsfb', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:%E7%A0%BA%E6%B3%A2%E5%B8%82%E7%AB%8B%E7%A0%BA%E6%B3%A2%E5%9B%B3%E6%9B%B8%E9%A4%A8.jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-018', '6fef359f-7296-5e99-b1b7-7dc580fdfed2'::uuid, 'kanazawa-umimirai-library', '以均质光孔和大空间提供安静、开放的城市学习环境。', NULL, 'Kanazawa Umimirai Library is a reference case for reading library, Design topic: 光, learning, publicness. It can inform thesis thinking about mixed programs, operation, and place-making.', '自然光に包まれた大きな閲覧空間を持つ公共図書館。静かな学習と地域の開放性を両立する空間密度を比較できる。', ARRAY['图书馆', '光', '学习', '公共性', '第三空间']::text[], '{}'::text[], ARRAY['library', 'Design topic: 光', 'learning', 'publicness', 'third place']::text[], ARRAY['図書館', '光', '学習', '公共性', '第三空間']::text[], NULL, NULL, 'https://www.lib.kanazawa.ishikawa.jp/umimirai/outline/architectural-information', 'published'),
  ('CASE-021', 'f53171cc-293c-579b-9425-1fc020b62542'::uuid, 'toyama-kirari', '图书馆、美术馆、银行与商业界面复合，形成城市中心的文化公共节点。', NULL, 'Toyama Kirari is a reference case for reading library, art museum, Design topic: 复合public建筑, urbancenter. It can inform thesis thinking about mixed programs, operation, and place-making.', '図書館、美術館、交流空間を都市中心部で重ねた複合公共建築。学習と文化利用が上下に連続する構成を比較できる。', ARRAY['图书馆', '美术馆', '复合公共建筑', '城市中心', '学习']::text[], '{}'::text[], ARRAY['library', 'art museum', 'Design topic: 复合public建筑', 'urbancenter', 'learning']::text[], ARRAY['図書館', '美術館', '複合公共建築', '都市中心部', '学習']::text[], NULL, NULL, 'https://kkaa.co.jp/en/project/toyama-kirari/', 'published'),
  ('CASE-022', '38b54039-7e4e-5318-a0e9-ef02e199c561'::uuid, 'minna-no-mori-gifu-media-cosmos', '图书馆、市民活动、多文化交流和展示功能并置，形成面向日常停留的市民平台。', NULL, 'Minna no Mori Gifu Media Cosmos is a reference case for reading library, citizenactivity, multicultural, learning. It can inform thesis thinking about mixed programs, operation, and place-making.', '図書館と市民活動を大きな屋根の下にまとめた公共施設。多文化利用、学習、交流を同時に受け止める開放性を読める。', ARRAY['图书馆', '市民活动', '多文化', '学习', '公共性']::text[], '{}'::text[], ARRAY['library', 'citizenactivity', 'multicultural', 'learning', 'publicness']::text[], ARRAY['図書館', '市民活動', '多文化', '学習', '公共性']::text[], NULL, NULL, 'https://www.toyo-ito.co.jp/WWW/Project_Descript/2015-/2015-p_02/2015-p_02_j.html', 'published'),
  ('CASE-023', '2f80a130-04e2-594a-abbe-10d7ab138cd0'::uuid, 'nakanoshima-childrens-book-forest', '把儿童阅读、河岸步行和城市文化记忆结合，形成可自由探索的书之公共空间。', NULL, 'Nakanoshima Children''s Book Forest is a reference case for reading children, library, waterfront, learning. It can inform thesis thinking about mixed programs, operation, and place-making.', '子どもが本と出会う体験を、水辺の都市環境と結びつけた図書施設。学習を管理ではなく発見として設計する参考になる。', ARRAY['儿童', '图书馆', '水边', '学习', '文化']::text[], '{}'::text[], ARRAY['children', 'library', 'waterfront', 'learning', 'culture']::text[], ARRAY['子ども', '図書館', '水辺', '学習', '文化']::text[], NULL, NULL, 'https://kodomohonnomori.osaka/', 'published'),
  ('CASE-027', 'e619eac8-d46f-5df5-b630-1d030850ee75'::uuid, 'yusuhara-community-library', '图书馆与福祉设施相邻，以地方木材和可停留空间支持山村的多代交流。', NULL, 'Yusuhara Community Library Yururi Yusuhara is a reference case for reading library, Design topic: 福祉, Design topic: local木材, Design topic: 多代exchange. It can inform thesis thinking about mixed programs, operation, and place-making.', '図書館、福祉、地域木材の空間を重ねた地域拠点。高齢者、子ども、観光客が同じ場所に滞在できる多世代の公共性を読める。', ARRAY['图书馆', '福祉', '地方木材', '多代交流', '高龄']::text[], '{}'::text[], ARRAY['library', 'Design topic: 福祉', 'Design topic: local木材', 'Design topic: 多代exchange', 'aging']::text[], ARRAY['図書館', '福祉', '地域木材', '多世代交流', '高齢']::text[], NULL, NULL, 'https://kkaa.co.jp/en/project/yusuhara-community-library-yururi-yusuhara/', 'published'),
  ('CASE-029', 'd5ad015d-93e2-5c1e-8cb3-174b5a6e098f'::uuid, 'musashino-place', '图书馆、市民活动、生涯学习和青少年活动整合，提供非商业的城市停留场所。', NULL, 'Musashino Place is a reference case for reading library, Design topic: 青少年, citizenactivity, third place. It can inform thesis thinking about mixed programs, operation, and place-making.', '図書館、青少年活動、市民交流を駅前で重ねた第三の居場所。学校や家庭以外の学びと滞在を支える構成を比較できる。', ARRAY['图书馆', '青少年', '市民活动', '第三空间', '学习']::text[], '{}'::text[], ARRAY['library', 'Design topic: 青少年', 'citizenactivity', 'third place', 'learning']::text[], ARRAY['図書館', '青少年', '市民活動', '第三の居場所', '学習']::text[], NULL, NULL, 'https://www.musashino.or.jp/place/', 'published'),
  ('CASE-042', 'd77dfe51-52a0-552a-b617-c8007b994bea'::uuid, 'nasushiobara-city-library-miruru', '车站前图书馆与广场像城市森林一样组织学习、市民活动和地方中心更新。', NULL, 'Nasushiobara City Library Miruru is a reference case for reading library, Design topic: station前, Design topic: 紧凑urban, citizenactivity. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Nasushiobara City Library Miruru」は、図書館・駅前・コンパクト都市・市民活動の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['图书馆', '车站前', '紧凑城市', '市民活动', '学习']::text[], '{}'::text[], ARRAY['library', 'Design topic: station前', 'Design topic: 紧凑urban', 'citizenactivity', 'learning']::text[], ARRAY['図書館', '駅前', 'コンパクト都市', '市民活動', '学習']::text[], NULL, NULL, 'https://www.u-a-o.jp/project/20200401/a-public-library-at-the-heart-of-a-compact-vibrant-city', 'published'),
  ('CASE-070', 'd801abfc-1290-5935-836d-9059ba4fedb5'::uuid, 'tonami-public-library', '地方图书馆以大木屋顶组织阅读、停留和市民活动，成为全天候公共客厅。', NULL, 'Tonami Public Library is a reference case for reading library, Design topic: 木roof, citizenactivity, learning. It can inform thesis thinking about mixed programs, operation, and place-making.', '木の屋根を持つ地域図書館。学習、市民活動、滞在が同じ空間に重なり、日常的な公共性を支える事例として読める。', ARRAY['图书馆', '木屋顶', '市民活动', '学习', '地方公共性']::text[], '{}'::text[], ARRAY['library', 'Design topic: 木roof', 'citizenactivity', 'learning', 'localpublicness']::text[], ARRAY['図書館', '木屋根', '市民活動', '学習', '地域拠点']::text[], NULL, NULL, 'https://mikami-arc.co.jp/work/%E7%A0%BA%E6%B3%A2%E5%B8%82%E7%AB%8B%E7%A0%BA%E6%B3%A2%E5%9B%B3%E6%9B%B8%E9%A4%A8', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('6fef359f-7296-5e99-b1b7-7dc580fdfed2'::uuid, 'kanazawa-umimirai-library', 'library', true, 1.000, 'https://www.lib.kanazawa.ishikawa.jp/umimirai/outline/architectural-information', 'The official Kanazawa City Library architecture page names the library use, address and Coelacanth K&H as architectural designer. The official library history records opening on 2011-05-21, and the perforated white facade matches the reviewed image.', '2026-07-12T00:00:00Z'::timestamptz),
  ('6fef359f-7296-5e99-b1b7-7dc580fdfed2'::uuid, 'kanazawa-umimirai-library', 'community-center', false, 1.000, 'https://www.lib.kanazawa.ishikawa.jp/umimirai/outline/architectural-information', 'The official Kanazawa City Library architecture page names the library use, address and Coelacanth K&H as architectural designer. The official library history records opening on 2011-05-21, and the perforated white facade matches the reviewed image.', '2026-07-12T00:00:00Z'::timestamptz),
  ('f53171cc-293c-579b-9425-1fc020b62542'::uuid, 'toyama-kirari', 'library', true, 1.000, 'https://kkaa.co.jp/en/project/toyama-kirari/', 'Kengo Kuma and Associates identifies Toyama Kirari in Toyama as completed in March 2015. The architect page explicitly says the building integrates a city library, glass art museum and local bank.', '2026-07-12T00:00:00Z'::timestamptz),
  ('f53171cc-293c-579b-9425-1fc020b62542'::uuid, 'toyama-kirari', 'museum', false, 1.000, 'https://kkaa.co.jp/en/project/toyama-kirari/', 'Kengo Kuma and Associates identifies Toyama Kirari in Toyama as completed in March 2015. The architect page explicitly says the building integrates a city library, glass art museum and local bank.', '2026-07-12T00:00:00Z'::timestamptz),
  ('f53171cc-293c-579b-9425-1fc020b62542'::uuid, 'toyama-kirari', 'mixed-use', false, 1.000, 'https://kkaa.co.jp/en/project/toyama-kirari/', 'Kengo Kuma and Associates identifies Toyama Kirari in Toyama as completed in March 2015. The architect page explicitly says the building integrates a city library, glass art museum and local bank.', '2026-07-12T00:00:00Z'::timestamptz),
  ('38b54039-7e4e-5318-a0e9-ef02e199c561'::uuid, 'minna-no-mori-gifu-media-cosmos', 'library', true, 1.000, 'https://g-mediacosmos.jp/cosmos/about/', 'The official municipal facility page identifies the central library, civic activity center, multicultural plaza and galleries as one complex. The same primary source records Toyo Ito and Associates as designer and construction completion in February 2015.', '2026-07-12T00:00:00Z'::timestamptz),
  ('38b54039-7e4e-5318-a0e9-ef02e199c561'::uuid, 'minna-no-mori-gifu-media-cosmos', 'community-center', false, 1.000, 'https://g-mediacosmos.jp/cosmos/about/', 'The official municipal facility page identifies the central library, civic activity center, multicultural plaza and galleries as one complex. The same primary source records Toyo Ito and Associates as designer and construction completion in February 2015.', '2026-07-12T00:00:00Z'::timestamptz),
  ('38b54039-7e4e-5318-a0e9-ef02e199c561'::uuid, 'minna-no-mori-gifu-media-cosmos', 'mixed-use', false, 1.000, 'https://g-mediacosmos.jp/cosmos/about/', 'The official municipal facility page identifies the central library, civic activity center, multicultural plaza and galleries as one complex. The same primary source records Toyo Ito and Associates as designer and construction completion in February 2015.', '2026-07-12T00:00:00Z'::timestamptz),
  ('2f80a130-04e2-594a-abbe-10d7ab138cd0'::uuid, 'nakanoshima-childrens-book-forest', 'library', true, 1.000, 'https://kodomohonnomori.osaka/about/', 'The official institution history records opening in July 2020 and design/donation by Tadao Ando Architect & Associates. The official source describes the building as a children''s book and arts culture facility in Nakanoshima Park.', '2026-07-12T00:00:00Z'::timestamptz),
  ('e619eac8-d46f-5df5-b630-1d030850ee75'::uuid, 'yusuhara-community-library', 'library', true, 1.000, 'https://kkaa.co.jp/en/project/yusuhara-community-library-yururi-yusuhara/', 'Kengo Kuma and Associates identifies the Kochi project as completed in October 2018. The architect page describes a library and welfare compound built with local cedar as an intergenerational town center.', '2026-07-12T00:00:00Z'::timestamptz),
  ('e619eac8-d46f-5df5-b630-1d030850ee75'::uuid, 'yusuhara-community-library', 'community-center', false, 1.000, 'https://kkaa.co.jp/en/project/yusuhara-community-library-yururi-yusuhara/', 'Kengo Kuma and Associates identifies the Kochi project as completed in October 2018. The architect page describes a library and welfare compound built with local cedar as an intergenerational town center.', '2026-07-12T00:00:00Z'::timestamptz),
  ('d5ad015d-93e2-5c1e-8cb3-174b5a6e098f'::uuid, 'musashino-place', 'library', true, 1.000, 'https://www.musashino.or.jp/place/1001617/1001618.html', 'The official Musashino Place page records completion in January 2011 and opening on 2011-07-09. The institution describes the building as a fusion of library, lifelong learning, civic activity and youth support functions.', '2026-07-12T00:00:00Z'::timestamptz),
  ('d5ad015d-93e2-5c1e-8cb3-174b5a6e098f'::uuid, 'musashino-place', 'community-center', false, 1.000, 'https://www.musashino.or.jp/place/1001617/1001618.html', 'The official Musashino Place page records completion in January 2011 and opening on 2011-07-09. The institution describes the building as a fusion of library, lifelong learning, civic activity and youth support functions.', '2026-07-12T00:00:00Z'::timestamptz),
  ('d5ad015d-93e2-5c1e-8cb3-174b5a6e098f'::uuid, 'musashino-place', 'mixed-use', false, 1.000, 'https://www.musashino.or.jp/place/1001617/1001618.html', 'The official Musashino Place page records completion in January 2011 and opening on 2011-07-09. The institution describes the building as a fusion of library, lifelong learning, civic activity and youth support functions.', '2026-07-12T00:00:00Z'::timestamptz),
  ('d77dfe51-52a0-552a-b617-c8007b994bea'::uuid, 'nasushiobara-city-library-miruru', 'library', true, 1.000, 'https://www.u-a-o.jp/project/20200401/a-public-library-at-the-heart-of-a-compact-vibrant-city', 'Urban Architecture Office identifies the project as Nasushiobara City Library and describes it as a public library integrated with the station surroundings. The architect states that the city planned it as a library serving as a community center and neighborhood catalyst.', '2026-07-12T00:00:00Z'::timestamptz),
  ('d77dfe51-52a0-552a-b617-c8007b994bea'::uuid, 'nasushiobara-city-library-miruru', 'community-center', false, 1.000, 'https://www.u-a-o.jp/project/20200401/a-public-library-at-the-heart-of-a-compact-vibrant-city', 'Urban Architecture Office identifies the project as Nasushiobara City Library and describes it as a public library integrated with the station surroundings. The architect states that the city planned it as a library serving as a community center and neighborhood catalyst.', '2026-07-12T00:00:00Z'::timestamptz),
  ('d801abfc-1290-5935-836d-9059ba4fedb5'::uuid, 'tonami-public-library', 'library', true, 1.000, 'https://mikami-arc.co.jp/work/%E7%A0%BA%E6%B3%A2%E5%B8%82%E7%AB%8B%E7%A0%BA%E6%B3%A2%E5%9B%B3%E6%9B%B8%E9%A4%A8', 'MIKAMI Architects records the current Sakaemachi library as completed in July 2020 and notes the Oshida Architectural Design joint venture. The previous image showed the former Omotemachi library; the replacement Commons file explicitly documents the library relocated and opened on 2020-11-01.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  required_function_matches integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 7
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 4
    OR (SELECT count(*) FROM building_seed) <> 8
    OR (SELECT count(*) FROM image_seed) <> 8
    OR (SELECT count(*) FROM profile_seed) <> 8
    OR (SELECT count(*) FROM assignment_seed) <> 17 THEN
    RAISE EXCEPTION 'Graduation library batch seed count mismatch';
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 3 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['library', 'community-center', 'museum', 'mixed-use']::text[]) AND is_active = true;
  IF required_function_matches <> 4
    OR NOT EXISTS (SELECT 1 FROM public.building_types WHERE slug = 'cultural') THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id OR target.building_id = seed.building_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation library batch requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 4
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 8
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 8
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 8
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 17
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 8
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 8 THEN
    RAISE EXCEPTION 'Graduation library batch post-write verification failed';
  END IF;
END $$;

COMMIT;
