-- Graduation theatre batch 001: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=theatre-001).
-- Scope: 1 new architects, 4 buildings, 4 images,
-- 4 profiles, 6 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation theatre batch 001 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('0cbb67cb-fcaf-4a55-a82b-e6b49cee9fea'::uuid, 'sanaa', 'SANAA', 'SANAA', 'SANAA', NULL, false),
  ('5f42cdc6-66ef-5689-9cbb-87ff3c519534'::uuid, 'snohetta', 'Snøhetta', 'Snøhetta', 'スノヘッタ', 'https://www.snohetta.com/', false),
  ('516ce1f7-20a5-5b7e-926c-7ee67ebc35b2'::uuid, 'henning-larsen', 'Henning Larsen 建筑事务所', 'Henning Larsen', 'ヘニング・ラーセン', 'https://www.henninglarsen.com/', false),
  ('f6b78370-cbc3-5d34-9b0e-c6e1db2c6fef'::uuid, 'diller-scofidio-renfro-rockwell-group', 'Diller Scofidio + Renfro + Rockwell Group', 'Diller Scofidio + Renfro + Rockwell Group', 'ディラー・スコフィディオ＋レンフロ + ロックウェル・グループ', 'https://dsrny.com/project/the-shed', true);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('59496d18-29b4-53e1-8158-dc29f8deba4e'::uuid, 'CASE-057', 'shogin-tact-tsuruoka', '荘银 TACT 鹤冈（鹤冈市文化会馆）', 'Shogin Tact Tsuruoka (Tsuruoka Cultural Hall)', '荘銀タクト鶴岡（鶴岡市文化会館）', '0cbb67cb-fcaf-4a55-a82b-e6b49cee9fea'::uuid, 'sanaa', 2017, 'published', '鹤冈', '日本', 'JP', 'cultural', 'https://tact-tsuruoka.jp/information'),
  ('c30fbe23-c030-563c-b67b-d083812ddbcc'::uuid, 'CASE-117', 'oslo-opera-house', '奥斯陆歌剧院', 'Oslo Opera House', 'オスロ・オペラハウス', '5f42cdc6-66ef-5689-9cbb-87ff3c519534'::uuid, 'snohetta', 2008, 'published', '奥斯陆', '挪威', 'NO', 'cultural', 'https://www.snohetta.com/projects/norwegian-national-opera-and-ballet'),
  ('b2675a07-3187-515e-bcd3-97ab8e32db96'::uuid, 'CASE-122', 'harpa-concert-hall', '哈帕音乐厅与会议中心', 'Harpa Concert Hall and Conference Centre', 'ハルパ・レイキャヴィク・コンサートホール＆会議センター', '516ce1f7-20a5-5b7e-926c-7ee67ebc35b2'::uuid, 'henning-larsen', 2011, 'published', '雷克雅未克', '冰岛', 'IS', 'cultural', 'https://www.henninglarsen.com/projects/harpa'),
  ('2f4194a7-3bba-55b2-af26-5952f483075d'::uuid, 'CASE-139', 'the-shed-hudson-yards', 'The Shed 艺术中心', 'The Shed', 'ザ・シェッド', 'f6b78370-cbc3-5d34-9b0e-c6e1db2c6fef'::uuid, 'diller-scofidio-renfro-rockwell-group', 2019, 'published', '纽约', '美国', 'US', 'cultural', 'https://dsrny.com/project/the-shed');

CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('c1b7eb6c-48ee-5bd8-a00a-29f133eec1a6'::uuid, '59496d18-29b4-53e1-8158-dc29f8deba4e'::uuid, 'shogin-tact-tsuruoka', 'CASE-057', '/images/graduation/cases/case-057-shogin-tact-tsuruoka.jpg', 'Ebiebi2', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Tact-Tsuruoka_1.jpg', 'exterior', true),
  ('8be0901e-f542-55c4-8e5e-b932ab086e84'::uuid, 'c30fbe23-c030-563c-b67b-d083812ddbcc'::uuid, 'oslo-opera-house', 'CASE-117', '/images/graduation/cases/case-117-oslo-opera-house.jpg', 'Christian David', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Oslo_Opera_House_(Den_Norske_Opera_%26_Ballett),_Norway.jpg', 'exterior', true),
  ('d9082466-3764-57ce-8443-5da2a41d61ab'::uuid, 'b2675a07-3187-515e-bcd3-97ab8e32db96'::uuid, 'harpa-concert-hall', 'CASE-122', '/images/graduation/cases/case-122-harpa-concert-hall.jpg', 'Gary J. Wood', 'Wikimedia Commons', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Harpa_From_Arnarh%C3%B3ll_(33650129491).jpg', 'exterior', true),
  ('0650b2be-99c9-58f2-88c4-09c1d2d04e52'::uuid, '2f4194a7-3bba-55b2-af26-5952f483075d'::uuid, 'the-shed-hudson-yards', 'CASE-139', '/images/graduation/cases/case-139-the-shed-hudson-yards.jpg', 'Ajay Suresh', 'Wikimedia Commons', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:The_Shed_-_Complete_(48206488176).jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-057', '59496d18-29b4-53e1-8158-dc29f8deba4e'::uuid, 'shogin-tact-tsuruoka', '地方文化厅以连续屋面和多功能空间支持演出、排练、市民活动和地方文化延续。', NULL, 'Tsuruoka Cultural Hall is a reference case for reading Design topic: culture厅, Design topic: 演出, citizenactivity, localculture. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Tsuruoka Cultural Hall」は、文化ホール・演出・市民活動・地域文化の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['文化厅', '演出', '市民活动', '地方文化', '屋面']::text[], '{}'::text[], ARRAY['Design topic: culture厅', 'Design topic: 演出', 'citizenactivity', 'localculture', 'Design topic: 屋面']::text[], ARRAY['文化ホール', '演出', '市民活動', '地域文化', '屋根']::text[], NULL, NULL, 'https://tact-tsuruoka.jp/information', 'published'),
  ('CASE-117', 'c30fbe23-c030-563c-b67b-d083812ddbcc'::uuid, 'oslo-opera-house', '屋根を都市の歩行広場として開放し、劇場を水辺の公共地形にした事例。入口と都市開放性を読める。', NULL, 'Reference case for Oslo Opera House: useful for comparing public program, urban interface, operation, and spatial experience.', '屋根を都市の歩行広場として開放し、劇場を水辺の公共地形にした事例。入口と都市開放性を読める。', ARRAY['劇場', '水辺', '公共屋根', '都市入口', '歩行']::text[], '{}'::text[], ARRAY['劇場', '水辺', '公共屋根', '都市入口', '歩行']::text[], ARRAY['劇場', '水辺', '公共屋根', '都市入口', '歩行']::text[], NULL, NULL, 'https://www.snohetta.com/projects/norwegian-national-opera-and-ballet', 'published'),
  ('CASE-122', 'b2675a07-3187-515e-bcd3-97ab8e32db96'::uuid, 'harpa-concert-hall', '港の風景とガラス外皮を結び、音楽、会議、観光を受け止める文化施設。気候と公共性の関係を読める。', NULL, 'Reference case for Harpa Concert Hall: useful for comparing public program, urban interface, operation, and spatial experience.', '港の風景とガラス外皮を結び、音楽、会議、観光を受け止める文化施設。気候と公共性の関係を読める。', ARRAY['音楽ホール', '港', 'ガラス外皮', '観光', '公共ロビー']::text[], '{}'::text[], ARRAY['音楽ホール', '港', 'ガラス外皮', '観光', '公共ロビー']::text[], ARRAY['音楽ホール', '港', 'ガラス外皮', '観光', '公共ロビー']::text[], NULL, NULL, 'https://www.henninglarsen.com/projects/harpa', 'published'),
  ('CASE-139', '2f4194a7-3bba-55b2-af26-5952f483075d'::uuid, 'the-shed-hudson-yards', '可動外皮によって展示、上演、イベント空間を切り替える文化施設。都市文化の変化に対応する建築を考えられる。', NULL, 'Reference case for The Shed: useful for comparing public program, urban interface, operation, and spatial experience.', '可動外皮によって展示、上演、イベント空間を切り替える文化施設。都市文化の変化に対応する建築を考えられる。', ARRAY['文化施設', '可動外皮', '展示', '上演', 'イベント']::text[], '{}'::text[], ARRAY['文化施設', '可動外皮', '展示', '上演', 'イベント']::text[], ARRAY['文化施設', '可動外皮', '展示', '上演', 'イベント']::text[], NULL, NULL, 'https://dsrny.com/project/the-shed', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('59496d18-29b4-53e1-8158-dc29f8deba4e'::uuid, 'shogin-tact-tsuruoka', 'theatre', true, 1.000, 'https://tact-tsuruoka.jp/information', 'Tsuruoka City records completion at the end of August 2017 and the March 2018 grand opening of the current cultural hall. The institution documents a live-acoustic theatre hall for concerts and civic cultural events; the design record identifies SANAA.', '2026-07-12T00:00:00Z'::timestamptz),
  ('c30fbe23-c030-563c-b67b-d083812ddbcc'::uuid, 'oslo-opera-house', 'theatre', true, 1.000, 'https://www.snohetta.com/projects/norwegian-national-opera-and-ballet', 'Snøhetta records the completed 2000–2008 Norwegian National Opera and Ballet project in Oslo and describes its main theatre and public roof plaza.', '2026-07-12T00:00:00Z'::timestamptz),
  ('b2675a07-3187-515e-bcd3-97ab8e32db96'::uuid, 'harpa-concert-hall', 'theatre', true, 1.000, 'https://www.henninglarsen.com/projects/harpa', 'Henning Larsen records the completed 2005–2011 Reykjavík concert hall and conference centre, four auditoriums and collaboration with Olafur Eliasson on the façade. The canonical architect relation uses Henning Larsen while Batteríið Architects and the façade collaboration remain in the graduation profile evidence.', '2026-07-12T00:00:00Z'::timestamptz),
  ('b2675a07-3187-515e-bcd3-97ab8e32db96'::uuid, 'harpa-concert-hall', 'mixed-use', false, 1.000, 'https://www.henninglarsen.com/projects/harpa', 'Henning Larsen records the completed 2005–2011 Reykjavík concert hall and conference centre, four auditoriums and collaboration with Olafur Eliasson on the façade. The canonical architect relation uses Henning Larsen while Batteríið Architects and the façade collaboration remain in the graduation profile evidence.', '2026-07-12T00:00:00Z'::timestamptz),
  ('2f4194a7-3bba-55b2-af26-5952f483075d'::uuid, 'the-shed-hudson-yards', 'theatre', true, 1.000, 'https://dsrny.com/project/the-shed', 'Diller Scofidio + Renfro records the April 2019 opening in New York, identifies DS+R as lead architect and Rockwell Group as collaborating architect, and describes performance, visual-art and event programmes enabled by the movable shell.', '2026-07-12T00:00:00Z'::timestamptz),
  ('2f4194a7-3bba-55b2-af26-5952f483075d'::uuid, 'the-shed-hudson-yards', 'mixed-use', false, 1.000, 'https://dsrny.com/project/the-shed', 'Diller Scofidio + Renfro records the April 2019 opening in New York, identifies DS+R as lead architect and Rockwell Group as collaborating architect, and describes performance, visual-art and event programmes enabled by the movable shell.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 4
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 1
    OR (SELECT count(*) FROM building_seed) <> 4
    OR (SELECT count(*) FROM image_seed) <> 4
    OR (SELECT count(*) FROM profile_seed) <> 4
    OR (SELECT count(*) FROM assignment_seed) <> 6 THEN
    RAISE EXCEPTION 'Graduation theatre batch 001 seed count mismatch';
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 3 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['theatre', 'mixed-use']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['cultural']::text[]);
  IF required_function_matches <> 2
    OR required_type_matches <> 1 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id OR target.building_id = seed.building_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation theatre batch 001 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 1
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 4
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 4
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 4
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 6
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 4
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 4 THEN
    RAISE EXCEPTION 'Graduation theatre batch 001 post-write verification failed';
  END IF;
END $$;

COMMIT;
