-- Graduation museum batch 001: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=museum-001).
-- Scope: 9 new architects, 14 buildings, 14 images,
-- 14 profiles, 16 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation museum batch 001 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('45779757-de71-5295-b346-e2b7331388a2'::uuid, 'hiroshi-sambuichi', '三分一博志', 'Hiroshi Sambuichi', '三分一博志', 'https://benesse-artsite.jp/en/art/seirensho.html', true),
  ('70f5f170-6142-552e-acfa-9f12af2257bb'::uuid, 'ryue-nishizawa', '西泽立卫', 'Ryue Nishizawa', '西沢立衛', 'https://towadaartcenter.com/en/about/', true),
  ('51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', '隈研吾', 'Kengo Kuma', '隈研吾', NULL, false),
  ('61138a5c-9829-5fca-9619-9872e84dbce5'::uuid, 'nikken-sekkei', '日建设计', 'Nikken Sekkei', '日建設計', 'https://www.nikken.co.jp/en/', true),
  ('aa16eb77-f51a-418b-a464-d46ce25cc0d8'::uuid, 'shigeru-ban', '坂茂', 'Shigeru Ban', '坂茂', NULL, false),
  ('d6c1fb23-17e0-5256-a571-99d7dcf777bb'::uuid, 'jun-aoki-tezzo-nishizawa', '青木淳 + 西泽彻夫', 'Jun Aoki + Tezzo Nishizawa', '青木淳 + 西澤徹夫', 'https://kyotocity-kyocera.museum/en/architecture', true),
  ('1be57c89-0007-56f8-a7d1-96b09e5b1bc5'::uuid, 'takenaka-corporation', '竹中工务店', 'Takenaka Corporation', '竹中工務店', 'https://www.takenaka.co.jp/', true),
  ('86de630c-8c9f-5ba3-b40a-278a70c29015'::uuid, 'yasuda-atelier', '安田工作室', 'Yasuda Atelier', '安田アトリエ', 'https://www.yasudaatelier.com/', true),
  ('af49165b-6ce2-5792-956a-dead0645df7f'::uuid, 'peter-cook-colin-fournier', 'Peter Cook + Colin Fournier', 'Peter Cook + Colin Fournier', 'ピーター・クック + コリン・フルニエ', 'https://www.museum-joanneum.at/en/kunsthaus-graz/discover/architecture/thearchitects', true),
  ('b1937cba-0c5b-4f4d-a833-a4ef88019f88'::uuid, 'zaha-hadid', '扎哈·哈迪德', 'Zaha Hadid', 'ザハ・ハディド', NULL, false),
  ('516ce1f7-20a5-5b7e-926c-7ee67ebc35b2'::uuid, 'henning-larsen', 'Henning Larsen 建筑事务所', 'Henning Larsen', 'ヘニング・ラーセン', 'https://www.henninglarsen.com/', true),
  ('45622cdd-8e07-5a72-9857-9cadf56ba3a3'::uuid, 'heatherwick-studio', 'Heatherwick Studio', 'Heatherwick Studio', 'ヘザウィック・スタジオ', 'https://heatherwick.com/', true);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('9a7ada39-c60a-5805-ae54-e5df5b10a780'::uuid, 'CASE-041', 'inujima-seirensho-art-museum', '犬岛精炼所美术馆', 'Inujima Seirensho Art Museum', '犬島精錬所美術館', '45779757-de71-5295-b346-e2b7331388a2'::uuid, 'hiroshi-sambuichi', 2008, 'published', '冈山', '日本', 'JP', 'cultural', 'https://benesse-artsite.jp/en/art/seirensho.html'),
  ('30aef487-cc52-5198-af18-59fee1add670'::uuid, 'CASE-045', 'teshima-art-museum', '丰岛美术馆', 'Teshima Art Museum', '豊島美術館', '70f5f170-6142-552e-acfa-9f12af2257bb'::uuid, 'ryue-nishizawa', 2010, 'published', '土庄', '日本', 'JP', 'cultural', 'https://benesse-artsite.jp/en/art/teshima-artmuseum.html'),
  ('053fb9eb-e536-5a1a-a070-5e1d23a865e7'::uuid, 'CASE-047', 'towada-art-center', '十和田市现代美术馆', 'Towada Art Center', '十和田市現代美術館', '70f5f170-6142-552e-acfa-9f12af2257bb'::uuid, 'ryue-nishizawa', 2008, 'published', '十和田', '日本', 'JP', 'cultural', 'https://towadaartcenter.com/en/about/'),
  ('2f162c1a-4861-564e-ab0b-1080eaec389d'::uuid, 'CASE-051', 'kadokawa-culture-museum', '角川武藏野博物馆', 'Kadokawa Culture Museum', '角川武蔵野ミュージアム', '51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', 2020, 'published', '所泽', '日本', 'JP', 'cultural', 'https://kkaa.co.jp/en/project/tokorozawa-sakura-town-kadokawa-culture-museum/'),
  ('73f72808-e942-57e1-9e81-e7da0701323a'::uuid, 'CASE-052', 'hoki-museum', 'Hoki 美术馆', 'Hoki Museum', 'ホキ美術館', '61138a5c-9829-5fca-9619-9872e84dbce5'::uuid, 'nikken-sekkei', 2010, 'published', '千叶', '日本', 'JP', 'cultural', 'https://www.nikken.co.jp/en/projects/cultural/hoki_museum.html'),
  ('745996bf-533b-56f3-a80b-4f0fc7b2d269'::uuid, 'CASE-053', 'oita-prefectural-art-museum', '大分县立美术馆', 'Oita Prefectural Art Museum', '大分県立美術館', 'aa16eb77-f51a-418b-a464-d46ce25cc0d8'::uuid, 'shigeru-ban', 2014, 'published', '大分', '日本', 'JP', 'cultural', 'https://shigerubanarchitects.com/works/oita-prefectural-art-museum/'),
  ('abb72157-0dbf-549c-a378-3fe8ae013bd9'::uuid, 'CASE-054', 'kyoto-city-kyocera-museum-of-art', '京都市京瓷美术馆', 'Kyoto City KYOCERA Museum of Art', '京都市京セラ美術館', 'd6c1fb23-17e0-5256-a571-99d7dcf777bb'::uuid, 'jun-aoki-tezzo-nishizawa', 2020, 'published', '京都', '日本', 'JP', 'cultural', 'https://kyotocity-kyocera.museum/en/architecture'),
  ('bf88b372-42b0-532f-87bb-33077fa0b6da'::uuid, 'CASE-055', 'nagasaki-prefectural-art-museum', '长崎县美术馆', 'Nagasaki Prefectural Art Museum', '長崎県美術館', '51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', 2005, 'published', '长崎', '日本', 'JP', 'cultural', 'https://kkaa.co.jp/en/project/nagasaki-prefectural-art-museum/'),
  ('22d7c427-87f9-5884-84f0-f6c88fc65bde'::uuid, 'CASE-058', 'sagawa-art-museum', '佐川美术馆', 'Sagawa Art Museum', '佐川美術館', '1be57c89-0007-56f8-a7d1-96b09e5b1bc5'::uuid, 'takenaka-corporation', 1998, 'published', '守山', '日本', 'JP', 'cultural', 'https://www.sagawa-artmuseum.or.jp/en/'),
  ('f0416e50-a744-5391-b680-5948f6636ae8'::uuid, 'CASE-060', 'fukuda-art-museum', '福田美术馆', 'Fukuda Art Museum', '福田美術館', '86de630c-8c9f-5ba3-b40a-278a70c29015'::uuid, 'yasuda-atelier', 2019, 'published', '京都', '日本', 'JP', 'cultural', 'https://fukuda-art-museum.jp/en/concept'),
  ('65cca6df-9211-5abc-8979-b0d618b42207'::uuid, 'CASE-109', 'kunsthaus-graz', '格拉茨美术馆', 'Kunsthaus Graz', 'クンストハウス・グラーツ', 'af49165b-6ce2-5792-956a-dead0645df7f'::uuid, 'peter-cook-colin-fournier', 2003, 'published', '格拉茨', '奥地利', 'AT', 'cultural', 'https://www.museum-joanneum.at/en/kunsthaus-graz/discover/architecture'),
  ('4a276826-cf33-57ac-80ea-ea7ea805f0ad'::uuid, 'CASE-118', 'maxxi-museum-of-xxi-century-arts', 'MAXXI 21世纪国家艺术博物馆', 'MAXXI — Museum of XXI Century Arts', 'MAXXI 国立21世紀美術館', 'b1937cba-0c5b-4f4d-a833-a4ef88019f88'::uuid, 'zaha-hadid', 2009, 'published', '罗马', '意大利', 'IT', 'cultural', 'https://www.zha.com/projects/architecture/maxxi-museum-of-xxi-century-arts'),
  ('436fc652-fae5-57e5-8907-47f2b496cc73'::uuid, 'CASE-124', 'moesgaard-museum', '莫斯高博物馆', 'Moesgaard Museum', 'モースゴー博物館', '516ce1f7-20a5-5b7e-926c-7ee67ebc35b2'::uuid, 'henning-larsen', 2014, 'published', '奥胡斯', '丹麦', 'DK', 'cultural', 'https://www.henninglarsen.com/projects/moesgaard'),
  ('37417806-10db-5418-a401-cfddbee92dff'::uuid, 'CASE-132', 'zeitz-mocaa', '蔡茨非洲当代艺术博物馆', 'Zeitz MOCAA', 'ツァイツ・アフリカ現代美術館', '45622cdd-8e07-5a72-9857-9cadf56ba3a3'::uuid, 'heatherwick-studio', 2017, 'published', '开普敦', '南非', 'ZA', 'cultural', 'https://heatherwick.com/projects/buildings/zeitz-mocaa/');

CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('b384cf69-d339-5964-b0f2-ecc079528285'::uuid, '9a7ada39-c60a-5805-ae54-e5df5b10a780'::uuid, 'inujima-seirensho-art-museum', 'CASE-041', '/images/graduation/cases/case-041-inujima-seirensho-art-museum.jpg', 'KimonBerlin', 'Wikimedia Commons', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Inujima_Seirensho_Art_Museum_(8918114910).jpg', 'exterior', true),
  ('a42bf291-5e5b-5818-9662-76a59ba81368'::uuid, '30aef487-cc52-5198-af18-59fee1add670'::uuid, 'teshima-art-museum', 'CASE-045', '/images/graduation/cases/case-045-teshima-art-museum.jpg', 'Bea Phi', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Exterior_of_the_Teshima_Art_Museum.jpg', 'exterior', true),
  ('bd027c34-d7c4-567d-ba7f-8007ed261ce0'::uuid, '053fb9eb-e536-5a1a-a070-5e1d23a865e7'::uuid, 'towada-art-center', 'CASE-047', '/images/graduation/cases/case-047-towada-art-center.jpg', 'Angaurits', 'Wikimedia Commons', 'CC0', 'https://commons.wikimedia.org/wiki/File:Towada_art_center.JPG', 'exterior', true),
  ('1d412ccb-f9a7-5e95-94cf-bdb9a9bf2e7b'::uuid, '2f162c1a-4861-564e-ab0b-1080eaec389d'::uuid, 'kadokawa-culture-museum', 'CASE-051', '/images/graduation/cases/case-051-kadokawa-culture-museum.jpg', 'Souka Kinmei', 'Wikimedia Commons', 'CC0', 'https://commons.wikimedia.org/wiki/File:本棟から角川武蔵野ミュージアムを写す.jpg', 'exterior', true),
  ('fde3c638-5f6d-5b94-81bf-d3fe04339e9c'::uuid, '73f72808-e942-57e1-9e81-e7da0701323a'::uuid, 'hoki-museum', 'CASE-052', 'https://upload.wikimedia.org/wikipedia/commons/1/16/Hoki_museum_outside_rear_001.jpg', 'W650neco', 'Wikimedia Commons', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Hoki_museum_outside_rear_001.jpg', 'exterior', true),
  ('0acfe2b7-dcd2-592e-94fc-53c8ddde350c'::uuid, '745996bf-533b-56f3-a80b-4f0fc7b2d269'::uuid, 'oita-prefectural-art-museum', 'CASE-053', 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Oita_OPAM_1.jpg', '大分帰省中', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Oita_OPAM_1.jpg', 'exterior', true),
  ('86a984ab-ef44-5fd4-a273-05b44688cefe'::uuid, 'abb72157-0dbf-549c-a378-3fe8ae013bd9'::uuid, 'kyoto-city-kyocera-museum-of-art', 'CASE-054', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Kyoto-City-KYOCERA-Museum-of-Art.jpg', 'Tokyo-Good', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Kyoto-City-KYOCERA-Museum-of-Art.jpg', 'exterior', true),
  ('89c9be7a-a4ca-5fce-ba34-12275e527398'::uuid, 'bf88b372-42b0-532f-87bb-33077fa0b6da'::uuid, 'nagasaki-prefectural-art-museum', 'CASE-055', 'https://upload.wikimedia.org/wikipedia/commons/6/68/Nagasaki_Prefectural_Art_Museum_%283611415894%29.jpg', 'Kenta Mabuchi', 'Wikimedia Commons', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Nagasaki_Prefectural_Art_Museum_(3611415894).jpg', 'exterior', true),
  ('fdffea8a-efda-553e-9796-94d33458cab8'::uuid, '22d7c427-87f9-5884-84f0-f6c88fc65bde'::uuid, 'sagawa-art-museum', 'CASE-058', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Sagawa_art_museum01s3200.jpg', '663highland', 'Wikimedia Commons', 'CC BY 2.5', 'https://commons.wikimedia.org/wiki/File:Sagawa_art_museum01s3200.jpg', 'exterior', true),
  ('ae7a2e7a-3958-5871-94c8-7aceb6374463'::uuid, 'f0416e50-a744-5391-b680-5948f6636ae8'::uuid, 'fukuda-art-museum', 'CASE-060', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Fukuda_art_museum.jpg', '運動会プロテインパワー', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Fukuda_art_museum.jpg', 'exterior', true),
  ('d81b9f27-3f48-5d8e-b97b-d6b0e6b6994b'::uuid, '65cca6df-9211-5abc-8979-b0d618b42207'::uuid, 'kunsthaus-graz', 'CASE-109', 'https://upload.wikimedia.org/wikipedia/commons/3/38/Graz_Kunsthaus-4476.jpg', 'Isiwal', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Graz_Kunsthaus-4476.jpg', 'exterior', true),
  ('e165b59a-513e-5dd9-be17-4edfefe2e3e0'::uuid, '4a276826-cf33-57ac-80ea-ea7ea805f0ad'::uuid, 'maxxi-museum-of-xxi-century-arts', 'CASE-118', 'https://upload.wikimedia.org/wikipedia/commons/3/30/L%27int%C3%A9rieur_du_MAXXI_%28Rome%29_%2834216328131%29.jpg', 'Jean-Pierre Dalbéra', 'Wikimedia Commons', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:L%27int%C3%A9rieur_du_MAXXI_(Rome)_(34216328131).jpg', 'interior', true),
  ('16388114-8320-5fa5-a236-e35551a31eba'::uuid, '436fc652-fae5-57e5-8907-47f2b496cc73'::uuid, 'moesgaard-museum', 'CASE-124', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Moesg%C3%A5rd%20Museum%2C%20New%20building1.JPG', 'Gardar Rurak', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Moesg%C3%A5rd_Museum%2C_New_building1.JPG', 'exterior', true),
  ('c5a1fb98-34b2-5d7d-88ec-f8872f334b16'::uuid, '37417806-10db-5418-a401-cfddbee92dff'::uuid, 'zeitz-mocaa', 'CASE-132', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Exterior%20Zeitz%20MOCAA%20-%20Museum%20of%20Contermporary%20Art%20Africa.jpg', 'Michael Rowe', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Exterior_Zeitz_MOCAA_-_Museum_of_Contermporary_Art_Africa.jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-041', '9a7ada39-c60a-5805-ae54-e5df5b10a780'::uuid, 'inujima-seirensho-art-museum', '旧铜精炼所遗构被保存并转化为艺术和环境体验，展示工业遗产再生的空间可能。', NULL, 'Inujima Seirensho Art Museum is a reference case for reading Design topic: 工业heritage, art, environmental education, Design topic: 离岛. It can inform thesis thinking about mixed programs, operation, and place-making.', '旧精錬所の遺構を、アートと環境体験の場へ転用した事例。産業遺産を壊さず、場所の記憶を新しい公共体験に変えている。', ARRAY['工业遗产', '艺术', '环境教育', '离岛', '再利用']::text[], '{}'::text[], ARRAY['Design topic: 工业heritage', 'art', 'environmental education', 'Design topic: 离岛', 'reuse']::text[], ARRAY['産業遺産', 'アート', '環境教育', '離島', '再利用']::text[], NULL, NULL, 'https://benesse-artsite.jp/en/art/seirensho.html', 'published'),
  ('CASE-045', '30aef487-cc52-5198-af18-59fee1add670'::uuid, 'teshima-art-museum', '低矮无柱壳体与水滴、风和场地植物共同形成艺术、自然和身体感知的空间。', NULL, 'Teshima Art Museum is a reference case for reading art museum, nature, Design topic: 离岛, Design topic: 身体体验. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Teshima Art Museum」は、美術館・自然・離島・身体体験の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['美术馆', '自然', '离岛', '身体体验', '环境']::text[], '{}'::text[], ARRAY['art museum', 'nature', 'Design topic: 离岛', 'Design topic: 身体体验', 'Design topic: 环境']::text[], ARRAY['美術館', '自然', '離島', '身体体験', '環境']::text[], NULL, NULL, 'https://benesse-artsite.jp/en/art/teshima-artmuseum.html', 'published'),
  ('CASE-047', '053fb9eb-e536-5a1a-a070-5e1d23a865e7'::uuid, 'towada-art-center', '分散盒子与街道结合，艺术设施成为地方城市街景再生和市民交流的核心。', NULL, 'Towada Art Center is a reference case for reading art museum, artneighborhood, localregeneration, Design topic: 步行. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Towada Art Center」は、美術館・アート街区・地域再生・歩行の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['美术馆', '艺术街区', '地方再生', '步行', '市民交流']::text[], '{}'::text[], ARRAY['art museum', 'artneighborhood', 'localregeneration', 'Design topic: 步行', 'citizenexchange']::text[], ARRAY['美術館', 'アート街区', '地域再生', '歩行', '市民交流']::text[], NULL, NULL, 'https://towadaartcenter.com/en/about/', 'published'),
  ('CASE-051', '2f162c1a-4861-564e-ab0b-1080eaec389d'::uuid, 'kadokawa-culture-museum', '巨石般的文化博物馆把出版、艺术、动漫、图书和活动组织成郊区文化目的地。', NULL, 'Kadokawa Culture Museum is a reference case for reading cultural complex, Design topic: 博物馆, Design topic: 出版, youthculture. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Kadokawa Culture Museum」は、文化複合・博物館・出版・若者文化の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['文化复合', '博物馆', '出版', '青年文化', '郊区']::text[], '{}'::text[], ARRAY['cultural complex', 'Design topic: 博物馆', 'Design topic: 出版', 'youthculture', 'Design topic: 郊区']::text[], ARRAY['文化複合', '博物館', '出版', '若者文化', '郊外']::text[], NULL, NULL, 'https://kkaa.co.jp/en/project/tokorozawa-sakura-town-kadokawa-culture-museum/', 'published'),
  ('CASE-052', '73f72808-e942-57e1-9e81-e7da0701323a'::uuid, 'hoki-museum', '弯曲悬挑画廊嵌入绿色环境，为写实绘画提供安静、连续且沉浸的观看空间。', NULL, 'Hoki Museum is a reference case for reading art museum, Design topic: 安静, nature, Design topic: 私人收藏. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Hoki Museum」は、美術館・静か・自然・個人コレクションの関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['美术馆', '安静', '自然', '私人收藏', '疗愈']::text[], '{}'::text[], ARRAY['art museum', 'Design topic: 安静', 'nature', 'Design topic: 私人收藏', 'Design topic: 疗愈']::text[], ARRAY['美術館', '静か', '自然', '個人コレクション', '癒やし']::text[], NULL, NULL, 'https://www.nikken.co.jp/en/projects/cultural/hoki_museum.html', 'published'),
  ('CASE-053', '745996bf-533b-56f3-a80b-4f0fc7b2d269'::uuid, 'oita-prefectural-art-museum', '开放立面和公共界面让美术馆成为城市会客厅，弱化传统美术馆的封闭感。', NULL, 'Oita Prefectural Art Museum is a reference case for reading art museum, Design topic: open界面, Design topic: citizen广场, localculture. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Oita Prefectural Art Museum」は、美術館・開いた接地面・市民広場・地域文化の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['美术馆', '开放界面', '市民广场', '地方文化', '活动']::text[], '{}'::text[], ARRAY['art museum', 'Design topic: open界面', 'Design topic: citizen广场', 'localculture', 'activity']::text[], ARRAY['美術館', '開いた接地面', '市民広場', '地域文化', '活動']::text[], NULL, NULL, 'https://shigerubanarchitects.com/works/oita-prefectural-art-museum/', 'published'),
  ('CASE-054', 'abb72157-0dbf-549c-a378-3fe8ae013bd9'::uuid, 'kyoto-city-kyocera-museum-of-art', '历史公共美术馆通过入口、广场和地下动线更新，在保留记忆的同时打开城市界面。', NULL, 'Kyoto City KYOCERA Museum of Art is a reference case for reading Design topic: history建筑, art museumrenewal, entry, Design topic: 广场. It can inform thesis thinking about mixed programs, operation, and place-making.', '歴史的建築の保存と美術館更新を重ね、入口、広場、展示動線を現代化した事例。文化記憶と公共性を比較できる。', ARRAY['历史建筑', '美术馆更新', '入口', '广场', '文化记忆']::text[], '{}'::text[], ARRAY['Design topic: history建筑', 'art museumrenewal', 'entry', 'Design topic: 广场', 'Design topic: culture记忆']::text[], ARRAY['歴史的建築', '美術館更新', '入口', '広場', '文化記憶']::text[], NULL, NULL, 'https://kyotocity-kyocera.museum/en/architecture', 'published'),
  ('CASE-055', 'bf88b372-42b0-532f-87bb-33077fa0b6da'::uuid, 'nagasaki-prefectural-art-museum', '跨越运河的美术馆把两块场地和水边景观连接起来，形成面向港口的文化公共空间。', NULL, 'Nagasaki Prefectural Art Museum is a reference case for reading waterfront, art museum, Design topic: 运河, Design topic: 港口. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Nagasaki Prefectural Art Museum」は、水辺・美術館・運河・港の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['水边', '美术馆', '运河', '港口', '景观']::text[], '{}'::text[], ARRAY['waterfront', 'art museum', 'Design topic: 运河', 'Design topic: 港口', 'Design topic: 景观']::text[], ARRAY['水辺', '美術館', '運河', '港', '景観']::text[], NULL, NULL, 'https://kkaa.co.jp/en/project/nagasaki-prefectural-art-museum/', 'published'),
  ('CASE-058', '22d7c427-87f9-5884-84f0-f6c88fc65bde'::uuid, 'sagawa-art-museum', '围绕人工水庭的低层美术馆被称为漂浮的美术馆，艺术、茶室和水景形成静谧体验。', NULL, 'Sagawa Art Museum is a reference case for reading art museum, Design topic: 水庭, Design topic: 茶室, nature. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Sagawa Art Museum」は、美術館・水庭・茶室・自然の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['美术馆', '水庭', '茶室', '自然', '安静']::text[], '{}'::text[], ARRAY['art museum', 'Design topic: 水庭', 'Design topic: 茶室', 'nature', 'Design topic: 安静']::text[], ARRAY['美術館', '水庭', '茶室', '自然', '静か']::text[], NULL, NULL, 'https://www.sagawa-artmuseum.or.jp/en/', 'published'),
  ('CASE-060', 'f0416e50-a744-5391-b680-5948f6636ae8'::uuid, 'fukuda-art-museum', '嵯峨岚山的美术馆强调未来百年的日本建筑标准，连接传统收藏、庭园和观光街区。', NULL, 'Fukuda Art Museum is a reference case for reading art museum, Design topic: 传统culture, tourism, Design topic: 庭园. It can inform thesis thinking about mixed programs, operation, and place-making.', '観光地の中で、美術館、庭園、伝統文化を落ち着いた滞在体験としてまとめた事例。来訪者利用と地域景観の距離感を読める。', ARRAY['美术馆', '传统文化', '观光', '庭园', '历史街区']::text[], '{}'::text[], ARRAY['art museum', 'Design topic: 传统culture', 'tourism', 'Design topic: 庭园', 'historyneighborhood']::text[], ARRAY['美術館', '伝統文化', '観光', '庭園', '歴史街区']::text[], NULL, NULL, 'https://fukuda-art-museum.jp/en/concept', 'published'),
  ('CASE-109', '65cca6df-9211-5abc-8979-b0d618b42207'::uuid, 'kunsthaus-graz', '历史街区の中に強い現代美術館を挿入し、都市の記憶と新しい文化を対比させる。', NULL, 'A contemporary art museum inserted into a historic urban fabric, contrasting memory and new cultural identity.', '歴史的街区に強い造形の現代美術館を挿入した事例。保存、更新、入口、都市景観の対比を考える参考になる。', ARRAY['美术馆', '历史街区', '城市更新', '入口', '文化地标']::text[], '{}'::text[], ARRAY['museum', 'historic district', 'urban renewal', 'entrance', 'cultural landmark']::text[], ARRAY['美術館', '歴史街区', '都市更新', '入口', '文化拠点']::text[], NULL, NULL, 'https://www.museum-joanneum.at/kunsthaus-graz', 'published'),
  ('CASE-118', '4a276826-cf33-57ac-80ea-ea7ea805f0ad'::uuid, 'maxxi-museum-of-xxi-century-arts', '流動的な展示動線で現代美術館を都市的な内部街路として構成した事例。展示と移動の関係を考えられる。', NULL, 'Reference case for MAXXI: useful for comparing public program, urban interface, operation, and spatial experience.', '流動的な展示動線で現代美術館を都市的な内部街路として構成した事例。展示と移動の関係を考えられる。', ARRAY['美術館', '展示動線', '内部街路', '現代文化', '都市性']::text[], '{}'::text[], ARRAY['美術館', '展示動線', '内部街路', '現代文化', '都市性']::text[], ARRAY['美術館', '展示動線', '内部街路', '現代文化', '都市性']::text[], NULL, NULL, 'https://www.zaha-hadid.com/architecture/maxxi/', 'published'),
  ('CASE-124', '436fc652-fae5-57e5-8907-47f2b496cc73'::uuid, 'moesgaard-museum', '斜面の屋根と展示を一体化し、博物館を景観と歩行体験に接続した事例。自然教育や地域記憶に応用できる。', NULL, 'Reference case for Moesgaard Museum: useful for comparing public program, urban interface, operation, and spatial experience.', '斜面の屋根と展示を一体化し、博物館を景観と歩行体験に接続した事例。自然教育や地域記憶に応用できる。', ARRAY['博物館', '景観', '屋根', '自然教育', '地域記憶']::text[], '{}'::text[], ARRAY['博物館', '景観', '屋根', '自然教育', '地域記憶']::text[], ARRAY['博物館', '景観', '屋根', '自然教育', '地域記憶']::text[], NULL, NULL, 'https://www.henninglarsen.com/projects/moesgaard', 'published'),
  ('CASE-132', '37417806-10db-5418-a401-cfddbee92dff'::uuid, 'zeitz-mocaa', '穀物サイロを現代美術館へ転用した事例。産業遺産、展示、観光、都市再生の関係を読める。', NULL, 'Reference case for Zeitz MOCAA: useful for comparing public program, urban interface, operation, and spatial experience.', '穀物サイロを現代美術館へ転用した事例。産業遺産、展示、観光、都市再生の関係を読める。', ARRAY['産業遺産', '美術館', 'サイロ', '再利用', '都市再生']::text[], '{}'::text[], ARRAY['産業遺産', '美術館', 'サイロ', '再利用', '都市再生']::text[], ARRAY['産業遺産', '美術館', 'サイロ', '再利用', '都市再生']::text[], NULL, NULL, 'https://heatherwick.com/projects/buildings/zeitz-mocaa/', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('9a7ada39-c60a-5805-ae54-e5df5b10a780'::uuid, 'inujima-seirensho-art-museum', 'museum', true, 1.000, 'https://benesse-artsite.jp/en/art/seirensho.html', 'Benesse identifies the 2008 Inujima project as an art museum that preserves and recreates copper-refinery remains through Hiroshi Sambuichi''s architecture.', '2026-07-12T00:00:00Z'::timestamptz),
  ('30aef487-cc52-5198-af18-59fee1add670'::uuid, 'teshima-art-museum', 'museum', true, 1.000, 'https://benesse-artsite.jp/en/art/teshima-artmuseum.html', 'Benesse identifies Ryue Nishizawa as architect of the 2010 Teshima Art Museum and describes its low concrete shell and two openings.', '2026-07-12T00:00:00Z'::timestamptz),
  ('053fb9eb-e536-5a1a-a070-5e1d23a865e7'::uuid, 'towada-art-center', 'museum', true, 1.000, 'https://towadaartcenter.com/en/about/', 'Towada Art Center names Ryue Nishizawa as architect and describes the Arts Towada project launched in 2008.', '2026-07-12T00:00:00Z'::timestamptz),
  ('2f162c1a-4861-564e-ab0b-1080eaec389d'::uuid, 'kadokawa-culture-museum', 'museum', true, 1.000, 'https://kkaa.co.jp/en/project/tokorozawa-sakura-town-kadokawa-culture-museum/', 'KKAA records October 2020 completion in Saitama and classifies the project as Gallery/Museum/Cultural. KADOKAWA records Kengo Kuma and Associates as design supervisor and Kajima as design-build contractor; the canonical architect relation therefore uses Kengo Kuma while the collaboration remains in the graduation profile.', '2026-07-12T00:00:00Z'::timestamptz),
  ('2f162c1a-4861-564e-ab0b-1080eaec389d'::uuid, 'kadokawa-culture-museum', 'library', false, 1.000, 'https://kkaa.co.jp/en/project/tokorozawa-sakura-town-kadokawa-culture-museum/', 'KKAA records October 2020 completion in Saitama and classifies the project as Gallery/Museum/Cultural. KADOKAWA records Kengo Kuma and Associates as design supervisor and Kajima as design-build contractor; the canonical architect relation therefore uses Kengo Kuma while the collaboration remains in the graduation profile.', '2026-07-12T00:00:00Z'::timestamptz),
  ('2f162c1a-4861-564e-ab0b-1080eaec389d'::uuid, 'kadokawa-culture-museum', 'mixed-use', false, 1.000, 'https://kkaa.co.jp/en/project/tokorozawa-sakura-town-kadokawa-culture-museum/', 'KKAA records October 2020 completion in Saitama and classifies the project as Gallery/Museum/Cultural. KADOKAWA records Kengo Kuma and Associates as design supervisor and Kajima as design-build contractor; the canonical architect relation therefore uses Kengo Kuma while the collaboration remains in the graduation profile.', '2026-07-12T00:00:00Z'::timestamptz),
  ('73f72808-e942-57e1-9e81-e7da0701323a'::uuid, 'hoki-museum', 'museum', true, 1.000, 'https://www.nikken.co.jp/en/projects/cultural/hoki_museum.html', 'Nikken Sekkei records the Hoki Museum in Chiba with 2010 completion and describes the stacked curved tubes and 30-meter cantilevers.', '2026-07-12T00:00:00Z'::timestamptz),
  ('745996bf-533b-56f3-a80b-4f0fc7b2d269'::uuid, 'oita-prefectural-art-museum', 'museum', true, 1.000, 'https://shigerubanarchitects.com/works/oita-prefectural-art-museum/', 'Shigeru Ban Architects records the completed 2014 museum in Oita and describes its cedar-braced facade and flexible atrium.', '2026-07-12T00:00:00Z'::timestamptz),
  ('abb72157-0dbf-549c-a378-3fe8ae013bd9'::uuid, 'kyoto-city-kyocera-museum-of-art', 'museum', true, 1.000, 'https://kyotocity-kyocera.museum/en/architecture', 'The museum identifies Jun Aoki and Tezzo Nishizawa as master designers of the renewal and records the March 2020 reopening.', '2026-07-12T00:00:00Z'::timestamptz),
  ('bf88b372-42b0-532f-87bb-33077fa0b6da'::uuid, 'nagasaki-prefectural-art-museum', 'museum', true, 1.000, 'https://kkaa.co.jp/en/project/nagasaki-prefectural-art-museum/', 'KKAA records February 2005 completion in Nagasaki and describes the museum''s two canal-linked sites.', '2026-07-12T00:00:00Z'::timestamptz),
  ('22d7c427-87f9-5884-84f0-f6c88fc65bde'::uuid, 'sagawa-art-museum', 'museum', true, 1.000, 'https://www.sagawa-artmuseum.or.jp/en/', 'Sagawa Art Museum records its March 22, 1998 opening in Moriyama, Shiga. The Japan Institute of Architects identifies Takenaka Corporation as designer of the main building and administration wing.', '2026-07-12T00:00:00Z'::timestamptz),
  ('f0416e50-a744-5391-b680-5948f6636ae8'::uuid, 'fukuda-art-museum', 'museum', true, 1.000, 'https://fukuda-art-museum.jp/en/concept', 'The museum records its October 2019 opening in Saga-Arashiyama and describes the building design. Yasuda Atelier identifies itself as architect and supervisor of the Fukuda Art Museum.', '2026-07-12T00:00:00Z'::timestamptz),
  ('65cca6df-9211-5abc-8979-b0d618b42207'::uuid, 'kunsthaus-graz', 'museum', true, 1.000, 'https://www.museum-joanneum.at/en/kunsthaus-graz/discover/architecture', 'The museum''s architecture documentation identifies Peter Cook and Colin Fournier as designers and records completion and opening in September 2003.', '2026-07-12T00:00:00Z'::timestamptz),
  ('4a276826-cf33-57ac-80ea-ea7ea805f0ad'::uuid, 'maxxi-museum-of-xxi-century-arts', 'museum', true, 1.000, 'https://www.zha.com/projects/architecture/maxxi-museum-of-xxi-century-arts', 'The current ZHA project page records MAXXI in Rome, Italy, with the project period 1998–2009.', '2026-07-12T00:00:00Z'::timestamptz),
  ('436fc652-fae5-57e5-8907-47f2b496cc73'::uuid, 'moesgaard-museum', 'museum', true, 1.000, 'https://www.henninglarsen.com/projects/moesgaard', 'Henning Larsen records the completed 2009–2014 museum project in Aarhus and its publicly accessible sloping roof.', '2026-07-12T00:00:00Z'::timestamptz),
  ('37417806-10db-5418-a401-cfddbee92dff'::uuid, 'zeitz-mocaa', 'museum', true, 1.000, 'https://heatherwick.com/projects/buildings/zeitz-mocaa/', 'Heatherwick Studio records the completed 2017 grain-silo conversion in Cape Town and the museum''s September 2017 opening.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 12
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 9
    OR (SELECT count(*) FROM building_seed) <> 14
    OR (SELECT count(*) FROM image_seed) <> 14
    OR (SELECT count(*) FROM profile_seed) <> 14
    OR (SELECT count(*) FROM assignment_seed) <> 16 THEN
    RAISE EXCEPTION 'Graduation museum batch 001 seed count mismatch';
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 3 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['museum', 'library', 'mixed-use']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['cultural']::text[]);
  IF required_function_matches <> 3
    OR required_type_matches <> 1 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id OR target.building_id = seed.building_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation museum batch 001 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 9
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 14
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 14
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 14
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 16
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 14
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 14 THEN
    RAISE EXCEPTION 'Graduation museum batch 001 post-write verification failed';
  END IF;
END $$;

COMMIT;
