-- Graduation unification batch 001: reviewed schema seed data.
-- Generated by scripts/prepare-graduation-unification-batch-001.mjs.
-- Prerequisite: reviewed graduation-unification foundation schema.
-- Scope: 21 profiles, 9 functions,
-- 122 aliases, 23 approved assignments.
-- This operation does not update or delete canonical buildings or images.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_aliases') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL THEN
    RAISE EXCEPTION 'Graduation unification schema prerequisite is missing';
  END IF;
END $$;

CREATE TEMP TABLE graduation_profile_seed (
  case_id text PRIMARY KEY,
  building_id uuid NOT NULL UNIQUE,
  building_slug text NOT NULL UNIQUE,
  concept_zh text NOT NULL,
  concept_zh_hant text,
  concept_en text,
  concept_ja text,
  keywords_zh text[] NOT NULL,
  keywords_zh_hant text[] NOT NULL,
  keywords_en text[] NOT NULL,
  keywords_ja text[] NOT NULL,
  plan_url text,
  section_url text,
  source_url text NOT NULL,
  publication_status text NOT NULL
) ON COMMIT DROP;

INSERT INTO graduation_profile_seed VALUES
  (
    'CASE-007', '582e9988-dfa5-4b9e-8498-b7a82b827c28'::uuid, 'sendai-mediatheque',
    '以开放楼板和管状结构承载图书馆、展览与市民活动的多层公共性。', NULL, 'Sendai Mediatheque is a reference case for reading library, Design topic: 媒体, publicness, learning. It can inform thesis thinking about mixed programs, operation, and place-making.', '図書館、ギャラリー、メディア機能を一つの公共建築に重ねた事例。用途を固定せず、市民が多様に使える空間構成を比較できる。',
    ARRAY['图书馆', '媒体', '公共性', '学习', '第三空间']::text[], '{}'::text[], ARRAY['library', 'Design topic: 媒体', 'publicness', 'learning', 'third place']::text[], ARRAY['図書館', 'メディア', '公共性', '学習', '第三空間']::text[],
    NULL, NULL, 'https://www.smt.jp/', 'published'
  ),
  (
    'CASE-046', 'fe4d501b-0cdb-4e50-94b8-d4e87af41cc0'::uuid, 'naoshima-chichu-art-museum',
    '大部分埋入地下的美术馆以自然光和几何庭院回应自然景观与艺术体验。', NULL, 'Chichu Art Museum is a reference case for reading art museum, Design topic: 地下, Design topic: nature光, Design topic: 离岛. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Chichu Art Museum」は、美術館・地下・自然光・離島の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。',
    ARRAY['美术馆', '地下', '自然光', '离岛', '景观']::text[], '{}'::text[], ARRAY['art museum', 'Design topic: 地下', 'Design topic: nature光', 'Design topic: 离岛', 'Design topic: 景观']::text[], ARRAY['美術館', '地下', '自然光', '離島', '景観']::text[],
    NULL, NULL, 'https://benesse-artsite.jp/en/art/chichu.html', 'published'
  ),
  (
    'CASE-099', '7ae9d279-1d5c-4c28-801e-2ae38f6552b7'::uuid, 'tate-modern',
    '旧发电站转为当代美术馆，以涡轮大厅和新展览空间展示产业遗产再利用的公共力量。', NULL, 'Tate Modern is a reference case for reading industrial heritage, art museum, Design topic: 发电站regeneration, Design topic: public大厅. It can inform thesis thinking about mixed programs, operation, and place-making.', '旧発電所を美術館へ転用した事例。産業遺産を壊さず、巨大な内部空間を都市の文化拠点へ変える方法を比較できる。',
    ARRAY['产业遗产', '美术馆', '发电站再生', '公共大厅', '文化设施']::text[], '{}'::text[], ARRAY['industrial heritage', 'art museum', 'Design topic: 发电站regeneration', 'Design topic: public大厅', 'culturefacility']::text[], ARRAY['産業遺産', '美術館', '再利用', '公共空間', '都市文化']::text[],
    NULL, NULL, 'https://www.herzogdemeuron.com/projects/126-tate-modern/', 'published'
  ),
  (
    'CASE-103', 'c18e2e30-a728-49f5-ad19-503ead0ce1e0'::uuid, 'kanazawa-museum',
    '圆形平面把美术馆变成可从多方向进入的城市公共场。', NULL, 'A circular museum that opens to the city from multiple directions and works like a civic field.', '円形平面と複数の入口により、美術館を街に開いた公共広場のように扱う事例。市民利用と展示の境界を読める。',
    ARRAY['美术馆', '市民广场', '公共性', '多入口', '地域文化']::text[], '{}'::text[], ARRAY['museum', 'civic plaza', 'publicness', 'multiple entrances', 'regional culture']::text[], ARRAY['美術館', '市民広場', '公共性', '複数入口', '地域文化']::text[],
    NULL, NULL, 'https://www.kanazawa21.jp/', 'published'
  ),
  (
    'CASE-106', 'a1ca0778-8b46-4400-9b96-56996578c705'::uuid, 'rolex-learning-center',
    '连续地景式楼板把学习、交流、休息和校园动线连接起来。', NULL, 'A continuous landscape-like floor linking learning, encounter, rest, and campus circulation.', '起伏する一枚の床で、学習、交流、休憩、キャンパス動線を連続させた事例。境界の少ない学習空間を考える参考になる。',
    ARRAY['学习中心', '校园', '连续地景', '交流', '开放学习']::text[], '{}'::text[], ARRAY['learning center', 'campus', 'continuous landscape', 'exchange', 'open learning']::text[], ARRAY['学習センター', 'キャンパス', '連続地形', '交流', '開放学習']::text[],
    NULL, NULL, 'https://www.archdaily.com/53536/rolex-learning-center-sanaa-by-iwan-baan', 'published'
  ),
  (
    'CASE-119', '8cc3634e-9443-4c07-951c-f3c76ff20ecf'::uuid, 'louvre-lens',
    '低く水平に広がる美術館を公園と接続し、地域再生の文化拠点にした事例。柔らかい公共性を読める。', NULL, 'Reference case for Louvre-Lens: useful for comparing public program, urban interface, operation, and spatial experience.', '低く水平に広がる美術館を公園と接続し、地域再生の文化拠点にした事例。柔らかい公共性を読める。',
    ARRAY['美術館', '公園', '地域再生', '低層', '公共性']::text[], '{}'::text[], ARRAY['美術館', '公園', '地域再生', '低層', '公共性']::text[], ARRAY['美術館', '公園', '地域再生', '低層', '公共性']::text[],
    NULL, NULL, 'https://www.louvre.fr/en/explore/the-palace/the-louvre-lens', 'published'
  ),
  (
    'CASE-123', 'f110abb5-d8ff-456c-a268-99a9fa403554'::uuid, 'aga-khan-museum',
    '庭園、水盤、美術館を通じてイスラム文化を公共教育へ開く事例。多文化と静かな学習空間を考えられる。', NULL, 'Reference case for Aga Khan Museum: useful for comparing public program, urban interface, operation, and spatial experience.', '庭園、水盤、美術館を通じてイスラム文化を公共教育へ開く事例。多文化と静かな学習空間を考えられる。',
    ARRAY['美術館', '多文化', '庭園', '水盤', '公共教育']::text[], '{}'::text[], ARRAY['美術館', '多文化', '庭園', '水盤', '公共教育']::text[], ARRAY['美術館', '多文化', '庭園', '水盤', '公共教育']::text[],
    NULL, NULL, 'https://www.moriyama-teshima.com/projects/aga-khan-museum/', 'published'
  ),
  (
    'CASE-125', 'd80be7f7-a8ab-46c3-97ee-a5c7fce26b21'::uuid, 'vitra-haus',
    '住宅の原型を積み重ねた展示施設。家具、住まい、ブランド体験、回遊を結びつける参考になる。', NULL, 'Reference case for VitraHaus: useful for comparing public program, urban interface, operation, and spatial experience.', '住宅の原型を積み重ねた展示施設。家具、住まい、ブランド体験、回遊を結びつける参考になる。',
    ARRAY['展示施設', '住宅原型', 'ブランド体験', '回遊', '文化観光']::text[], '{}'::text[], ARRAY['展示施設', '住宅原型', 'ブランド体験', '回遊', '文化観光']::text[], ARRAY['展示施設', '住宅原型', 'ブランド体験', '回遊', '文化観光']::text[],
    NULL, NULL, 'https://www.herzogdemeuron.com/projects/246-vitrahaus/', 'published'
  ),
  (
    'CASE-138', '7e7252fd-c528-435a-93e7-db2c7db85d82'::uuid, 'copenhill',
    '清掃工場をスキー場、クライミング、展望の公共施設へ重ねた事例。環境インフラを都市活動に変える参考になる。', NULL, 'Reference case for CopenHill: useful for comparing public program, urban interface, operation, and spatial experience.', '清掃工場をスキー場、クライミング、展望の公共施設へ重ねた事例。環境インフラを都市活動に変える参考になる。',
    ARRAY['環境インフラ', '清掃工場', 'スポーツ', '展望', '都市活動']::text[], '{}'::text[], ARRAY['環境インフラ', '清掃工場', 'スポーツ', '展望', '都市活動']::text[], ARRAY['環境インフラ', '清掃工場', 'スポーツ', '展望', '都市活動']::text[],
    NULL, NULL, 'https://big.dk/projects/copenhill-191', 'published'
  ),
  (
    'CASE-128', 'b1b8cb5d-1ad2-44e0-a791-e5d56fb20edd'::uuid, 'sesc-pompeia',
    '旧工場をスポーツ、劇場、食堂、滞在の文化センターへ転用した事例。日常の公共性と再利用を学べる。', NULL, 'Reference case for SESC Pompeia: useful for comparing public program, urban interface, operation, and spatial experience.', '旧工場をスポーツ、劇場、食堂、滞在の文化センターへ転用した事例。日常の公共性と再利用を学べる。',
    ARRAY['工場再生', '文化センター', 'スポーツ', '食堂', '日常公共性']::text[], '{}'::text[], ARRAY['工場再生', '文化センター', 'スポーツ', '食堂', '日常公共性']::text[], ARRAY['工場再生', '文化センター', 'スポーツ', '食堂', '日常公共性']::text[],
    NULL, NULL, 'https://arquitecturaviva.com/works/sesc-pompeia-factory', 'published'
  ),
  (
    'CASE-061', '49a21106-36cc-46ad-a50b-eae2ee7e5668'::uuid, 'national-stadium-tokyo',
    '大型体育场以层叠木质檐口和公园化边界回应国家赛事设施的日常化问题。', NULL, 'Japan National Stadium is a reference case for reading Design topic: 体育场, Design topic: 赛事heritage, Design topic: 木材, park. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Japan National Stadium」は、スポーツ場・イベント遺産・木材・公園の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。',
    ARRAY['体育场', '赛事遗产', '木材', '公园', '城市开放空间']::text[], '{}'::text[], ARRAY['Design topic: 体育场', 'Design topic: 赛事heritage', 'Design topic: 木材', 'park', 'urbanopenspace']::text[], ARRAY['スポーツ場', 'イベント遺産', '木材', '公園', '都市開放空間']::text[],
    NULL, NULL, 'https://kkaa.co.jp/en/project/japan-national-stadium/', 'published'
  ),
  (
    'CASE-104', '444deee7-5b62-43aa-8b2c-dbc46648e083'::uuid, 'seattle-central-library',
    '把图书馆程序堆叠成透明的城市知识基础设施。', NULL, 'A transparent civic knowledge infrastructure formed by stacking library programs.', '図書館の機能を積層し、透明な都市インフラとして表現した事例。情報、閲覧、移動、公共性の関係を比較できる。',
    ARRAY['图书馆', '知识基础设施', '透明', '城市中心', '学习']::text[], '{}'::text[], ARRAY['library', 'knowledge infrastructure', 'transparency', 'city center', 'learning']::text[], ARRAY['図書館', '知識インフラ', '透明性', '都心', '学習']::text[],
    NULL, NULL, 'https://www.oma.com/projects/seattle-central-library', 'published'
  ),
  (
    'CASE-108', '7ac209df-dd1c-4600-ac2b-b6f013a9bbff'::uuid, 'pompidou-metz',
    '大屋根下に展示、広场和城市活动を包み込む文化拠点。', NULL, 'A museum under a large roof that receives exhibition, plaza, events, and urban movement.', '大きな屋根の下に展示、広場、イベント、都市の通り抜けを受け止める美術館。文化施設と都市活動の重ね方を読める。',
    ARRAY['美术馆', '大屋根', '市民广场', '展示', '文化活动']::text[], '{}'::text[], ARRAY['museum', 'large roof', 'civic plaza', 'exhibition', 'cultural activity']::text[], ARRAY['美術館', '大屋根', '市民広場', '展示', '文化活動']::text[],
    NULL, NULL, 'https://shigerubanarchitects.com/works/cultural/centre-pompidou-metz/', 'published'
  ),
  (
    'CASE-120', '1af2ea73-49d7-4e47-9146-cae45adaddeb'::uuid, 'guangzhou-opera-house',
    '劇場と都市広場を強い造形で結び、水辺の文化ランドマークをつくった事例。大規模文化施設の入口を比較できる。', NULL, 'Reference case for Guangzhou Opera House: useful for comparing public program, urban interface, operation, and spatial experience.', '劇場と都市広場を強い造形で結び、水辺の文化ランドマークをつくった事例。大規模文化施設の入口を比較できる。',
    ARRAY['劇場', '文化拠点', '水辺', '都市広場', 'ランドマーク']::text[], '{}'::text[], ARRAY['劇場', '文化拠点', '水辺', '都市広場', 'ランドマーク']::text[], ARRAY['劇場', '文化拠点', '水辺', '都市広場', 'ランドマーク']::text[],
    NULL, NULL, 'https://www.zaha-hadid.com/architecture/guangzhou-opera-house/', 'published'
  ),
  (
    'CASE-127', 'e212bd81-0c29-417a-ab24-db4a93661b19'::uuid, 'cctv-headquarters',
    '巨大なループ状の高層建築で制作、管理、都市景観を接続した事例。大規模複合施設の構成を比較できる。', NULL, 'Reference case for CCTV Headquarters: useful for comparing public program, urban interface, operation, and spatial experience.', '巨大なループ状の高層建築で制作、管理、都市景観を接続した事例。大規模複合施設の構成を比較できる。',
    ARRAY['大規模複合', 'メディア', '高層', '都市景観', '構造']::text[], '{}'::text[], ARRAY['大規模複合', 'メディア', '高層', '都市景観', '構造']::text[], ARRAY['大規模複合', 'メディア', '高層', '都市景観', '構造']::text[],
    NULL, NULL, 'https://www.oma.com/projects/cctv-headquarters', 'published'
  ),
  (
    'CASE-129', '6c32f1bb-fdd4-40b4-8380-256f039b231a'::uuid, 'centre-pompidou',
    '展示、図書館、広場、都市イベントを外部化した文化センター。巨大公共施設と街の関係を比較できる。', NULL, 'Reference case for Centre Pompidou: useful for comparing public program, urban interface, operation, and spatial experience.', '展示、図書館、広場、都市イベントを外部化した文化センター。巨大公共施設と街の関係を比較できる。',
    ARRAY['文化センター', '図書館', '市民広場', '展示', '都市イベント']::text[], '{}'::text[], ARRAY['文化センター', '図書館', '市民広場', '展示', '都市イベント']::text[], ARRAY['文化センター', '図書館', '市民広場', '展示', '都市イベント']::text[],
    NULL, NULL, 'https://www.centrepompidou.fr/en/', 'published'
  ),
  (
    'CASE-131', 'b06ab0b3-b06d-4965-b14d-dff4b53a6110'::uuid, 'casa-da-musica',
    '音楽ホールを都市の中の不定形な公共物として配置した事例。ホール、広場、街の接点を読める。', NULL, 'Reference case for Casa da Música: useful for comparing public program, urban interface, operation, and spatial experience.', '音楽ホールを都市の中の不定形な公共物として配置した事例。ホール、広場、街の接点を読める。',
    ARRAY['音楽ホール', '都市広場', '文化拠点', '公共入口', '上演']::text[], '{}'::text[], ARRAY['音楽ホール', '都市広場', '文化拠点', '公共入口', '上演']::text[], ARRAY['音楽ホール', '都市広場', '文化拠点', '公共入口', '上演']::text[],
    NULL, NULL, 'https://www.oma.com/projects/casa-da-musica', 'published'
  ),
  (
    'CASE-135', '750ce23f-0a58-47eb-a898-762fe3c0cd0e'::uuid, 'kunsthal',
    '複数の動線を交差させ、展示と公園、道路、入口を接続した美術館。都市の流れと展示施設の関係を読める。', NULL, 'Reference case for Kunsthal Rotterdam: useful for comparing public program, urban interface, operation, and spatial experience.', '複数の動線を交差させ、展示と公園、道路、入口を接続した美術館。都市の流れと展示施設の関係を読める。',
    ARRAY['美術館', '動線', '公園', '都市接続', '展示']::text[], '{}'::text[], ARRAY['美術館', '動線', '公園', '都市接続', '展示']::text[], ARRAY['美術館', '動線', '公園', '都市接続', '展示']::text[],
    NULL, NULL, 'https://www.oma.com/projects/kunsthal', 'published'
  ),
  (
    'CASE-102', 'e8a453f5-8c49-456c-a4c8-d72217357571'::uuid, 'kiasma',
    '以柔和动线和自然光组织当代艺术、美术馆入口和城市界面。', NULL, 'A contemporary art museum organized through light, curved movement, and a strong urban threshold.', '自然光と曲線的な動線で展示室、入口、都市との接点をつなぐ美術館。静けさと公共性の両方を読む参考になる。',
    ARRAY['美术馆', '自然光', '城市界面', '展览', '静谧']::text[], '{}'::text[], ARRAY['museum', 'natural light', 'urban interface', 'exhibition', 'quietness']::text[], ARRAY['美術館', '自然光', '都市界面', '展示', '静けさ']::text[],
    NULL, NULL, 'https://www.stevenholl.com/project/kiasma-museum/', 'published'
  ),
  (
    'CASE-107', 'e611522f-a42e-4915-b518-653bad66b8b3'::uuid, 'taichung-metropolitan-opera',
    '表演厅、公共大厅和连续曲面空间共同构成城市文化地标。', NULL, 'A performing arts complex where theaters, public foyers, and curved spatial continuity form a civic landmark.', '劇場、公共ロビー、連続する曲面空間が都市の文化拠点をつくる事例。鑑賞前後の滞在や市民利用を考えられる。',
    ARRAY['剧场', '文化地标', '公共大厅', '表演', '城市活动']::text[], '{}'::text[], ARRAY['theater', 'cultural landmark', 'public foyer', 'performance', 'urban activity']::text[], ARRAY['劇場', '文化拠点', '公共ロビー', '上演', '都市活動']::text[],
    NULL, NULL, 'https://www.toyo-ito.co.jp/WWW/Project_Descript/2016-/2016-p_01/2016-p_01_en.html', 'published'
  ),
  (
    'CASE-121', '4d89cb59-b2c1-40fe-89e8-35216f340a08'::uuid, 'hamburg-elbphilharmonie',
    '港の倉庫の上にコンサートホールを重ね、都市の水辺と観光、文化を接続した事例。産業遺産更新の参考になる。', NULL, 'Reference case for Elbphilharmonie: useful for comparing public program, urban interface, operation, and spatial experience.', '港の倉庫の上にコンサートホールを重ね、都市の水辺と観光、文化を接続した事例。産業遺産更新の参考になる。',
    ARRAY['音楽ホール', '倉庫再生', '港', '文化観光', '都市景観']::text[], '{}'::text[], ARRAY['音楽ホール', '倉庫再生', '港', '文化観光', '都市景観']::text[], ARRAY['音楽ホール', '倉庫再生', '港', '文化観光', '都市景観']::text[],
    NULL, NULL, 'https://www.herzogdemeuron.com/projects/230-elbphilharmonie-hamburg/', 'published'
  );

CREATE TEMP TABLE building_function_seed (
  slug text PRIMARY KEY,
  broad_type_slug text,
  name_zh text NOT NULL,
  name_zh_hant text NOT NULL,
  name_en text NOT NULL,
  name_ja text NOT NULL
) ON COMMIT DROP;

INSERT INTO building_function_seed VALUES
  (
    'library', 'cultural',
    '图书馆', '圖書館', 'Library', '図書館'
  ),
  (
    'museum', 'cultural',
    '博物馆／美术馆', '博物館／美術館', 'Museum', '博物館・美術館'
  ),
  (
    'theatre', 'cultural',
    '剧院／剧场', '劇院／劇場', 'Theatre', '劇場'
  ),
  (
    'school', 'educational',
    '学校', '學校', 'School', '学校'
  ),
  (
    'university', 'educational',
    '大学', '大學', 'University', '大学'
  ),
  (
    'community-center', 'civic-public',
    '社区中心', '社區中心', 'Community Center', 'コミュニティセンター'
  ),
  (
    'elderly-care', 'healthcare',
    '养老与高龄照护', '養老與高齡照護', 'Elderly Care', '高齢者ケア'
  ),
  (
    'social-housing', 'residential',
    '社会住宅', '社會住宅', 'Social Housing', '公営・社会住宅'
  ),
  (
    'mixed-use', 'mixed-use',
    '混合用途', '混合用途', 'Mixed Use', '複合用途'
  );

CREATE TEMP TABLE building_function_alias_seed (
  function_slug text NOT NULL,
  locale text NOT NULL,
  alias text NOT NULL,
  PRIMARY KEY (locale, alias)
) ON COMMIT DROP;

INSERT INTO building_function_alias_seed VALUES
  ('library', 'zh', '图书馆'),
  ('library', 'zh', '图书室'),
  ('library', 'zh-Hant', '圖書館'),
  ('library', 'zh-Hant', '圖書室'),
  ('library', 'en', 'library'),
  ('library', 'en', 'libraries'),
  ('library', 'en', 'biblioteca'),
  ('library', 'en', 'bibliothèque'),
  ('library', 'en', 'bibliothek'),
  ('library', 'ja', '図書館'),
  ('library', 'ja', '図書室'),
  ('museum', 'zh', '博物馆'),
  ('museum', 'zh', '美术馆'),
  ('museum', 'zh-Hant', '博物館'),
  ('museum', 'zh-Hant', '美術館'),
  ('museum', 'en', 'museum'),
  ('museum', 'en', 'art museum'),
  ('museum', 'en', 'kunsthaus'),
  ('museum', 'en', 'kunsthalle'),
  ('museum', 'ja', '博物館'),
  ('museum', 'ja', '美術館'),
  ('museum', 'ja', 'ミュージアム'),
  ('theatre', 'zh', '剧院'),
  ('theatre', 'zh', '剧场'),
  ('theatre', 'zh', '歌剧院'),
  ('theatre', 'zh-Hant', '劇院'),
  ('theatre', 'zh-Hant', '劇場'),
  ('theatre', 'zh-Hant', '歌劇院'),
  ('theatre', 'en', 'theatre'),
  ('theatre', 'en', 'theater'),
  ('theatre', 'en', 'opera house'),
  ('theatre', 'en', 'playhouse'),
  ('theatre', 'ja', '劇場'),
  ('theatre', 'ja', '歌劇場'),
  ('theatre', 'ja', 'シアター'),
  ('school', 'zh', '学校'),
  ('school', 'zh', '小学'),
  ('school', 'zh', '中学'),
  ('school', 'zh', '幼儿园'),
  ('school', 'zh-Hant', '學校'),
  ('school', 'zh-Hant', '小學'),
  ('school', 'zh-Hant', '中學'),
  ('school', 'zh-Hant', '幼兒園'),
  ('school', 'en', 'school'),
  ('school', 'en', 'primary school'),
  ('school', 'en', 'secondary school'),
  ('school', 'en', 'kindergarten'),
  ('school', 'ja', '学校'),
  ('school', 'ja', '小学校'),
  ('school', 'ja', '中学校'),
  ('school', 'ja', '幼稚園'),
  ('university', 'zh', '大学'),
  ('university', 'zh', '学院'),
  ('university', 'zh-Hant', '大學'),
  ('university', 'zh-Hant', '學院'),
  ('university', 'en', 'university'),
  ('university', 'en', 'college'),
  ('university', 'en', 'faculty building'),
  ('university', 'en', 'campus'),
  ('university', 'ja', '大学'),
  ('university', 'ja', '大学院'),
  ('university', 'ja', '学部棟'),
  ('university', 'ja', 'キャンパス'),
  ('community-center', 'zh', '社区中心'),
  ('community-center', 'zh', '社区活动中心'),
  ('community-center', 'zh', '市民中心'),
  ('community-center', 'zh-Hant', '社區中心'),
  ('community-center', 'zh-Hant', '社區活動中心'),
  ('community-center', 'zh-Hant', '市民中心'),
  ('community-center', 'en', 'community center'),
  ('community-center', 'en', 'community centre'),
  ('community-center', 'en', 'civic center'),
  ('community-center', 'en', 'civic centre'),
  ('community-center', 'ja', 'コミュニティセンター'),
  ('community-center', 'ja', '地域センター'),
  ('community-center', 'ja', '市民センター'),
  ('community-center', 'ja', '公民館'),
  ('elderly-care', 'zh', '养老院'),
  ('elderly-care', 'zh', '养老设施'),
  ('elderly-care', 'zh', '老年照护'),
  ('elderly-care', 'zh', '高龄者设施'),
  ('elderly-care', 'zh-Hant', '養老院'),
  ('elderly-care', 'zh-Hant', '養老設施'),
  ('elderly-care', 'zh-Hant', '老年照護'),
  ('elderly-care', 'zh-Hant', '高齡者設施'),
  ('elderly-care', 'en', 'elderly care'),
  ('elderly-care', 'en', 'senior care'),
  ('elderly-care', 'en', 'nursing home'),
  ('elderly-care', 'en', 'assisted living'),
  ('elderly-care', 'ja', '高齢者施設'),
  ('elderly-care', 'ja', '老人ホーム'),
  ('elderly-care', 'ja', '介護施設'),
  ('elderly-care', 'ja', '高齢者ケア'),
  ('social-housing', 'zh', '社会住宅'),
  ('social-housing', 'zh', '公共住宅'),
  ('social-housing', 'zh', '保障性住房'),
  ('social-housing', 'zh', '廉租房'),
  ('social-housing', 'zh-Hant', '社會住宅'),
  ('social-housing', 'zh-Hant', '公共住宅'),
  ('social-housing', 'zh-Hant', '保障性住房'),
  ('social-housing', 'zh-Hant', '廉租屋'),
  ('social-housing', 'en', 'social housing'),
  ('social-housing', 'en', 'public housing'),
  ('social-housing', 'en', 'affordable housing'),
  ('social-housing', 'en', 'council housing'),
  ('social-housing', 'ja', '社会住宅'),
  ('social-housing', 'ja', '公営住宅'),
  ('social-housing', 'ja', '公共住宅'),
  ('social-housing', 'ja', '低所得者住宅'),
  ('mixed-use', 'zh', '混合用途'),
  ('mixed-use', 'zh', '综合体'),
  ('mixed-use', 'zh', '复合设施'),
  ('mixed-use', 'zh-Hant', '混合用途'),
  ('mixed-use', 'zh-Hant', '綜合體'),
  ('mixed-use', 'zh-Hant', '複合設施'),
  ('mixed-use', 'en', 'mixed use'),
  ('mixed-use', 'en', 'mixed-use'),
  ('mixed-use', 'en', 'multi-use complex'),
  ('mixed-use', 'en', 'multipurpose complex'),
  ('mixed-use', 'ja', '複合用途'),
  ('mixed-use', 'ja', '複合施設'),
  ('mixed-use', 'ja', 'ミクストユース');

CREATE TEMP TABLE building_function_assignment_seed (
  building_id uuid NOT NULL,
  building_slug text NOT NULL,
  function_slug text NOT NULL,
  confidence numeric(4,3) NOT NULL,
  evidence_url text NOT NULL,
  evidence_note text NOT NULL,
  reviewed_at timestamptz NOT NULL,
  PRIMARY KEY (building_id, function_slug)
) ON COMMIT DROP;

INSERT INTO building_function_assignment_seed VALUES
  (
    '45e768be-5423-4315-b982-c14ff6dcacda'::uuid, 'atlanta-fulton-county-central-library', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q105751960', 'Atlanta Fulton County Central Library is classified as a library building in the United States.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    'd57bbedb-6ed6-49ec-aa9b-2698c4f50cf7'::uuid, 'beinecke-rare-book-manuscript-library', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q814779', 'Beinecke Rare Book & Manuscript Library is classified as an academic, rare-book and library building.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    'faa20fe8-e4be-4dde-a9b9-137c89c6e4cd'::uuid, 'biblioteca-comunale-centrale-antonio-tiraboschi', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q3639566', 'Biblioteca Antonio Tiraboschi is classified as a public library and a library of an Italian territorial body.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '2f9e5b43-f509-4b50-aa6c-34ab79e0659d'::uuid, 'biblioteca-municipal-de-viana-do', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q17318051', 'Biblioteca Municipal de Viana do Castelo is classified as a library, public library, municipal library and library building.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    'b60c6ff1-0ddc-4c17-9aec-cf4cac8cd386'::uuid, 'c-v-starr-east-asian', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q118903541', 'C. V. Starr East Asian Library is classified as a library building in the United States.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '0a272df1-7d88-445a-8fa3-b084e937ce51'::uuid, 'central-library-des-moines', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q66042452', 'Central Library, Des Moines is classified as a library building in the United States.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '0e48c41e-53ae-41dd-bc7d-f6d508afe942'::uuid, 'dortmund-city-and-state-library', 'library',
    1.000, 'https://www.dortmund.de/themen/bildung/stadt-und-landesbibliothek/', 'The City of Dortmund operates this building as the Stadt- und Landesbibliothek.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '8bd1a441-71ca-4bcf-90df-f6d97eaee9b1'::uuid, 'grosse-pointe-public-library-central', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q106900422', 'Grosse Pointe Public Library Central Branch is classified as a library building in the United States.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    'c7547211-daeb-477e-912c-6dab71109027'::uuid, 'hill-museum-manuscript-library', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q5762205', 'Hill Museum & Manuscript Library is explicitly classified as both a library and a museum.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    'c7547211-daeb-477e-912c-6dab71109027'::uuid, 'hill-museum-manuscript-library', 'museum',
    1.000, 'https://www.wikidata.org/wiki/Q5762205', 'Hill Museum & Manuscript Library is explicitly classified as both a library and a museum.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '2efb1ed3-23c9-47ab-b088-6932da4f8e23'::uuid, 'laurentian-library', 'library',
    1.000, 'https://www.bmlonline.it/', 'The official Biblioteca Medicea Laurenziana site identifies and operates the Laurentian Library.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '63c9fd31-6ac6-49e0-b5e8-58a2eac5bbec'::uuid, 'library-of-the-university-of', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q3755932', 'The University of Deusto building is classified as an academic and main library.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '8e52c196-ae39-4bb0-9cca-2fedc1140d70'::uuid, 'lyndon-baines-johnson-library-and', 'library',
    1.000, 'https://www.lbjlibrary.org/', 'The official LBJ Presidential Library site describes a research library and public museum in Austin, Texas.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '8e52c196-ae39-4bb0-9cca-2fedc1140d70'::uuid, 'lyndon-baines-johnson-library-and', 'museum',
    1.000, 'https://www.lbjlibrary.org/', 'The official LBJ Presidential Library site describes a research library and public museum in Austin, Texas.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '5a412752-58bc-4fdd-9677-446e7b1375ae'::uuid, 'musashino-art-museum', 'library',
    1.000, 'https://mauml.musabi.ac.jp/en/', 'Musashino Art University''s official Museum & Library site operates both museum and library facilities.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '5a412752-58bc-4fdd-9677-446e7b1375ae'::uuid, 'musashino-art-museum', 'museum',
    1.000, 'https://mauml.musabi.ac.jp/en/', 'Musashino Art University''s official Museum & Library site operates both museum and library facilities.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '6253770b-bc9d-44b5-81c2-f7a97430c78f'::uuid, 'new-york-public-library-for', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q7013890', 'New York Public Library for the Performing Arts is classified as a public, research and branch library.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '505d64e1-35f7-4419-9f10-36c40af6607b'::uuid, 'niagara-falls-public-library', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q65068973', 'Niagara Falls Public Library is classified as a main library in the United States.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    'a52fc3e3-78a4-4be7-851b-163997e379b2'::uuid, 'r-dovre-library', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q21098720', 'Rødovre Library is classified as a municipal library in Denmark.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    'b3c550f7-67b9-4516-bd47-b6941cd46995'::uuid, 'rovaniemi-city-library', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q10547804', 'Rovaniemi City Library is classified as a library and municipal library in Finland.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '557b9c4c-8f0a-49bf-b489-b836aadbbd87'::uuid, 'schocken-library', 'library',
    1.000, 'https://www.wikidata.org/wiki/Q6756158', 'Schocken Library is classified as an academic and reference library in Israel.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '444deee7-5b62-43aa-8b2c-dbc46648e083'::uuid, 'seattle-central-library', 'library',
    1.000, 'https://www.spl.org/hours-and-locations/central-library', 'The Seattle Public Library''s official page identifies the Central Library and its library collections and services.', '2026-07-12T00:00:00Z'::timestamptz
  ),
  (
    '0ed33a5f-0285-419d-87a2-a8a7e313fd8e'::uuid, 'vyborg-library', 'library',
    1.000, 'https://www.alvaraalto.fi/en/architecture/alvar-aalto-library/', 'The Alvar Aalto Foundation documents the Vyborg Central Library and its completion in 1935.', '2026-07-12T00:00:00Z'::timestamptz
  );

DO $$
DECLARE
  profile_seed_count integer;
  function_seed_count integer;
  alias_seed_count integer;
  assignment_seed_count integer;
  matched_profile_buildings integer;
  matched_assignment_rows integer;
  known_broad_types integer;
  existing_conflicts integer;
BEGIN
  SELECT count(*) INTO profile_seed_count FROM graduation_profile_seed;
  SELECT count(*) INTO function_seed_count FROM building_function_seed;
  SELECT count(*) INTO alias_seed_count FROM building_function_alias_seed;
  SELECT count(*) INTO assignment_seed_count FROM building_function_assignment_seed;

  IF profile_seed_count <> 21
    OR function_seed_count <> 9
    OR alias_seed_count <> 122
    OR assignment_seed_count <> 23 THEN
    RAISE EXCEPTION 'Seed count mismatch: profiles %, functions %, aliases %, assignments %',
      profile_seed_count, function_seed_count, alias_seed_count, assignment_seed_count;
  END IF;

  SELECT count(*) INTO matched_profile_buildings
  FROM graduation_profile_seed seed
  JOIN public.buildings building
    ON building.id = seed.building_id AND building.slug = seed.building_slug;

  SELECT count(*) INTO matched_assignment_rows
  FROM building_function_assignment_seed seed
  JOIN public.buildings building
    ON building.id = seed.building_id AND building.slug = seed.building_slug;

  SELECT count(*) INTO known_broad_types
  FROM building_function_seed seed
  JOIN public.building_types type ON type.slug = seed.broad_type_slug;

  IF matched_profile_buildings <> 21
    OR matched_assignment_rows <> 23
    OR known_broad_types <> 9 THEN
    RAISE EXCEPTION 'Canonical reference mismatch: profiles %, assignments %, broad types %',
      matched_profile_buildings, matched_assignment_rows, known_broad_types;
  END IF;

  SELECT
    (SELECT count(*) FROM public.graduation_case_profiles target JOIN graduation_profile_seed seed USING (case_id))
    + (SELECT count(*) FROM public.building_functions target JOIN building_function_seed seed USING (slug))
    + (SELECT count(*) FROM public.building_function_aliases target JOIN building_function_alias_seed seed USING (function_slug, locale, alias))
    + (SELECT count(*) FROM public.building_function_assignments target JOIN building_function_assignment_seed seed USING (building_id, function_slug))
  INTO existing_conflicts;

  IF existing_conflicts <> 0 THEN
    RAISE EXCEPTION 'Batch 001 requires an empty target for its keys; found % conflicts', existing_conflicts;
  END IF;
END $$;

INSERT INTO public.building_functions (
  slug, broad_type_slug, name_zh, name_zh_hant, name_en, name_ja
)
SELECT slug, broad_type_slug, name_zh, name_zh_hant, name_en, name_ja
FROM building_function_seed;

INSERT INTO public.building_function_aliases (function_slug, locale, alias)
SELECT function_slug, locale, alias
FROM building_function_alias_seed;

INSERT INTO public.graduation_case_profiles (
  case_id, building_id,
  concept_zh, concept_zh_hant, concept_en, concept_ja,
  keywords_zh, keywords_zh_hant, keywords_en, keywords_ja,
  plan_url, section_url, source_url, publication_status
)
SELECT
  case_id, building_id,
  concept_zh, concept_zh_hant, concept_en, concept_ja,
  keywords_zh, keywords_zh_hant, keywords_en, keywords_ja,
  plan_url, section_url, source_url, publication_status
FROM graduation_profile_seed;

INSERT INTO public.building_function_assignments (
  building_id, function_slug, is_primary, confidence, review_status,
  assignment_method, evidence_url, evidence_note, reviewed_at
)
SELECT
  building_id, function_slug, false, confidence, 'approved',
  'source-derived', evidence_url, evidence_note, reviewed_at
FROM building_function_assignment_seed;

DO $$
DECLARE
  written_profiles integer;
  written_functions integer;
  written_aliases integer;
  written_assignments integer;
BEGIN
  SELECT count(*) INTO written_profiles
  FROM public.graduation_case_profiles target JOIN graduation_profile_seed seed USING (case_id, building_id);
  SELECT count(*) INTO written_functions
  FROM public.building_functions target JOIN building_function_seed seed USING (slug);
  SELECT count(*) INTO written_aliases
  FROM public.building_function_aliases target JOIN building_function_alias_seed seed USING (function_slug, locale, alias);
  SELECT count(*) INTO written_assignments
  FROM public.building_function_assignments target JOIN building_function_assignment_seed seed USING (building_id, function_slug)
  WHERE target.review_status = 'approved';

  IF written_profiles <> 21
    OR written_functions <> 9
    OR written_aliases <> 122
    OR written_assignments <> 23 THEN
    RAISE EXCEPTION 'Post-write count mismatch: profiles %, functions %, aliases %, assignments %',
      written_profiles, written_functions, written_aliases, written_assignments;
  END IF;
END $$;

COMMIT;
