-- Graduation Shimokitazawa retail batch 001: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=shimokitazawa-retail-001).
-- Scope: 2 new architects, 2 buildings, 2 images,
-- 2 profiles, 5 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation Shimokitazawa retail batch 001 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('0d3e5341-af67-5f3e-be30-99900711ef4e'::uuid, 'tsubame-architects', 'TSUBAME ARCHITECTS', 'TSUBAME ARCHITECTS', 'ツバメアーキテクツ', 'https://tbma.jp/en/', true),
  ('9a5f58e6-c762-59c2-8d9c-cc96a6c71930'::uuid, 'taiju-yamashita-design-and-architecture', '山下泰树设计建筑事务所', 'Taiju Yamashita Design and Architecture', '山下泰樹建築デザイン事務所', 'https://tjda.com/en/', true);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('3a86512e-ffa7-59d8-942a-585622839947'::uuid, 'CASE-038', 'bonus-track-shimokitazawa', '下北泽 BONUS TRACK', 'BONUS TRACK Shimokitazawa', 'BONUS TRACK 下北沢', '0d3e5341-af67-5f3e-be30-99900711ef4e'::uuid, 'tsubame-architects', 2020, 'published', '东京', '日本', 'JP', 'commercial', 'https://tbma.jp/en/works/bonus-track/'),
  ('bbd87e2f-2345-5eb4-8284-512d9cc2a0a0'::uuid, 'CASE-039', 'mikan-shimokita', '下北泽 MIKAN SHIMOKITA', 'MIKAN SHIMOKITA', 'ミカン下北', '9a5f58e6-c762-59c2-8d9c-cc96a6c71930'::uuid, 'taiju-yamashita-design-and-architecture', 2022, 'published', '东京', '日本', 'JP', 'commercial', 'https://tjda.com/en/projects/mikan-shimokita/');

CREATE TEMP TABLE reused_building_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE) ON COMMIT DROP;


CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('d6f955db-b759-5a79-b866-d729ca96d29c'::uuid, '3a86512e-ffa7-59d8-942a-585622839947'::uuid, 'bonus-track-shimokitazawa', 'CASE-038', '/images/graduation/cases/case-038-bonus-track-shimokitazawa.jpg', 'morinakayasuaki / Figure 3 in Hiroki Nakajima, Sustainability 17(17), MDPI', 'MDPI', 'CC BY 4.0', 'https://www.mdpi.com/2071-1050/17/17/7583', 'exterior', true),
  ('b91c9529-a9ba-58f8-9abb-b80ade3de2d7'::uuid, 'bbd87e2f-2345-5eb4-8284-512d9cc2a0a0'::uuid, 'mikan-shimokita', 'CASE-039', '/images/graduation/cases/case-039-mikan-shimokita.jpg', 'Souka Kinmei', 'Wikimedia Commons', 'CC0', 'https://commons.wikimedia.org/wiki/File:%E5%95%86%E6%A5%AD%E6%96%BD%E8%A8%AD%E3%80%8C%E3%83%9F%E3%82%AB%E3%83%B3%E4%B8%8B%E5%8C%97%E3%80%8D.jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL, building_slug text NOT NULL, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-038', '3a86512e-ffa7-59d8-942a-585622839947'::uuid, 'bonus-track-shimokitazawa', '旧铁路用地变成小店创业和街区交流空间，保留低层、可逛、可参与的街区气质。', NULL, 'BONUS TRACK Shimokitazawa is a reference case for reading Design topic: 旧铁路用地, Design topic: 小店创业, neighborhoodrenewal, Design topic: 步行. It can inform thesis thinking about mixed programs, operation, and place-making.', '旧鉄道用地に小さな店舗と活動を並べた街区更新。大規模開発ではなく、小商いと歩行で場所を育てる方法を読める。', ARRAY['旧铁路用地', '小店创业', '街区更新', '步行', '社区商业']::text[], '{}'::text[], ARRAY['Design topic: 旧铁路用地', 'Design topic: 小店创业', 'neighborhoodrenewal', 'Design topic: 步行', 'Design topic: community商业']::text[], ARRAY['旧鉄道用地', '小店舗起業', '街区更新', '歩行', 'コミュニティ商業']::text[], NULL, NULL, 'https://tbma.jp/en/works/bonus-track/', 'published'),
  ('CASE-039', 'bbd87e2f-2345-5eb4-8284-512d9cc2a0a0'::uuid, 'mikan-shimokita', '高架下商业与工作空间以未完成感和可变骨架回应下北泽的街区文化。', NULL, 'MIKAN SHIMOKITA is a reference case for reading Design topic: 高架下, Design topic: 商业, Design topic: shared办公, neighborhoodculture. It can inform thesis thinking about mixed programs, operation, and place-making.', '高架下に商業、シェアオフィス、街区文化を重ねた事例。雨を避けられる線状空間を日常的な滞在と仕事の場へ変えている。', ARRAY['高架下', '商业', '共享办公', '街区文化', '可变空间']::text[], '{}'::text[], ARRAY['Design topic: 高架下', 'Design topic: 商业', 'Design topic: shared办公', 'neighborhoodculture', 'Design topic: 可变space']::text[], ARRAY['高架下', '商業', 'シェアオフィス', '街区文化', '可変空間']::text[], NULL, NULL, 'https://tjda.com/en/projects/mikan-shimokita/', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('3a86512e-ffa7-59d8-942a-585622839947'::uuid, 'bonus-track-shimokitazawa', 'retail', true, 1.000, 'https://tbma.jp/en/works/bonus-track/', 'TSUBAME ARCHITECTS identifies BONUS TRACK as a new shopping street designed to support individuals starting small shops while retaining Shimokitazawa''s character. The official project page records completion in April 2020 and identifies TSUBAME ARCHITECTS as architect.', '2026-07-12T00:00:00Z'::timestamptz),
  ('3a86512e-ffa7-59d8-942a-585622839947'::uuid, 'bonus-track-shimokitazawa', 'mixed-use', false, 1.000, 'https://tbma.jp/en/works/bonus-track/', 'TSUBAME ARCHITECTS identifies BONUS TRACK as a new shopping street designed to support individuals starting small shops while retaining Shimokitazawa''s character. The official project page records completion in April 2020 and identifies TSUBAME ARCHITECTS as architect.', '2026-07-12T00:00:00Z'::timestamptz),
  ('3a86512e-ffa7-59d8-942a-585622839947'::uuid, 'bonus-track-shimokitazawa', 'public-space', false, 1.000, 'https://tbma.jp/en/works/bonus-track/', 'TSUBAME ARCHITECTS identifies BONUS TRACK as a new shopping street designed to support individuals starting small shops while retaining Shimokitazawa''s character. The official project page records completion in April 2020 and identifies TSUBAME ARCHITECTS as architect.', '2026-07-12T00:00:00Z'::timestamptz),
  ('bbd87e2f-2345-5eb4-8284-512d9cc2a0a0'::uuid, 'mikan-shimokita', 'retail', true, 1.000, 'https://tjda.com/en/projects/mikan-shimokita/', 'Taiju Yamashita Design and Architecture identifies MIKAN SHIMOKITA as a shopping complex beneath the elevated Keio Inokashira Line tracks at Shimokitazawa Station. The official project page records opening in 2022 and describes retail, shared office and neighborhood-cultural uses.', '2026-07-12T00:00:00Z'::timestamptz),
  ('bbd87e2f-2345-5eb4-8284-512d9cc2a0a0'::uuid, 'mikan-shimokita', 'mixed-use', false, 1.000, 'https://tjda.com/en/projects/mikan-shimokita/', 'Taiju Yamashita Design and Architecture identifies MIKAN SHIMOKITA as a shopping complex beneath the elevated Keio Inokashira Line tracks at Shimokitazawa Station. The official project page records opening in 2022 and describes retail, shared office and neighborhood-cultural uses.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  reused_building_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  invalid_profile_buildings integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 2
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 2
    OR (SELECT count(*) FROM building_seed) <> 2
    OR (SELECT count(*) FROM reused_building_seed) <> 0
    OR (SELECT count(*) FROM image_seed) <> 2
    OR (SELECT count(*) FROM profile_seed) <> 2
    OR (SELECT count(*) FROM assignment_seed) <> 5 THEN
    RAISE EXCEPTION 'Graduation Shimokitazawa retail batch 001 seed count mismatch';
  END IF;

  SELECT count(*) INTO reused_building_matches
  FROM reused_building_seed seed JOIN public.buildings target USING (id, slug);
  IF reused_building_matches <> 0 THEN
    RAISE EXCEPTION 'Reused building UUID/slug pairs drifted: matched %', reused_building_matches;
  END IF;

  SELECT count(*) INTO invalid_profile_buildings
  FROM profile_seed profile
  LEFT JOIN building_seed created ON created.id = profile.building_id AND created.slug = profile.building_slug
  LEFT JOIN reused_building_seed reused ON reused.id = profile.building_id AND reused.slug = profile.building_slug
  WHERE created.id IS NULL AND reused.id IS NULL;
  IF invalid_profile_buildings <> 0 THEN
    RAISE EXCEPTION 'Profile seed references % unreviewed canonical buildings', invalid_profile_buildings;
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 0 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['retail', 'mixed-use', 'public-space']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['commercial']::text[]);
  IF required_function_matches <> 3
    OR required_type_matches <> 1 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation Shimokitazawa retail batch 001 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 2
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 2
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 2
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 2
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 5
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 2
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 2 THEN
    RAISE EXCEPTION 'Graduation Shimokitazawa retail batch 001 post-write verification failed';
  END IF;
END $$;

COMMIT;
