import type { ExamConcept } from './types'

export const examConcepts: ExamConcept[] = [
  {
    id: 'bcr-formula',
    kind: 'formula',
    label: '建蔽率 = 建築面積 ÷ 敷地面積 × 100%',
    topicSlugs: ['building-coverage-ratio'],
    glossarySlugs: ['building-coverage-ratio', 'building-area', 'site-area'],
    sourceRefs: ['building-coverage-ratio:official-source'],
    note: 'Core area-control formula for footprint ratio questions.',
  },
  {
    id: 'far-formula',
    kind: 'formula',
    label: '容積率 = 延べ面積 ÷ 敷地面積 × 100%',
    topicSlugs: ['floor-area-ratio'],
    glossarySlugs: ['floor-area-ratio', 'total-floor-area', 'site-area'],
    sourceRefs: ['floor-area-ratio:official-source'],
    note: 'Core area-control formula for total floor-area intensity.',
  },
  {
    id: 'road-width-far-coefficients',
    kind: 'condition',
    label: '4/10・6/10',
    topicSlugs: ['floor-area-ratio'],
    glossarySlugs: ['floor-area-ratio', 'front-road', 'road-width'],
    sourceRefs: ['floor-area-ratio:official-source'],
    note: 'Study shorthand for road-width FAR coefficients. Final use requires legal verification.',
  },
  {
    id: 'smaller-far-rule',
    kind: 'process',
    label: '小さい方を採用',
    topicSlugs: ['floor-area-ratio'],
    glossarySlugs: ['floor-area-ratio'],
    sourceRefs: ['floor-area-ratio:official-source'],
    note: 'Compare designated FAR and road-width FAR, then use the smaller value in study examples.',
  },
  {
    id: 'road-access-two-meter',
    kind: 'condition',
    label: '2m以上接道',
    topicSlugs: ['road-access-obligation'],
    glossarySlugs: ['road-access-obligation', 'front-road'],
    sourceRefs: ['road-access-obligation:official-source'],
    note: 'High-frequency access condition tied to Article 43 study logic.',
  },
  {
    id: 'article-42-road',
    kind: 'keyword',
    label: '建築基準法上の道路・第42条道路',
    topicSlugs: ['road-access-obligation'],
    glossarySlugs: ['road-access-obligation', 'front-road', 'road-width'],
    sourceRefs: ['road-access-obligation:official-source'],
    note: 'Road access questions require checking whether the route is legally treated as a road.',
  },
  {
    id: 'road-slant-slope',
    kind: 'condition',
    label: '道路斜線 1.25・1.5',
    topicSlugs: ['road-slant-restriction'],
    glossarySlugs: ['road-slant-restriction', 'road-width'],
    sourceRefs: ['road-slant-restriction:official-source', 'class-materials:height-restrictions'],
    note: 'Study slopes for residential and other categories. Treat as draft educational shorthand.',
  },
  {
    id: 'opposite-road-boundary',
    kind: 'keyword',
    label: '反対側道路境界線',
    topicSlugs: ['road-slant-restriction'],
    glossarySlugs: ['road-slant-restriction', 'front-road'],
    sourceRefs: ['road-slant-restriction:official-source', 'class-materials:height-restrictions'],
    note: 'Common exam trap: the road slant starts from the opposite road boundary.',
  },
  {
    id: 'setback-relaxation',
    kind: 'condition',
    label: '後退緩和',
    topicSlugs: ['road-slant-restriction'],
    glossarySlugs: ['road-slant-restriction'],
    sourceRefs: ['road-slant-restriction:official-source', 'class-materials:height-restrictions'],
    note: 'Setback can affect the horizontal-distance reading, but it is not a universal free pass.',
  },
  {
    id: 'sky-factor',
    kind: 'keyword',
    label: '天空率',
    topicSlugs: ['road-slant-restriction', 'north-side-slant-restriction'],
    glossarySlugs: ['sky-factor'],
    sourceRefs: ['road-slant-restriction:official-source'],
    note: 'Alternative review concept; not a simple exemption from height controls.',
  },
  {
    id: 'north-side-starting-height',
    kind: 'condition',
    label: '北側斜線 5m・10m',
    topicSlugs: ['north-side-slant-restriction'],
    glossarySlugs: ['north-side-slant-restriction'],
    sourceRefs: ['north-side-slant-restriction:official-source', 'class-materials:height-restrictions'],
    note: 'Starting-height study values tied to residential zoning categories.',
  },
  {
    id: 'north-side-slope',
    kind: 'condition',
    label: '北側斜線 1.25',
    topicSlugs: ['north-side-slant-restriction'],
    glossarySlugs: ['north-side-slant-restriction'],
    sourceRefs: ['north-side-slant-restriction:official-source', 'class-materials:height-restrictions'],
    note: 'Study slope used with starting height and north-side horizontal distance.',
  },
  {
    id: 'true-north',
    kind: 'keyword',
    label: '真北',
    topicSlugs: ['north-side-slant-restriction'],
    glossarySlugs: ['north-side-slant-restriction', 'shadow-regulation'],
    sourceRefs: ['north-side-slant-restriction:official-source'],
    note: 'North-side controls require careful reading of north-side direction and boundary conditions.',
  },
  {
    id: 'shadow-vs-north-side-slant',
    kind: 'trap',
    label: '北側斜線 vs 日影規制',
    topicSlugs: ['north-side-slant-restriction'],
    glossarySlugs: ['north-side-slant-restriction', 'shadow-regulation'],
    sourceRefs: ['north-side-slant-restriction:official-source'],
    note: 'North-side slant is a geometric height envelope; shadow regulation concerns shadow duration.',
  },
  {
    id: 'fire-resistant-building',
    kind: 'keyword',
    label: '耐火建築物',
    topicSlugs: ['fire-prevention-district', 'building-coverage-ratio'],
    glossarySlugs: ['fire-resistant-building', 'fire-prevention-district'],
    sourceRefs: ['fire-prevention-district:official-source'],
    note: 'Important fire-performance keyword, often paired with district and scale conditions.',
  },
  {
    id: 'quasi-fire-resistant-building',
    kind: 'keyword',
    label: '準耐火建築物',
    topicSlugs: ['quasi-fire-prevention-district'],
    glossarySlugs: ['quasi-fire-resistant-building', 'quasi-fire-prevention-district'],
    sourceRefs: ['quasi-fire-prevention-district:official-source'],
    note: 'Intermediate fire-performance keyword used in quasi-fire district study.',
  },
  {
    id: 'zoning-use-restriction',
    kind: 'process',
    label: '用途地域 → 用途制限 → 規模・形態制限',
    topicSlugs: ['zoning-districts'],
    glossarySlugs: ['zoning-districts'],
    sourceRefs: ['zoning-districts:official-source'],
    note: 'Study order: read zoning and use permissibility before calculations.',
  },
]

export const examConceptsById = Object.fromEntries(
  examConcepts.map(concept => [concept.id, concept])
) as Record<string, ExamConcept>
