import type { LearningSourceMaterial, LearningSourceTopicNote } from './types'
import { remainingLearningSourceMaterials } from './remaining-materials'

const classMaterialCopyrightNote =
  'Do not reproduce full text or scanned pages. Use only for private study reference, short citation, page reference, and editorial paraphrase.'

export const classLearningSourceMaterials: LearningSourceMaterial[] = [
  ...remainingLearningSourceMaterials,
  {
    id: 'rc-overview-2025',
    slug: 'rc-overview-2025',
    title: '01_概要.pdf',
    sourceType: 'lecture_notes',
    language: 'ja',
    year: 2025,
    fileName: '01_概要.pdf',
    usageScope: 'reference_only',
    copyrightNote: classMaterialCopyrightNote,
    relatedTopicSlugs: [],
    relatedGlossarySlugs: ['reinforced-concrete', 'rigid-frame-structure', 'flat-slab-structure', 'wall-structure'],
    coveredAreas: ['鉄筋コンクリート', '構造形式', '配筋', '構造力学'],
    extractionStatus: 'draft',
    notes: 'Used to identify foundational RC structure vocabulary. Numerical examples and historical attributions require independent review.',
  },
  {
    id: 'rc-cement-2025',
    slug: 'rc-cement-2025',
    title: '02_コンクリート_材料①セメント.pdf',
    sourceType: 'lecture_notes',
    language: 'ja',
    year: 2025,
    fileName: '02_コンクリート_材料①セメント.pdf',
    usageScope: 'reference_only',
    copyrightNote: classMaterialCopyrightNote,
    relatedTopicSlugs: [],
    relatedGlossarySlugs: ['cement', 'hydration', 'heat-of-hydration', 'portland-cement', 'blast-furnace-cement', 'fly-ash-cement'],
    coveredAreas: ['セメント', '水和', '混合セメント', 'コンクリート材料'],
    extractionStatus: 'draft',
    notes: 'Terminology source only. JIS and JASS classifications, limits, and environmental figures must be checked against current primary sources.',
  },
  {
    id: 'rc-aggregate-2025',
    slug: 'rc-aggregate-2025',
    title: '03_コンクリート_材料②骨材.pdf',
    sourceType: 'lecture_notes',
    language: 'ja',
    year: 2025,
    fileName: '03_コンクリート_材料②骨材.pdf',
    usageScope: 'reference_only',
    copyrightNote: classMaterialCopyrightNote,
    relatedTopicSlugs: [],
    relatedGlossarySlugs: ['aggregate', 'fine-aggregate', 'coarse-aggregate'],
    coveredAreas: ['骨材', '粒度', '材料分離', 'アルカリ骨材反応'],
    extractionStatus: 'draft',
    notes: 'Used for aggregate vocabulary and relationships. Classification thresholds and test requirements remain draft.',
  },
  {
    id: 'rc-mix-2025',
    slug: 'rc-mix-2025',
    title: '04_コンクリート_調合.pdf',
    sourceType: 'lecture_notes',
    language: 'ja',
    year: 2025,
    fileName: '04_コンクリート_調合.pdf',
    usageScope: 'reference_only',
    copyrightNote: classMaterialCopyrightNote,
    relatedTopicSlugs: [],
    relatedGlossarySlugs: ['water-cement-ratio', 'slump', 'curing', 'bleeding', 'laitance', 'cold-joint', 'carbonation'],
    coveredAreas: ['調合', '強度', '養生', '施工欠陥', '耐久性'],
    extractionStatus: 'draft',
    notes: 'Used for mix-design and durability terminology. Public definitions intentionally omit edition-sensitive numerical limits.',
  },
  {
    id: 'rc-rebar-2025',
    slug: 'rc-rebar-2025',
    title: '05_鉄筋・配筋①.pdf',
    sourceType: 'lecture_notes',
    language: 'ja',
    year: 2025,
    fileName: '05_鉄筋・配筋①.pdf',
    usageScope: 'reference_only',
    copyrightNote: classMaterialCopyrightNote,
    relatedTopicSlugs: [],
    relatedGlossarySlugs: ['deformed-bar', 'anchorage', 'stirrup', 'hoop-reinforcement'],
    coveredAreas: ['鉄筋', '付着', '定着', '配筋'],
    extractionStatus: 'draft',
    notes: 'Used for reinforcement vocabulary. Bar grades, dimensions, and detailing rules require current standards review.',
  },
  {
    id: 'interior-coordination-2025',
    slug: 'interior-coordination-2025',
    title: 'ICオリジナル2025まとめのコピー.pdf',
    sourceType: 'course_handbook',
    language: 'ja',
    year: 2025,
    fileName: 'ICオリジナル2025まとめのコピー.pdf',
    usageScope: 'reference_only',
    copyrightNote: classMaterialCopyrightNote,
    relatedTopicSlugs: [],
    relatedGlossarySlugs: [],
    coveredAreas: ['インテリアコーディネーション', '家具', '材料', '照明', 'カラー'],
    extractionStatus: 'draft',
    notes: 'Image-heavy handbook with damaged embedded-font extraction. Only page-targeted OCR and editorial paraphrase may be used.',
  },
  {
    id: 'interior-style-reference-2025',
    slug: 'interior-style-reference-2025',
    title: '別冊表紙2025まとめのコピー.pdf',
    sourceType: 'reference_booklet',
    language: 'ja',
    year: 2025,
    fileName: '別冊表紙2025まとめのコピー.pdf',
    usageScope: 'reference_only',
    copyrightNote: classMaterialCopyrightNote,
    relatedTopicSlugs: [],
    relatedGlossarySlugs: [],
    coveredAreas: ['インテリアスタイル', '家具', '照明', '仕上材'],
    extractionStatus: 'draft',
    notes: 'Reference-only style booklet. Style labels are candidates for normalization, not authoritative historical classifications.',
  },
  {
    id: 'houki-ii-exercises-2026-first-term',
    slug: 'houki-ii-exercises-2026-first-term',
    title: '法規Ⅱ_演習_2026前期.pdf',
    sourceType: 'exam_material',
    language: 'ja',
    year: 2026,
    fileName: '法規Ⅱ_演習_2026前期.pdf',
    usageScope: 'reference_only',
    copyrightNote: classMaterialCopyrightNote,
    relatedTopicSlugs: [
      'road-slant-restriction',
      'north-side-slant-restriction',
    ],
    relatedGlossarySlugs: [
      'road-slant-restriction',
      'north-side-slant-restriction',
      'sky-factor',
      'shadow-regulation',
    ],
    coveredAreas: ['高さ制限', '避難施設', '内装制限', '確認申請'],
    extractionStatus: 'draft',
    reviewer: undefined,
    lastReviewed: undefined,
    notes:
      'Class exercise material used as a private study reference for identifying exam-style prompts, calculation patterns, and final-exam scope. Do not store full questions, answer text, or scanned pages in the repository.',
  },
  {
    id: 'houki-ii-underlined-law-book-2025',
    slug: 'houki-ii-underlined-law-book-2025',
    title: '法規Ⅱ_アンダーライン_法令集2025年版.pdf',
    sourceType: 'law_book',
    language: 'ja',
    year: 2025,
    fileName: '法規Ⅱ_アンダーライン_法令集2025年版.pdf',
    usageScope: 'reference_only',
    copyrightNote: classMaterialCopyrightNote,
    relatedTopicSlugs: [
      'road-slant-restriction',
      'north-side-slant-restriction',
    ],
    relatedGlossarySlugs: [
      'road-slant-restriction',
      'north-side-slant-restriction',
      'sky-factor',
      'shadow-regulation',
    ],
    coveredAreas: ['建築基準法', '高さ制限', '避難施設', '内装制限', '確認申請'],
    extractionStatus: 'draft',
    reviewer: undefined,
    lastReviewed: undefined,
    notes:
      'Underlined law-book material used only as a private reference for locating highlighted articles and confirming study emphasis. Official legal verification must still use public official sources such as e-Gov.',
  },
]

export const classLearningSourceTopicNotes: LearningSourceTopicNote[] = [
  {
    topicSlug: 'road-slant-restriction',
    sourceMaterialIds: [
      'houki-ii-exercises-2026-first-term',
      'houki-ii-underlined-law-book-2025',
    ],
    referenceScope: ['高さ制限 1〜5', '高さ制限５ 解答の穴埋めキーワード'],
    note:
      'Referenced only to strengthen exam focus, worked examples, and memory tips around road height restriction keywords. No full problem statements or scanned pages are reproduced.',
  },
  {
    topicSlug: 'north-side-slant-restriction',
    sourceMaterialIds: [
      'houki-ii-exercises-2026-first-term',
      'houki-ii-underlined-law-book-2025',
    ],
    referenceScope: ['高さ制限 1〜5', '高さ制限５ 解答の穴埋めキーワード'],
    note:
      'Referenced only to strengthen exam focus, worked examples, and memory tips around north-side height restriction keywords. No full problem statements or scanned pages are reproduced.',
  },
]
