import type { LearningSourceCandidateGroup } from './types'

export const rcInteriorCandidateGroups: LearningSourceCandidateGroup[] = [
  { sourceMaterialId: 'rc-overview-2025', page: 2, category: 'building-part', terms: ['パラペット', 'スラブ', '配筋', '大梁', '小梁'] },
  { sourceMaterialId: 'rc-overview-2025', page: 3, category: 'structure', terms: ['鉄筋コンクリート', '圧縮', '引張', '座屈', 'クリープ', '脆性材料', '靭性材料'] },
  { sourceMaterialId: 'rc-overview-2025', page: 4, category: 'material', terms: ['線膨張率'] },
  { sourceMaterialId: 'rc-overview-2025', page: 5, category: 'structure', terms: ['ラーメン構造', '剛接合', 'フラットスラブ構造', '壁式構造', '積載荷重', '耐震壁'] },
  { sourceMaterialId: 'rc-overview-2025', page: 6, category: 'structure', terms: ['シェル構造', '懸垂線', 'カテナリーアーチ', '折板構造'] },
  { sourceMaterialId: 'rc-overview-2025', page: 7, category: 'structure', terms: ['単純梁', '曲げモーメント', '主筋', 'ピン支点', 'ローラー支点'] },
  { sourceMaterialId: 'rc-overview-2025', page: 8, category: 'structure', terms: ['片持ち梁'] },
  { sourceMaterialId: 'rc-overview-2025', page: 9, category: 'structure', terms: ['せん断力', 'あばら筋', '帯筋'] },
  { sourceMaterialId: 'rc-overview-2025', page: 10, category: 'drawing', terms: ['配筋詳細図', 'せん断補強筋'] },
  { sourceMaterialId: 'rc-cement-2025', page: 2, category: 'concrete', terms: ['セメント', '水硬性', '気硬性', '水和', '水和熱', 'フレッシュコンクリート', 'ワーカビリティー', 'レディーミクストコンクリート'] },
  { sourceMaterialId: 'rc-cement-2025', page: 3, category: 'concrete', terms: ['骨材', '細骨材', '粗骨材', 'モルタル'] },
  { sourceMaterialId: 'rc-cement-2025', page: 4, category: 'material', terms: ['ポルトランドセメント', 'ロータリーキルン', 'クリンカー', 'せっこう'] },
  { sourceMaterialId: 'rc-cement-2025', page: 5, category: 'material', terms: ['エーライト', 'ビーライト', 'アルミネート相', 'フェライト相'] },
  { sourceMaterialId: 'rc-cement-2025', page: 6, category: 'material', terms: ['早強ポルトランドセメント', '中庸熱ポルトランドセメント', '低熱ポルトランドセメント', 'マスコンクリート', '温度ひび割れ'] },
  { sourceMaterialId: 'rc-cement-2025', page: 7, category: 'concrete', terms: ['材齢', '圧縮強度'] },
  { sourceMaterialId: 'rc-cement-2025', page: 8, category: 'construction', terms: ['暑中コンクリート'] },
  { sourceMaterialId: 'rc-cement-2025', page: 9, category: 'material', terms: ['混合セメント', '高炉セメント', 'フライアッシュセメント', '潜在水硬性', 'ポゾラン反応'] },
  { sourceMaterialId: 'rc-aggregate-2025', page: 2, category: 'material', terms: ['重量骨材', '普通骨材', '軽量骨材', '人工軽量骨材'] },
  { sourceMaterialId: 'rc-aggregate-2025', page: 3, category: 'material', terms: ['天然骨材', '人工骨材', '再生骨材', '砕石', '砕砂', '高炉スラグ骨材'] },
  { sourceMaterialId: 'rc-aggregate-2025', page: 4, category: 'material', terms: ['粒度', '粒形', '実積率', '単位水量', '乾燥収縮'] },
  { sourceMaterialId: 'rc-aggregate-2025', page: 5, category: 'concrete', terms: ['細骨材率', '材料分離', '試験練り'] },
  { sourceMaterialId: 'rc-aggregate-2025', page: 6, category: 'durability', terms: ['アルカリ骨材反応', '反応性鉱物', '亀甲状ひび割れ'] },
  { sourceMaterialId: 'rc-aggregate-2025', page: 7, category: 'material', terms: ['粗骨材の最大寸法', '鉄筋のあき', 'かぶり厚さ'] },
  { sourceMaterialId: 'rc-mix-2025', page: 2, category: 'concrete', terms: ['計画調合', 'スランプ試験', 'AE剤', '連行空気', '巻き込み空気', '減水剤', '空気量'] },
  { sourceMaterialId: 'rc-mix-2025', page: 3, category: 'concrete', terms: ['水セメント比', '結合材'] },
  { sourceMaterialId: 'rc-mix-2025', page: 4, category: 'construction', terms: ['養生', '凝結', '硬化', '湿潤養生', 'プラスチック収縮ひび割れ', 'タンピング'] },
  { sourceMaterialId: 'rc-mix-2025', page: 6, category: 'structure', terms: ['設計基準強度', 'ヤング係数', '許容応力度'] },
  { sourceMaterialId: 'rc-mix-2025', page: 8, category: 'concrete', terms: ['耐久設計基準強度', '品質基準強度', '調合管理強度', '呼び強度', '調合強度', '標準養生'] },
  { sourceMaterialId: 'rc-mix-2025', page: 11, category: 'construction', terms: ['ブリーディング', '沈下ひび割れ', 'レイタンス', '打ち継ぎ'] },
  { sourceMaterialId: 'rc-mix-2025', page: 12, category: 'construction', terms: ['コールドジョイント', '打ち重ね'] },
  { sourceMaterialId: 'rc-mix-2025', page: 13, category: 'durability', terms: ['自己収縮', '温度収縮', 'エフロレッセンス'] },
  { sourceMaterialId: 'rc-mix-2025', page: 14, category: 'durability', terms: ['中性化', '中性化試験', '剥離', '剥落'] },
  { sourceMaterialId: 'rc-rebar-2025', page: 2, category: 'structure', terms: ['丸鋼', '異形棒鋼', '付着力', '呼び径', '定着', '上端筋', '下端筋'] },
  { sourceMaterialId: 'rc-rebar-2025', page: 3, category: 'structure', terms: ['降伏点', '引張強度', '降伏比', '応力ひずみ線図', '弾性領域', '塑性領域'] },
  { sourceMaterialId: 'rc-rebar-2025', page: 4, category: 'structure', terms: ['末端部フック', '余長'] },
  { sourceMaterialId: 'interior-coordination-2025', page: 1, category: 'interior', terms: ['インテリアコーディネーション', 'ウインドウトリートメント', '造作家具'] },
  { sourceMaterialId: 'interior-style-reference-2025', page: 1, category: 'interior-style', terms: ['ミニマルシンプル', 'イタリアモダン', 'アジアンエスニック', '和モダン', 'インダストリアル', 'ブルックリンスタイル', '北欧モダン', 'フレンチシャビー'] },
]

export const rcInteriorCandidateCount = rcInteriorCandidateGroups.reduce(
  (count, group) => count + group.terms.length,
  0,
)
