import type { LearningSourceCandidateGroup } from './types'

export const remainingCandidateGroups: LearningSourceCandidateGroup[] = [
  { sourceMaterialId: 'planning-2025-01', page: 4, category: 'planning', terms: ['メートル法', '尺貫法', 'ヤード・ポンド法', '縮尺'] },
  { sourceMaterialId: 'planning-2025-01', page: 17, category: 'planning', terms: ['人体寸法', '動作寸法', '物品寸法', '動作空間'] },
  { sourceMaterialId: 'planning-2025-01', page: 20, category: 'planning', terms: ['静的人体寸法', '人間工学', '対人距離'] },
  { sourceMaterialId: 'planning-2025-01', page: 28, category: 'planning', terms: ['モデュール', 'モデューラーコーディネーション', '基準寸法', '芯芯寸法'] },
  { sourceMaterialId: 'planning-2025-01', page: 40, category: 'drawing', terms: ['シングルグリッド', 'グリッドプランニング', '部材規格化'] },
  { sourceMaterialId: 'planning-2025-01', page: 45, category: 'planning', terms: ['畳割り', '京間', '江戸間', '中京間'] },

  { sourceMaterialId: 'planning-2025-02', page: 2, category: 'planning', terms: ['祝儀敷き', '不祝儀敷き', '回し敷き'] },
  { sourceMaterialId: 'planning-2025-02', page: 8, category: 'drawing', terms: ['縮尺', '配置図', '平面図', '展開図'] },
  { sourceMaterialId: 'planning-2025-02', page: 16, category: 'planning', terms: ['グルーピング', 'ゾーニング', '領域'] },
  { sourceMaterialId: 'planning-2025-02', page: 21, category: 'planning', terms: ['動線', '家事動線', '生活動線', 'サービス動線'] },

  { sourceMaterialId: 'planning-2025-03', page: 1, category: 'planning', terms: ['異種動線', '客動線', 'サービス動線', '避難経路', '二方向避難'] },
  { sourceMaterialId: 'planning-2025-03', page: 5, category: 'planning', terms: ['分割法', '連結法'] },
  { sourceMaterialId: 'planning-2025-03', page: 6, category: 'building-part', terms: ['開き戸', '引き戸', 'スイングドア', '折れ戸'] },
  { sourceMaterialId: 'planning-2025-03', page: 25, category: 'building-part', terms: ['引き違い窓', '上げ下げ窓', '開き窓', 'FIX窓', 'ジャロジー窓', 'トップライト'] },
  { sourceMaterialId: 'planning-2025-03', page: 42, category: 'building-part', terms: ['切妻屋根', '寄棟屋根', '片流れ屋根', '陸屋根'] },
  { sourceMaterialId: 'planning-2025-03', page: 54, category: 'building-part', terms: ['直階段', '折返し階段', '回り階段', 'らせん階段', '踊り場'] },

  { sourceMaterialId: 'planning-2025-04', page: 1, category: 'planning', terms: ['廊下', '中廊下', '片廊下', '車いす動線'] },
  { sourceMaterialId: 'planning-2025-04', page: 9, category: 'planning', terms: ['単位空間', '食事空間', '家具配置', 'アクティビティ寸法'] },
  { sourceMaterialId: 'planning-2025-04', page: 15, category: 'planning', terms: ['公室', '私室', '家事室', '水回り'] },
  { sourceMaterialId: 'planning-2025-04', page: 21, category: 'planning', terms: ['食寝分離', '就寝分離', 'プライバシー', '採光', '通風'] },
  { sourceMaterialId: 'planning-2025-04', page: 36, category: 'planning', terms: ['DK', 'LD', 'LDK', 'リビングダイニング'] },
  { sourceMaterialId: 'planning-2025-04', page: 47, category: 'planning', terms: ['壁付型キッチン', 'アイランド型キッチン', 'ペニンシュラ型キッチン'] },

  { sourceMaterialId: 'planning-2025-05', page: 1, category: 'planning', terms: ['家事室', 'ユーティリティ', '洗濯室', '脱衣室'] },
  { sourceMaterialId: 'planning-2025-05', page: 5, category: 'planning', terms: ['玄関', '下足箱', 'シューズインクローゼット'] },
  { sourceMaterialId: 'planning-2025-05', page: 9, category: 'planning', terms: ['中廊下型住宅', 'ワンルーム型住宅', 'コートハウス'] },
  { sourceMaterialId: 'planning-2025-05', page: 26, category: 'history', terms: ['町家', '通り庭', '箱階段', '縁側'] },
  { sourceMaterialId: 'planning-2025-05', page: 27, category: 'case-study', terms: ['スカイハウス', '塔の家', '住吉の長屋', '山川山荘'] },
  { sourceMaterialId: 'planning-2025-05', page: 43, category: 'case-study', terms: ['ロビー邸', 'シュレーダー邸', 'サヴォア邸', 'イームズ自邸'] },
  { sourceMaterialId: 'planning-2025-05', page: 48, category: 'construction', terms: ['在来軸組工法', 'プレカット', '枠組壁工法', 'ログハウス工法'] },

  { sourceMaterialId: 'planning-housing-2025-01', page: 3, category: 'housing', terms: ['片廊下型', '中廊下型', 'ツインコリダー型', '階段室型'] },
  { sourceMaterialId: 'planning-housing-2025-01', page: 13, category: 'housing', terms: ['集中型', 'ポイントアクセス型', 'コア'] },
  { sourceMaterialId: 'planning-housing-2025-01', page: 14, category: 'housing', terms: ['スキップフロア型', 'エレベーター停止階'] },
  { sourceMaterialId: 'planning-housing-2025-01', page: 17, category: 'housing', terms: ['フラット型', 'メゾネット型', '住戸断面形式'] },
  { sourceMaterialId: 'planning-housing-2025-01', page: 26, category: 'housing', terms: ['テラスハウス', 'ポイントハウス', 'コーポラティブハウス', 'コレクティブハウス'] },
  { sourceMaterialId: 'planning-housing-2025-01', page: 30, category: 'housing', terms: ['スケルトン・インフィル', '可変住宅', 'NEXT21'] },

  { sourceMaterialId: 'planning-housing-2025-02', page: 1, category: 'case-study', terms: ['同潤会アパート', '日本住宅公団', 'UR賃貸住宅'] },
  { sourceMaterialId: 'planning-housing-2025-02', page: 7, category: 'housing', terms: ['斜面住宅', '雁行型', '六甲の集合住宅'] },
  { sourceMaterialId: 'planning-housing-2025-02', page: 9, category: 'case-study', terms: ['桜台コートビレッジ', '低層集合住宅'] },
  { sourceMaterialId: 'planning-housing-2025-02', page: 13, category: 'case-study', terms: ['ユニテ・ダビタシオン', '垂直な田園都市', '住居単位'] },
  { sourceMaterialId: 'planning-housing-2025-02', page: 22, category: 'case-study', terms: ['アビタ67', 'モジュール住戸', 'プレファブリケーション'] },
  { sourceMaterialId: 'planning-housing-2025-02', page: 26, category: 'planning', terms: ['近隣住区理論', '住区基幹公園', '歩車分離', 'クルドサック'] },

  { sourceMaterialId: 'planning-office-2025', page: 2, category: 'office', terms: ['事務所ゾーニング', '来客動線', '執務動線', 'サービス動線'] },
  { sourceMaterialId: 'planning-office-2025', page: 10, category: 'office', terms: ['レンタブル比', '賃貸面積', '非収益部分'] },
  { sourceMaterialId: 'planning-office-2025', page: 14, category: 'office', terms: ['基準階', 'コアプラン', 'センターコア'] },
  { sourceMaterialId: 'planning-office-2025', page: 19, category: 'office', terms: ['ツインコア', 'ダブルコア', '片寄せコア', '分離コア'] },
  { sourceMaterialId: 'planning-office-2025', page: 24, category: 'office', terms: ['モジュラープランニング', 'システム天井', 'フリーアドレスオフィス', 'OAフロア'] },

  { sourceMaterialId: 'planning-commercial-2025', page: 13, category: 'commercial', terms: ['パサージュ', 'アーケード', '商業空間'] },
  { sourceMaterialId: 'planning-commercial-2025', page: 15, category: 'commercial', terms: ['百貨店', 'ショーウインドウ', '定価販売'] },
  { sourceMaterialId: 'planning-commercial-2025', page: 22, category: 'commercial', terms: ['セルフサービス', 'スーパーマーケット', '流通業態'] },
  { sourceMaterialId: 'planning-commercial-2025', page: 25, category: 'commercial', terms: ['ショッピングセンター', '核店舗', '専門店'] },
  { sourceMaterialId: 'planning-commercial-2025', page: 28, category: 'commercial', terms: ['オープンモール', 'エンクローズドモール', 'ハイブリッドモール'] },
  { sourceMaterialId: 'planning-commercial-2025', page: 40, category: 'commercial', terms: ['物品販売店', '飲食店', '店舗面積', '売場面積'] },
  { sourceMaterialId: 'planning-commercial-2025', page: 43, category: 'commercial', terms: ['客動線', '商品動線', 'サービス動線', '陳列棚'] },

  { sourceMaterialId: 'history-jp-2025-01', page: 3, category: 'history', terms: ['竪穴式住居', '高床式建物', '掘立柱', '環濠集落'] },
  { sourceMaterialId: 'history-jp-2025-01', page: 17, category: 'case-study', terms: ['吉野ヶ里遺跡', '北内郭', '南内郭'] },
  { sourceMaterialId: 'history-jp-2025-01', page: 20, category: 'history', terms: ['神社建築', '本殿', '式年遷宮', '式年造替'] },
  { sourceMaterialId: 'history-jp-2025-01', page: 26, category: 'history', terms: ['伊勢神宮', '神明造', '平入', '千木', '堅魚木'] },
  { sourceMaterialId: 'history-jp-2025-01', page: 30, category: 'history', terms: ['住吉大社', '住吉造', '妻入'] },
  { sourceMaterialId: 'history-jp-2025-01', page: 33, category: 'history', terms: ['出雲大社', '大社造', '心御柱'] },
  { sourceMaterialId: 'history-jp-2025-01', page: 36, category: 'history', terms: ['仏教建築', '伽藍配置', '飛鳥寺', '四天王寺'] },
  { sourceMaterialId: 'history-jp-2025-01', page: 38, category: 'history', terms: ['組物', '肘木', '大斗', '人字形割束', 'エンタシス'] },
  { sourceMaterialId: 'history-jp-2025-01', page: 39, category: 'case-study', terms: ['法隆寺', '西院伽藍', '金堂', '五重塔', '中門', '回廊'] },

  { sourceMaterialId: 'history-jp-2025-02', page: 1, category: 'history', terms: ['古代都市計画', '平城京', '平安京', '条坊制'] },
  { sourceMaterialId: 'history-jp-2025-02', page: 6, category: 'history', terms: ['浄土教建築', '阿弥陀堂', '末法思想'] },
  { sourceMaterialId: 'history-jp-2025-02', page: 10, category: 'case-study', terms: ['平等院鳳凰堂', '翼廊', '尾廊'] },
  { sourceMaterialId: 'history-jp-2025-02', page: 21, category: 'history', terms: ['中世仏教建築', '大仏様', '禅宗様', '和様'] },
  { sourceMaterialId: 'history-jp-2025-02', page: 41, category: 'history', terms: ['流造', '春日造', '中世神社建築'] },
  { sourceMaterialId: 'history-jp-2025-02', page: 44, category: 'case-study', terms: ['厳島神社', '海上社殿'] },
  { sourceMaterialId: 'history-jp-2025-02', page: 51, category: 'history', terms: ['寝殿造', '書院造', '寝殿', '対屋', '渡殿'] },

  { sourceMaterialId: 'history-jp-2025-03', page: 1, category: 'history', terms: ['城郭建築', '天守', '山城', '平山城', '平城'] },
  { sourceMaterialId: 'history-jp-2025-03', page: 8, category: 'history', terms: ['連郭式', '梯郭式', '輪郭式', '本丸', '二の丸', '三の丸'] },
  { sourceMaterialId: 'history-jp-2025-03', page: 12, category: 'history', terms: ['茶室', '数寄屋', '書院茶', '草庵茶室'] },
  { sourceMaterialId: 'history-jp-2025-03', page: 23, category: 'building-part', terms: ['躙口', '下地窓', '連子窓', '炉'] },
  { sourceMaterialId: 'history-jp-2025-03', page: 31, category: 'case-study', terms: ['待庵', '燕庵', '桂離宮'] },
  { sourceMaterialId: 'history-jp-2025-03', page: 41, category: 'history', terms: ['近世寺社建築', '懸造', '権現造'] },
  { sourceMaterialId: 'history-jp-2025-03', page: 44, category: 'history', terms: ['民家', '町家', '農家'] },

  { sourceMaterialId: 'history-jp-2025-035', page: 1, category: 'history', terms: ['本棟造', '大和棟', '合掌造り', '切妻造妻入'] },
  { sourceMaterialId: 'history-jp-2025-035', page: 2, category: 'building-part', terms: ['坪庭', '奥庭', '通り庭', '揚げ見世'] },
  { sourceMaterialId: 'history-jp-2025-035', page: 5, category: 'building-part', terms: ['格子', '虫籠窓', '通り庇'] },
  { sourceMaterialId: 'history-jp-2025-035', page: 9, category: 'case-study', terms: ['白川郷', '五箇山', '結'] },

  { sourceMaterialId: 'history-modern-jp-2025', page: 2, category: 'history', terms: ['擬洋風建築', 'コロニアル様式', '外国人居留地'] },
  { sourceMaterialId: 'history-modern-jp-2025', page: 10, category: 'history', terms: ['銀座煉瓦街', 'ジョサイア・コンドル', '工部大学校'] },
  { sourceMaterialId: 'history-modern-jp-2025', page: 18, category: 'history', terms: ['辰野金吾', '日本人建築家', '辰野式'] },
  { sourceMaterialId: 'history-modern-jp-2025', page: 27, category: 'history', terms: ['歴史主義建築', '古典主義', '様式建築'] },
  { sourceMaterialId: 'history-modern-jp-2025', page: 42, category: 'case-study', terms: ['築地本願寺', '伊東忠太'] },
  { sourceMaterialId: 'history-modern-jp-2025', page: 62, category: 'history', terms: ['日本モダニズム', 'ヨーロッパ造形運動', '近代建築運動'] },

  { sourceMaterialId: 'history-modern-jp-cases-2025', page: 1, category: 'history', terms: ['モダニズム建築', '国際様式', '近代建築三大巨匠'] },
  { sourceMaterialId: 'history-modern-jp-cases-2025', page: 12, category: 'history', terms: ['戦災復興', '戦後建築', '都市復興'] },
  { sourceMaterialId: 'history-modern-jp-cases-2025', page: 30, category: 'history', terms: ['住宅政策', '公営住宅', '住宅金融公庫', '日本住宅公団'] },
  { sourceMaterialId: 'history-modern-jp-cases-2025', page: 32, category: 'housing', terms: ['DK住宅', 'nDK', '食寝分離'] },
  { sourceMaterialId: 'history-modern-jp-cases-2025', page: 45, category: 'history', terms: ['メタボリズム', '国家プロジェクト', '丹下健三'] },
  { sourceMaterialId: 'history-modern-jp-cases-2025', page: 64, category: 'history', terms: ['ポストモダニズム', '機能主義批判', '歴史的引用'] },

  { sourceMaterialId: 'history-western-2025-01', page: 2, category: 'history', terms: ['エジプト建築', 'マスタバ', 'ピラミッド', '葬祭殿'] },
  { sourceMaterialId: 'history-western-2025-01', page: 14, category: 'history', terms: ['オリエント建築', 'ジッグラト', '記念性'] },
  { sourceMaterialId: 'history-western-2025-01', page: 21, category: 'history', terms: ['ギリシア建築', 'ポリス', 'アクロポリス', 'アゴラ'] },
  { sourceMaterialId: 'history-western-2025-01', page: 22, category: 'history', terms: ['オーダー', 'ドリス式', 'イオニア式', 'コリント式'] },
  { sourceMaterialId: 'history-western-2025-01', page: 28, category: 'case-study', terms: ['パルテノン神殿', '視覚補正', '大理石架構'] },
  { sourceMaterialId: 'history-western-2025-01', page: 34, category: 'history', terms: ['ローマ建築', 'ローマンコンクリート', '迫持アーチ', 'ヴォールト'] },
  { sourceMaterialId: 'history-western-2025-01', page: 40, category: 'case-study', terms: ['パンテオン', 'ロトンダ', 'ドーム', 'オクルス'] },
  { sourceMaterialId: 'history-western-2025-01', page: 48, category: 'case-study', terms: ['コロッセウム', '円形闘技場', 'アーケード'] },

  { sourceMaterialId: 'history-western-2025-02', page: 1, category: 'history', terms: ['初期キリスト教建築', 'バシリカ式', '集中式', 'アトリウム'] },
  { sourceMaterialId: 'history-western-2025-02', page: 8, category: 'history', terms: ['ビザンティン建築', 'ペンデンティブ', 'ギリシア十字', 'ドーム'] },
  { sourceMaterialId: 'history-western-2025-02', page: 17, category: 'case-study', terms: ['ハギア・ソフィア', 'モザイク', 'ミナレット'] },
  { sourceMaterialId: 'history-western-2025-02', page: 27, category: 'history', terms: ['イスラム建築', 'モスク', 'ミフラーブ', 'ミナレット', 'マドラサ'] },
  { sourceMaterialId: 'history-western-2025-02', page: 38, category: 'case-study', terms: ['アルハンブラ宮殿', 'コルドバ大モスク', 'アラベスク'] },
  { sourceMaterialId: 'history-western-2025-02', page: 44, category: 'history', terms: ['ロマネスク建築', '半円アーチ', '交差ヴォールト'] },
  { sourceMaterialId: 'history-western-2025-02', page: 58, category: 'history', terms: ['ゴシック建築', '尖頭アーチ', 'リブ・ヴォールト', '飛梁'] },
  { sourceMaterialId: 'history-western-2025-02', page: 73, category: 'history', terms: ['初期イギリス式', '装飾式', '垂直式', '扇形ヴォールト'] },

  { sourceMaterialId: 'rc-construction-2025', page: 2, category: 'construction', terms: ['鉄筋コンクリート造', '型枠', '配筋', '打設'] },
  { sourceMaterialId: 'rc-construction-2025', page: 6, category: 'construction', terms: ['壁配筋', '床配筋', 'せき板', '型枠解体'] },
  { sourceMaterialId: 'rc-construction-2025', page: 10, category: 'structure', terms: ['耐力壁', 'ラーメン構造'] },
  { sourceMaterialId: 'rc-construction-2025', page: 22, category: 'drawing', terms: ['柱スパン', '柱寸法', '梁幅', '梁せい'] },

  { sourceMaterialId: 'rc-worksheet-01', page: 1, category: 'structure', terms: ['圧縮力', '引張力', '座屈', '脆性', '靭性', '線膨張率', 'クリープ'] },
  { sourceMaterialId: 'rc-worksheet-01', page: 2, category: 'structure', terms: ['ラーメン構造', 'フラットスラブ構造', '壁式構造', 'シェル構造', '曲げモーメント', 'せん断力'] },
  { sourceMaterialId: 'rc-worksheet-02', page: 1, category: 'material', terms: ['水硬性', '水和熱', 'セメントペースト', 'ポルトランドセメント', '混合セメント'] },
  { sourceMaterialId: 'rc-worksheet-02', page: 3, category: 'material', terms: ['早強ポルトランドセメント', '中庸熱ポルトランドセメント', '低熱ポルトランドセメント', '高炉セメント', 'フライアッシュセメント'] },
  { sourceMaterialId: 'rc-worksheet-03', page: 1, category: 'material', terms: ['重量骨材', '普通骨材', '軽量骨材', '再生骨材', '高炉スラグ骨材', '実積率', '細骨材率'] },
  { sourceMaterialId: 'rc-worksheet-03', page: 2, category: 'durability', terms: ['アルカリ骨材反応', '反応性鉱物', '単位水量'] },
  { sourceMaterialId: 'rc-worksheet-04', page: 1, category: 'concrete', terms: ['調合', '水セメント比', '空気量', 'AE剤', '減水剤', '湿潤養生'] },
  { sourceMaterialId: 'rc-worksheet-04', page: 2, category: 'concrete', terms: ['設計基準強度', '耐久設計基準強度', '品質基準強度', '調合管理強度', '調合強度'] },
  { sourceMaterialId: 'rc-worksheet-04', page: 4, category: 'durability', terms: ['ブリーディング', 'レイタンス', 'エフロレッセンス', 'コールドジョイント', '中性化'] },
  { sourceMaterialId: 'rc-worksheet-05', page: 1, category: 'structure', terms: ['丸鋼', '異形棒鋼', '降伏点', '引張強度', 'ヤング係数'] },
  { sourceMaterialId: 'rc-worksheet-05', page: 2, category: 'structure', terms: ['末端部フック', '定着', '鉄筋のあき', '鉄筋間隔'] },
  { sourceMaterialId: 'rc-exam-answers-2025', page: 2, category: 'exam-concept', terms: ['応力ひずみ線図', '許容応力度', '混合セメント'] },
  { sourceMaterialId: 'rc-exam-answers-2025', page: 4, category: 'exam-concept', terms: ['調合計算', '水セメント比', '空気量', '細骨材率', '配筋読解'] },
  { sourceMaterialId: 'rc-exam-answers-2025', page: 5, category: 'exam-concept', terms: ['構造形式判別', '空間構想'] },

  { sourceMaterialId: 'exam-housing-2025', page: 2, category: 'exam-concept', terms: ['片廊下型', '中廊下型', '階段室型', '集中型'] },
  { sourceMaterialId: 'exam-housing-2025', page: 10, category: 'exam-concept', terms: ['スキップフロア型', '共用廊下', 'アクセス動線'] },
  { sourceMaterialId: 'exam-housing-2025', page: 14, category: 'exam-concept', terms: ['メゾネット型', 'フラット型', 'プライバシー'] },
  { sourceMaterialId: 'exam-housing-2025', page: 17, category: 'exam-concept', terms: ['コレクティブハウス', 'コーポラティブハウス', 'テラスハウス'] },
  { sourceMaterialId: 'exam-housing-2025', page: 30, category: 'exam-concept', terms: ['スケルトン・インフィル', '近隣住区', '住宅地道路計画'] },
  { sourceMaterialId: 'exam-office-2025', page: 2, category: 'exam-concept', terms: ['センターコア', 'ダブルコア', '分離コア', '二方向避難'] },
  { sourceMaterialId: 'exam-office-2025', page: 6, category: 'exam-concept', terms: ['レンタブル比', '基準階', '収益部分'] },
  { sourceMaterialId: 'exam-office-2025', page: 21, category: 'exam-concept', terms: ['システム天井', 'OAフロア', 'パーティション'] },
  { sourceMaterialId: 'exam-office-2025', page: 25, category: 'exam-concept', terms: ['エレベーターゾーニング', 'フリーアドレス'] },
  { sourceMaterialId: 'exam-commercial-2025', page: 3, category: 'exam-concept', terms: ['喫茶店', '客席面積', '店舗動線'] },
  { sourceMaterialId: 'exam-commercial-2025', page: 6, category: 'exam-concept', terms: ['カフェテリア', '配膳動線', '下げ膳動線'] },
  { sourceMaterialId: 'exam-commercial-2025', page: 18, category: 'exam-concept', terms: ['主通路', '補助通路', '陳列棚'] },
  { sourceMaterialId: 'exam-commercial-2025', page: 29, category: 'exam-concept', terms: ['飲食店厨房', 'カウンター高さ', 'サービス動線'] },

  { sourceMaterialId: 'custom-fixtures-reference', page: 1, category: 'interior', terms: ['造作家具', '置き家具', '人体系家具'] },
  { sourceMaterialId: 'custom-fixtures-reference', page: 2, category: 'furniture', terms: ['自立テーブル', '天板', '脚部'] },
  { sourceMaterialId: 'custom-fixtures-reference', page: 3, category: 'furniture', terms: ['収納家具', '背板', '間仕切り家具'] },
  { sourceMaterialId: 'interior-zoning-workflow', page: 1, category: 'interior', terms: ['クライアントプロフィール', 'ヒアリング', '条件整理', 'ゾーニング', '家具配置'] },
  { sourceMaterialId: 'lighting-layout-reference', page: 1, category: 'lighting', terms: ['リビング照明', 'ダイニング照明', 'ダウンライト'] },
  { sourceMaterialId: 'lighting-layout-reference', page: 2, category: 'lighting', terms: ['玄関照明', '階段照明', '廊下照明', 'キッチン照明'] },
  { sourceMaterialId: 'lighting-pendants-2025', page: 1, category: 'lighting', terms: ['ペンダントライト', 'ルイスポールセン'] },
  { sourceMaterialId: 'lighting-pendants-2025', page: 4, category: 'lighting', terms: ['レ・クリント', 'クラシックペンダント'] },
  { sourceMaterialId: 'lighting-pendants-2025', page: 6, category: 'lighting', terms: ['FLOS', 'スミスフィールド'] },
  { sourceMaterialId: 'lighting-pendants-2025', page: 9, category: 'lighting', terms: ['ネルソンバブルランプ', 'フォスカリーニ'] },
  { sourceMaterialId: 'lighting-pendants-2025', page: 15, category: 'lighting', terms: ['イサム・ノグチ', 'AKARI', 'アルテック'] },

  { sourceMaterialId: 'houki-ii-exercises-2026-first-term', page: 2, category: 'code', terms: ['道路高さ制限', '前面道路', '適用距離', '勾配'] },
  { sourceMaterialId: 'houki-ii-exercises-2026-first-term', page: 20, category: 'code', terms: ['北側高さ制限', '隣地高さ制限', '用途地域', '地盤面'] },
  { sourceMaterialId: 'houki-ii-exercises-2026-first-term', page: 38, category: 'code', terms: ['道路斜線制限', '後退緩和', '二以上の前面道路'] },
  { sourceMaterialId: 'houki-ii-exercises-2026-first-term', page: 48, category: 'code', terms: ['廊下幅', '歩行距離', '直通階段', '避難階段'] },
  { sourceMaterialId: 'houki-ii-exercises-2026-first-term', page: 52, category: 'code', terms: ['排煙設備', '非常用照明', '非常用進入口', '敷地内通路'] },
  { sourceMaterialId: 'houki-ii-exercises-2026-first-term', page: 56, category: 'code', terms: ['内装制限', '特殊建築物', '不燃材料'] },
  { sourceMaterialId: 'houki-ii-exercises-2026-first-term', page: 60, category: 'code', terms: ['確認申請', '確認済証', '用途変更'] },
  { sourceMaterialId: 'houki-ii-underlined-law-book-2025', page: 3, category: 'code', terms: ['道路高さ制限', '隣地高さ制限', '北側高さ制限'] },
  { sourceMaterialId: 'houki-ii-underlined-law-book-2025', page: 8, category: 'code', terms: ['避難階', '避難階段', '非常用照明'] },
  { sourceMaterialId: 'houki-ii-underlined-law-book-2025', page: 13, category: 'code', terms: ['排煙口', '手動開放装置', '排煙設備'] },
  { sourceMaterialId: 'houki-ii-underlined-law-book-2025', page: 17, category: 'code', terms: ['内装制限', '壁仕上げ', '天井仕上げ'] },
  { sourceMaterialId: 'houki-ii-underlined-law-book-2025', page: 20, category: 'code', terms: ['二以上の前面道路', '前面道路とみなす道路', '高低差緩和'] },
]

export const remainingCandidateCount = remainingCandidateGroups.reduce(
  (count, group) => count + group.terms.length,
  0,
)
