import type { GlossaryTerm } from './types'

export const rcMaterialGlossaryTerms: GlossaryTerm[] = [
  {
    id: 'reinforced-concrete',
    slug: 'reinforced-concrete',
    termJa: '鉄筋コンクリート',
    reading: 'てっきんコンクリート',
    termZh: '钢筋混凝土',
    termEn: 'Reinforced Concrete',
    category: 'structure',
    shortDefinitionZh: '把擅长受压的混凝土与擅长受拉的钢筋组合，使两者共同工作的结构材料。',
    shortDefinitionJa: '圧縮に強いコンクリートと引張に強い鉄筋を組み合わせ、両者を一体として働かせる構造材料です。',
    shortDefinitionEn: 'A structural material combining concrete in compression with reinforcing steel in tension.',
    searchKeywords: ['RC', '鉄筋コンクリート造', 'reinforced concrete structure', '钢筋混凝土结构'],
  },
  {
    id: 'rigid-frame-structure',
    slug: 'rigid-frame-structure',
    termJa: 'ラーメン構造',
    reading: 'ラーメンこうぞう',
    termZh: '刚架结构',
    termEn: 'Rigid-frame Structure',
    category: 'structure',
    shortDefinitionZh: '通过柱梁刚接形成框架，由构件弯曲与节点共同抵抗水平和竖向荷载的结构形式。',
    shortDefinitionJa: '柱と梁を剛接合した骨組で、部材の曲げと接合部によって水平力・鉛直力に抵抗する構造形式です。',
    shortDefinitionEn: 'A frame whose rigidly connected beams and columns resist loads through member bending and joint action.',
    searchKeywords: ['moment frame', 'rigid frame', '剛接合', '刚架'],
  },
  {
    id: 'flat-slab-structure',
    slug: 'flat-slab-structure',
    termJa: 'フラットスラブ構造',
    reading: 'フラットスラブこうぞう',
    termZh: '无梁楼盖结构',
    termEn: 'Flat-slab Structure',
    category: 'structure',
    shortDefinitionZh: '楼板不经普通梁而直接支承在柱上的结构形式，可获得较平整的天花空间。',
    shortDefinitionJa: '床スラブを通常の梁を介さず柱で直接支持する構造形式で、天井面を平滑にしやすい特徴があります。',
    shortDefinitionEn: 'A structural system in which floor slabs bear directly on columns without conventional beams.',
    searchKeywords: ['flat slab', '無梁版', '无梁楼板'],
  },
  {
    id: 'wall-structure',
    slug: 'wall-structure',
    termJa: '壁式構造',
    reading: 'かべしきこうぞう',
    termZh: '墙式结构',
    termEn: 'Wall Structure',
    category: 'structure',
    shortDefinitionZh: '主要由承重墙和楼板组成，以墙体承担竖向力和水平力的结构形式。',
    shortDefinitionJa: '主に耐力壁と床で構成し、壁によって鉛直力と水平力を負担する構造形式です。',
    shortDefinitionEn: 'A system of load-bearing walls and floors in which walls carry vertical and lateral forces.',
    searchKeywords: ['wall-type structure', 'load-bearing wall system', '壁式鉄筋コンクリート'],
  },
  {
    id: 'cement',
    slug: 'cement',
    termJa: 'セメント',
    reading: 'セメント',
    termZh: '水泥',
    termEn: 'Cement',
    category: 'material',
    shortDefinitionZh: '与水反应后硬化并把骨料结合在一起的粉状胶结材料，是混凝土的重要组成。',
    shortDefinitionJa: '水と反応して硬化し、骨材を結び付ける粉体状の結合材で、コンクリートの主要材料です。',
    shortDefinitionEn: 'A powdered binder that reacts with water, hardens, and binds aggregate in concrete.',
    searchKeywords: ['水泥', 'binder', '結合材'],
  },
  {
    id: 'hydration',
    slug: 'hydration',
    termJa: '水和',
    reading: 'すいわ',
    termZh: '水化',
    termEn: 'Hydration',
    category: 'concrete',
    shortDefinitionZh: '水泥成分与水发生化学反应、生成水化物并使材料逐渐凝结硬化的过程。',
    shortDefinitionJa: 'セメント成分が水と化学反応し、水和物を生成しながら凝結・硬化していく過程です。',
    shortDefinitionEn: 'The chemical reaction between cement and water that produces hydrates and leads to setting and hardening.',
    searchKeywords: ['水和反応', 'cement hydration', '水化反应'],
  },
  {
    id: 'heat-of-hydration',
    slug: 'heat-of-hydration',
    termJa: '水和熱',
    reading: 'すいわねつ',
    termZh: '水化热',
    termEn: 'Heat of Hydration',
    category: 'concrete',
    shortDefinitionZh: '水泥水化反应释放的热量，在大体积混凝土中会影响温度变化和开裂风险。',
    shortDefinitionJa: 'セメントの水和反応で発生する熱で、マスコンクリートでは温度変化やひび割れに関係します。',
    shortDefinitionEn: 'Heat released by cement hydration, important to temperature change and cracking risk in mass concrete.',
    searchKeywords: ['hydration heat', '水化热', '温度ひび割れ'],
  },
  {
    id: 'fresh-concrete',
    slug: 'fresh-concrete',
    termJa: 'フレッシュコンクリート',
    reading: 'フレッシュコンクリート',
    termZh: '新拌混凝土',
    termEn: 'Fresh Concrete',
    category: 'concrete',
    shortDefinitionZh: '从拌合到凝结前仍具有塑性、能够运输和浇筑的混凝土。',
    shortDefinitionJa: '練り混ぜ後から凝結前までの、運搬・打込みが可能な塑性状態のコンクリートです。',
    shortDefinitionEn: 'Concrete in its plastic state after mixing and before setting, while it can still be transported and placed.',
    searchKeywords: ['生コンクリート', 'fresh mix', '新鲜混凝土'],
  },
  {
    id: 'workability',
    slug: 'workability',
    termJa: 'ワーカビリティー',
    reading: 'ワーカビリティー',
    termZh: '和易性',
    termEn: 'Workability',
    category: 'concrete',
    shortDefinitionZh: '新拌混凝土在运输、浇筑、填充和密实时的操作难易程度，同时要避免明显离析。',
    shortDefinitionJa: 'フレッシュコンクリートの運搬、打込み、充填、締固めのしやすさを、材料分離への抵抗も含めて表す性質です。',
    shortDefinitionEn: 'The ease of transporting, placing, filling, and compacting fresh concrete without harmful segregation.',
    searchKeywords: ['施工性', '和易性', 'placeability'],
  },
  {
    id: 'aggregate',
    slug: 'aggregate',
    termJa: '骨材',
    reading: 'こつざい',
    termZh: '骨料',
    termEn: 'Aggregate',
    category: 'material',
    shortDefinitionZh: '混凝土或砂浆中使用的砂、砾石、碎石等颗粒材料，形成主要体积和骨架。',
    shortDefinitionJa: 'コンクリートやモルタルに用いる砂、砂利、砕石などの粒状材料で、主要な体積と骨格をつくります。',
    shortDefinitionEn: 'Granular material such as sand, gravel, or crushed stone forming much of concrete or mortar.',
    searchKeywords: ['骨料', 'sand and gravel', 'aggregate material'],
  },
  {
    id: 'fine-aggregate',
    slug: 'fine-aggregate',
    termJa: '細骨材',
    reading: 'さいこつざい',
    termZh: '细骨料',
    termEn: 'Fine Aggregate',
    category: 'material',
    shortDefinitionZh: '粒径较小、主要用于填充粗骨料之间空隙的骨料，典型材料是砂。',
    shortDefinitionJa: '粒径が小さく、主に粗骨材間の空隙を満たす骨材で、砂が代表例です。',
    shortDefinitionEn: 'Smaller aggregate, typically sand, used to fill spaces between coarse aggregate particles.',
    searchKeywords: ['砂', 'fine aggregate', '细集料'],
  },
  {
    id: 'coarse-aggregate',
    slug: 'coarse-aggregate',
    termJa: '粗骨材',
    reading: 'そこつざい',
    termZh: '粗骨料',
    termEn: 'Coarse Aggregate',
    category: 'material',
    shortDefinitionZh: '混凝土中粒径较大的骨料，如砾石或碎石，构成混凝土骨架的重要部分。',
    shortDefinitionJa: '砂利や砕石など、コンクリート中で比較的大きな粒径を持ち骨格をつくる骨材です。',
    shortDefinitionEn: 'Larger aggregate such as gravel or crushed stone that forms a main part of the concrete skeleton.',
    searchKeywords: ['砂利', '砕石', 'coarse aggregate', '粗集料'],
  },
  {
    id: 'mortar',
    slug: 'mortar',
    termJa: 'モルタル',
    reading: 'モルタル',
    termZh: '砂浆',
    termEn: 'Mortar',
    category: 'material',
    shortDefinitionZh: '通常由水泥、水和细骨料组成的材料，可用于砌筑、抹面，也构成混凝土中的基质部分。',
    shortDefinitionJa: '一般にセメント、水、細骨材からなる材料で、組積・仕上げやコンクリートの基質部分に用いられます。',
    shortDefinitionEn: 'A mix generally made from cement, water, and fine aggregate, used in masonry, finishes, and concrete matrix.',
    searchKeywords: ['砂浆', 'cement mortar'],
  },
  {
    id: 'portland-cement',
    slug: 'portland-cement',
    termJa: 'ポルトランドセメント',
    reading: 'ポルトランドセメント',
    termZh: '硅酸盐水泥',
    termEn: 'Portland Cement',
    category: 'material',
    shortDefinitionZh: '以熟料和适量石膏等制成的常用水硬性水泥，是多种混凝土配合的基础胶结材料。',
    shortDefinitionJa: 'クリンカーと適量のせっこうなどからつくられる代表的な水硬性セメントで、多くのコンクリートに用いられます。',
    shortDefinitionEn: 'A common hydraulic cement made primarily from clinker and gypsum, widely used as a concrete binder.',
    searchKeywords: ['Pセメント', 'Portland cement', '波特兰水泥'],
  },
  {
    id: 'blast-furnace-cement',
    slug: 'blast-furnace-cement',
    termJa: '高炉セメント',
    reading: 'こうろセメント',
    termZh: '高炉水泥',
    termEn: 'Blast-furnace Cement',
    category: 'material',
    shortDefinitionZh: '将高炉矿渣微粉与水泥组分结合使用的混合水泥，性能会随配比和等级而变化。',
    shortDefinitionJa: '高炉スラグ微粉末をセメント成分と組み合わせた混合セメントで、性能は混合割合や区分により異なります。',
    shortDefinitionEn: 'A blended cement incorporating ground granulated blast-furnace slag, with properties varying by blend.',
    searchKeywords: ['高炉スラグ', 'slag cement', 'GGBS', '矿渣水泥'],
  },
  {
    id: 'fly-ash-cement',
    slug: 'fly-ash-cement',
    termJa: 'フライアッシュセメント',
    reading: 'フライアッシュセメント',
    termZh: '粉煤灰水泥',
    termEn: 'Fly-ash Cement',
    category: 'material',
    shortDefinitionZh: '掺入粉煤灰的混合水泥，可改变新拌性能、水化热及长期强度发展。',
    shortDefinitionJa: 'フライアッシュを混合したセメントで、流動性、水和熱、長期的な強度発現などに影響します。',
    shortDefinitionEn: 'A blended cement containing fly ash, affecting workability, heat evolution, and long-term strength development.',
    searchKeywords: ['fly ash', 'FA cement', '粉煤灰'],
  },
  {
    id: 'water-cement-ratio',
    slug: 'water-cement-ratio',
    termJa: '水セメント比',
    reading: 'みずセメントひ',
    termZh: '水灰比',
    termEn: 'Water-cement Ratio',
    category: 'concrete',
    shortDefinitionZh: '拌合水质量与水泥质量之比，是影响混凝土强度、耐久性和施工性的核心指标。',
    shortDefinitionJa: '練混ぜ水の質量をセメントの質量で割った比率で、強度、耐久性、施工性に大きく関係します。',
    shortDefinitionEn: 'The mass ratio of mixing water to cement, central to concrete strength, durability, and workability.',
    searchKeywords: ['W/C', 'water cement ratio', '水灰比', 'みずせめんとひ'],
  },
  {
    id: 'slump',
    slug: 'slump',
    termJa: 'スランプ',
    reading: 'スランプ',
    termZh: '坍落度',
    termEn: 'Slump',
    category: 'concrete',
    shortDefinitionZh: '通过标准试验观察新拌混凝土下沉量，以表示其稠度和流动状态的指标。',
    shortDefinitionJa: '標準試験でフレッシュコンクリートの沈下量を測り、軟らかさや流動状態を表す指標です。',
    shortDefinitionEn: 'A measure of fresh-concrete consistency based on the vertical subsidence observed in a standard test.',
    searchKeywords: ['スランプ試験', 'slump test', '坍落度试验'],
  },
  {
    id: 'air-entraining-agent',
    slug: 'air-entraining-agent',
    termJa: 'AE剤',
    reading: 'エーイーざい',
    termZh: '引气剂',
    termEn: 'Air-entraining Agent',
    category: 'material',
    shortDefinitionZh: '在混凝土中形成许多微细、分散气泡的外加剂，用于改善和易性和抗冻融能力。',
    shortDefinitionJa: 'コンクリート中に微細で独立した気泡を導入し、ワーカビリティーや耐凍害性を改善する混和剤です。',
    shortDefinitionEn: 'An admixture that introduces small dispersed air bubbles to improve workability and freeze-thaw resistance.',
    searchKeywords: ['AE agent', 'air entrainment', '引气'],
  },
  {
    id: 'curing',
    slug: 'curing',
    termJa: '養生',
    reading: 'ようじょう',
    termZh: '养护',
    termEn: 'Curing',
    category: 'construction',
    shortDefinitionZh: '在混凝土硬化初期控制水分、温度并避免有害振动或外力，以支持强度与耐久性形成。',
    shortDefinitionJa: 'コンクリートの硬化初期に水分と温度を管理し、有害な振動や外力を避けて強度・耐久性の発現を支える作業です。',
    shortDefinitionEn: 'The control of moisture, temperature, and disturbance while concrete hardens to support strength and durability.',
    searchKeywords: ['湿潤養生', 'concrete curing', '养护'],
  },
  {
    id: 'design-strength',
    slug: 'design-strength',
    termJa: '設計基準強度',
    reading: 'せっけいきじゅんきょうど',
    termZh: '设计基准强度',
    termEn: 'Specified Design Strength',
    category: 'structure',
    shortDefinitionZh: '结构设计中规定混凝土应满足的基准抗压强度，用作构件性能判断的基础。',
    shortDefinitionJa: '構造設計で構造体コンクリートが満たすべき基準として定める圧縮強度です。',
    shortDefinitionEn: 'The specified compressive strength that structural concrete is required to satisfy for design.',
    searchKeywords: ['Fc', 'specified concrete strength', '设计强度'],
  },
  {
    id: 'bleeding',
    slug: 'bleeding',
    termJa: 'ブリーディング',
    reading: 'ブリーディング',
    termZh: '泌水',
    termEn: 'Bleeding',
    category: 'concrete',
    shortDefinitionZh: '新拌混凝土中的固体颗粒沉降时，部分水分向表面上升的现象。',
    shortDefinitionJa: 'フレッシュコンクリート中の固体粒子が沈降し、一部の水が表面へ上昇する現象です。',
    shortDefinitionEn: 'The upward movement of water in fresh concrete as solid particles settle.',
    searchKeywords: ['泌水', 'bleed water'],
  },
  {
    id: 'laitance',
    slug: 'laitance',
    termJa: 'レイタンス',
    reading: 'レイタンス',
    termZh: '浮浆层',
    termEn: 'Laitance',
    category: 'construction',
    shortDefinitionZh: '泌水携带细颗粒上升后在混凝土表面形成的薄弱层，施工缝处理时通常需要清除。',
    shortDefinitionJa: 'ブリーディング水とともに微粒子が上昇し、コンクリート表面に形成される脆弱な層です。',
    shortDefinitionEn: 'A weak surface layer of fine particles carried upward with bleed water.',
    searchKeywords: ['浮浆', 'surface laitance'],
  },
  {
    id: 'cold-joint',
    slug: 'cold-joint',
    termJa: 'コールドジョイント',
    reading: 'コールドジョイント',
    termZh: '冷缝',
    termEn: 'Cold Joint',
    category: 'construction',
    shortDefinitionZh: '前后两批混凝土未能充分一体化而形成的非预期接缝，可能影响防水和结构连续性。',
    shortDefinitionJa: '先に打ち込んだコンクリートと後続のコンクリートが十分に一体化せず生じる、意図しない継ぎ目です。',
    shortDefinitionEn: 'An unintended joint where successive concrete placements fail to integrate adequately.',
    searchKeywords: ['施工冷缝', 'cold construction joint'],
  },
  {
    id: 'carbonation',
    slug: 'carbonation',
    termJa: '中性化',
    reading: 'ちゅうせいか',
    termZh: '碳化',
    termEn: 'Concrete Carbonation',
    category: 'concrete',
    shortDefinitionZh: '硬化混凝土与空气中二氧化碳反应、碱性逐渐降低的过程，可能削弱钢筋的防锈环境。',
    shortDefinitionJa: '硬化コンクリートが空気中の二酸化炭素と反応し、アルカリ性を徐々に失う現象です。',
    shortDefinitionEn: 'The reaction of hardened concrete with atmospheric carbon dioxide, gradually reducing alkalinity.',
    searchKeywords: ['コンクリート中性化', 'carbonation depth', '混凝土碳化'],
  },
  {
    id: 'deformed-bar',
    slug: 'deformed-bar',
    termJa: '異形棒鋼',
    reading: 'いけいぼうこう',
    termZh: '带肋钢筋',
    termEn: 'Deformed Reinforcing Bar',
    category: 'structure',
    shortDefinitionZh: '表面带有节和肋、用于提高与混凝土机械咬合作用的钢筋。',
    shortDefinitionJa: '表面に節やリブを設け、コンクリートとの機械的なかみ合いを高めた鉄筋です。',
    shortDefinitionEn: 'Reinforcing steel with surface ribs that improve mechanical bond with concrete.',
    searchKeywords: ['異形鉄筋', 'rebar', 'deformed bar', '螺纹钢筋'],
  },
  {
    id: 'anchorage',
    slug: 'anchorage',
    termJa: '定着',
    reading: 'ていちゃく',
    termZh: '锚固',
    termEn: 'Reinforcement Anchorage',
    category: 'structure',
    shortDefinitionZh: '通过足够埋入长度、弯钩或其他构造，使钢筋应力可靠传递到混凝土或相邻构件。',
    shortDefinitionJa: '必要な埋込み長さやフックなどにより、鉄筋の力をコンクリートや接続部材へ確実に伝えることです。',
    shortDefinitionEn: 'The transfer of reinforcing-bar force into concrete or adjoining members through embedment or hooks.',
    searchKeywords: ['鉄筋定着', 'development length', '锚固长度'],
  },
  {
    id: 'concrete-cover',
    slug: 'concrete-cover',
    termJa: 'かぶり厚さ',
    reading: 'かぶりあつさ',
    termZh: '混凝土保护层厚度',
    termEn: 'Concrete Cover',
    category: 'structure',
    shortDefinitionZh: '钢筋外表面到混凝土表面的最短距离，关系到耐久、防火、粘结和施工。',
    shortDefinitionJa: '鉄筋表面からコンクリート表面までの最短距離で、耐久性、耐火性、付着、施工に関係します。',
    shortDefinitionEn: 'The shortest distance from reinforcement to the concrete surface, important to durability and fire resistance.',
    searchKeywords: ['cover thickness', '保护层厚度', 'かぶり'],
  },
  {
    id: 'stirrup',
    slug: 'stirrup',
    termJa: 'あばら筋',
    reading: 'あばらきん',
    termZh: '梁箍筋',
    termEn: 'Stirrup',
    category: 'structure',
    shortDefinitionZh: '围绕梁主筋配置的横向钢筋，主要参与抵抗剪力并约束主筋。',
    shortDefinitionJa: '梁の主筋を囲む横方向の鉄筋で、主にせん断力への抵抗と主筋の拘束を担います。',
    shortDefinitionEn: 'Transverse reinforcement enclosing beam bars, primarily resisting shear and restraining longitudinal bars.',
    searchKeywords: ['スターラップ', 'stirrup reinforcement', '箍筋'],
  },
  {
    id: 'hoop-reinforcement',
    slug: 'hoop-reinforcement',
    termJa: '帯筋',
    reading: 'おびきん',
    termZh: '柱箍筋',
    termEn: 'Hoop Reinforcement',
    category: 'structure',
    shortDefinitionZh: '围绕柱纵向钢筋设置的横向钢筋，用于抗剪、约束核心混凝土并固定主筋位置。',
    shortDefinitionJa: '柱の主筋を囲む横方向の鉄筋で、せん断抵抗、コンクリートの拘束、主筋位置の保持に役立ちます。',
    shortDefinitionEn: 'Transverse reinforcement around column bars that contributes to shear resistance and confinement.',
    searchKeywords: ['フープ', 'hoop', 'tie reinforcement', '柱箍筋'],
  },
  {
    id: 'creep',
    slug: 'creep',
    termJa: 'クリープ',
    reading: 'クリープ',
    termZh: '徐变',
    termEn: 'Creep',
    category: 'material',
    shortDefinitionZh: '材料在持续应力作用下，随时间逐渐增加变形的现象。',
    shortDefinitionJa: '材料に一定の応力が長時間作用すると、時間の経過とともに変形が増加する現象です。',
    shortDefinitionEn: 'The gradual increase in material deformation over time under sustained stress.',
    searchKeywords: ['creep deformation', '徐变变形'],
  },
  {
    id: 'shear-reinforcement',
    slug: 'shear-reinforcement',
    termJa: 'せん断補強筋',
    reading: 'せんだんほきょうきん',
    termZh: '抗剪钢筋',
    termEn: 'Shear Reinforcement',
    category: 'structure',
    shortDefinitionZh: '为抵抗构件中的剪力而设置的钢筋，包括梁箍筋和柱箍筋等。',
    shortDefinitionJa: '部材に生じるせん断力へ抵抗するための鉄筋で、梁のあばら筋や柱の帯筋などが含まれます。',
    shortDefinitionEn: 'Reinforcement provided to resist shear, including beam stirrups and column hoops.',
    searchKeywords: ['せん断筋', 'shear steel', '抗剪箍筋'],
  },
]
