import type { GlossaryTerm } from './types'

const baseGlossaryTerms: GlossaryTerm[] = [
  {
    id: 'floor-area-ratio',
    slug: 'floor-area-ratio',
    termJa: '容積率',
    reading: 'ようせきりつ',
    termZh: '容积率',
    termEn: 'Floor Area Ratio',
    category: 'code',
    shortDefinitionZh: '建筑物延べ面積相对于敷地面積的比例，用来控制基地上的总楼面规模。',
    shortDefinitionJa: '建築物の延べ面積の敷地面積に対する割合。敷地に建てられる総量を読む指標です。',
    shortDefinitionEn: 'The ratio of total floor area to site area, used to control the overall building volume on a site.',
    relatedCodeTopicSlug: 'floor-area-ratio',
    relatedCodeTopicLabel: '容積率',
  },
  {
    id: 'building-coverage-ratio',
    slug: 'building-coverage-ratio',
    termJa: '建蔽率',
    reading: 'けんぺいりつ',
    termZh: '建蔽率',
    termEn: 'Building Coverage Ratio',
    category: 'code',
    shortDefinitionZh: '建筑面积相对于敷地面积的比例，主要控制建筑在平面上覆盖多少土地。',
    shortDefinitionJa: '建築面積の敷地面積に対する割合。建物が地面をどれだけ覆うかを示します。',
    shortDefinitionEn: 'The ratio of building footprint area to site area, controlling how much ground the building covers.',
    relatedCodeTopicSlug: 'building-coverage-ratio',
    relatedCodeTopicLabel: '建蔽率',
  },
  {
    id: 'zoning-districts',
    slug: 'zoning-districts',
    termJa: '用途地域',
    reading: 'ようとちいき',
    termZh: '用途地域',
    termEn: 'Zoning Districts',
    category: 'planning',
    shortDefinitionZh: '按照居住、商业、工业等城市功能划分土地利用的日本都市计划制度。',
    shortDefinitionJa: '住居、商業、工業などの都市機能に応じて土地利用を区分する都市計画制度です。',
    shortDefinitionEn: 'Japanese land-use districts that organize urban areas by residential, commercial, and industrial functions.',
    relatedCodeTopicSlug: 'zoning-districts',
    relatedCodeTopicLabel: '用途地域',
  },
  {
    id: 'road-access-obligation',
    slug: 'road-access-obligation',
    termJa: '接道義務',
    reading: 'せつどうぎむ',
    termZh: '接道义务',
    termEn: 'Road Access Obligation',
    category: 'road',
    shortDefinitionZh: '建筑基地需要与法定道路保持必要连接的基本规则，关系到避难、消防和通行。',
    shortDefinitionJa: '建築物の敷地が法令上の道路に必要な形で接することを求める基本条件です。',
    shortDefinitionEn: 'A basic rule requiring a building site to connect properly to a legally recognized road.',
    relatedCodeTopicSlug: 'road-access-obligation',
    relatedCodeTopicLabel: '接道義務',
  },
  {
    id: 'road-slant-restriction',
    slug: 'road-slant-restriction',
    termJa: '道路斜線制限',
    reading: 'どうろしゃせんせいげん',
    termZh: '道路斜线限制',
    termEn: 'Road Slant Restriction',
    category: 'height',
    shortDefinitionZh: '从前面道路一侧控制建筑高度和上部形态的斜线限制。',
    shortDefinitionJa: '前面道路側から建築物の高さや上部形状を制限する斜線制限です。',
    shortDefinitionEn: 'A slant-plane height control from the road side that shapes the street-facing building envelope.',
    relatedCodeTopicSlug: 'road-slant-restriction',
    relatedCodeTopicLabel: '道路斜線制限',
  },
  {
    id: 'north-side-slant-restriction',
    slug: 'north-side-slant-restriction',
    termJa: '北側斜線制限',
    reading: 'きたがわしゃせんせいげん',
    termZh: '北侧斜线限制',
    termEn: 'North-side Slant Restriction',
    category: 'height',
    shortDefinitionZh: '从北侧邻地关系控制建筑高度，保护住宅环境、日照和天空感。',
    shortDefinitionJa: '北側隣地の日照や住環境を守るため、建築物の高さを制限する制度です。',
    shortDefinitionEn: 'A height control from the north-side boundary that protects daylight and residential conditions.',
    relatedCodeTopicSlug: 'north-side-slant-restriction',
    relatedCodeTopicLabel: '北側斜線制限',
  },
  {
    id: 'fire-prevention-district',
    slug: 'fire-prevention-district',
    termJa: '防火地域',
    reading: 'ぼうかちいき',
    termZh: '防火地域',
    termEn: 'Fire Prevention District',
    category: 'fire',
    shortDefinitionZh: '城市高火灾风险区域的防火地区指定，通常要求更高耐火性能。',
    shortDefinitionJa: '延焼リスクが高い市街地で、建築物に高い防火性能を求める地区指定です。',
    shortDefinitionEn: 'A fire-safety district designation requiring stronger fire performance in dense or high-risk urban areas.',
    relatedCodeTopicSlug: 'fire-prevention-district',
    relatedCodeTopicLabel: '防火地域',
  },
  {
    id: 'quasi-fire-prevention-district',
    slug: 'quasi-fire-prevention-district',
    termJa: '準防火地域',
    reading: 'じゅんぼうかちいき',
    termZh: '准防火地域',
    termEn: 'Quasi-fire Prevention District',
    category: 'fire',
    shortDefinitionZh: '介于一般区域和防火地域之间的防火控制区域，常见于密集市街地或防火地域周边。',
    shortDefinitionJa: '一般区域と防火地域の中間的な防火性能を求める地区指定です。',
    shortDefinitionEn: 'An intermediate fire-safety district often used around fire prevention districts or dense urban areas.',
    relatedCodeTopicSlug: 'quasi-fire-prevention-district',
    relatedCodeTopicLabel: '準防火地域',
  },
  {
    id: 'building-area',
    slug: 'building-area',
    termJa: '建築面積',
    reading: 'けんちくめんせき',
    termZh: '建筑面积',
    termEn: 'Building Area',
    category: 'area',
    shortDefinitionZh: '用于计算建蔽率的建筑占地面积，具体算入范围需按法规判断。',
    shortDefinitionJa: '建蔽率の計算に用いる建築物の面積。算入範囲は法令上の扱いを確認します。',
    shortDefinitionEn: 'The building footprint area used for coverage calculations, with legal inclusion rules to be checked.',
    relatedCodeTopicSlug: 'building-coverage-ratio',
    relatedCodeTopicLabel: '建蔽率',
  },
  {
    id: 'total-floor-area',
    slug: 'total-floor-area',
    termJa: '延べ面積',
    reading: 'のべめんせき',
    termZh: '延べ面积',
    termEn: 'Total Floor Area',
    category: 'area',
    shortDefinitionZh: '建筑各层楼面面积的合计，是理解容積率时最重要的面积概念之一。',
    shortDefinitionJa: '建築物の各階の床面積の合計。容積率を読むうえで重要な面積概念です。',
    shortDefinitionEn: 'The sum of floor areas across building stories, central to Floor Area Ratio calculations.',
    relatedCodeTopicSlug: 'floor-area-ratio',
    relatedCodeTopicLabel: '容積率',
  },
  {
    id: 'site-area',
    slug: 'site-area',
    termJa: '敷地面積',
    reading: 'しきちめんせき',
    termZh: '基地面积',
    termEn: 'Site Area',
    category: 'area',
    shortDefinitionZh: '建筑基地的面积，是容積率、建蔽率等规模判断的基础。',
    shortDefinitionJa: '建築敷地の面積。容積率や建蔽率などの規模判断の基礎になります。',
    shortDefinitionEn: 'The area of a building site, used as the base for FAR and coverage calculations.',
    relatedCodeTopicSlug: 'floor-area-ratio',
    relatedCodeTopicLabel: '容積率',
  },
  {
    id: 'front-road',
    slug: 'front-road',
    termJa: '前面道路',
    reading: 'ぜんめんどうろ',
    termZh: '前面道路',
    termEn: 'Front Road',
    category: 'road',
    shortDefinitionZh: '基地所临接的道路，常影响接道、容積率道路宽度限制和道路斜线。',
    shortDefinitionJa: '敷地が接する道路。接道、容積率、道路斜線制限に関係します。',
    shortDefinitionEn: 'The road facing or adjoining a site, relevant to access, FAR limits, and road slant controls.',
    relatedCodeTopicSlug: 'road-access-obligation',
    relatedCodeTopicLabel: '接道義務',
  },
  {
    id: 'road-width',
    slug: 'road-width',
    termJa: '道路幅員',
    reading: 'どうろふくいん',
    termZh: '道路宽度',
    termEn: 'Road Width',
    category: 'road',
    shortDefinitionZh: '道路的宽度，可能影响接道判断、容積率限制和道路斜线计算。',
    shortDefinitionJa: '道路の幅。接道、容積率制限、道路斜線制限の読み方に関係します。',
    shortDefinitionEn: 'The width of a road, relevant to access, FAR restrictions, and road slant calculations.',
    relatedCodeTopicSlug: 'floor-area-ratio',
    relatedCodeTopicLabel: '容積率',
  },
  {
    id: 'corner-lot-relaxation',
    slug: 'corner-lot-relaxation',
    termJa: '角地緩和',
    reading: 'かどちかんわ',
    termZh: '角地缓和',
    termEn: 'Corner Lot Relaxation',
    category: 'code',
    shortDefinitionZh: '在满足角地等条件时，部分建蔽率等限制可能获得放宽的概念。',
    shortDefinitionJa: '角地など一定条件を満たす場合に、建蔽率などが緩和される考え方です。',
    shortDefinitionEn: 'A relaxation concept that may apply to coverage and other controls on qualifying corner lots.',
    relatedCodeTopicSlug: 'building-coverage-ratio',
    relatedCodeTopicLabel: '建蔽率',
  },
  {
    id: 'sky-factor',
    slug: 'sky-factor',
    termJa: '天空率',
    reading: 'てんくうりつ',
    termZh: '天空率',
    termEn: 'Sky Factor',
    category: 'height',
    shortDefinitionZh: '用于评价建筑周边天空开放性的指标，常与斜线限制的替代验证相关。',
    shortDefinitionJa: '建築物周辺の天空の開放性を評価する指標。斜線制限の代替検討と関係します。',
    shortDefinitionEn: 'A measure of sky openness around a building, often used in alternative review of slant restrictions.',
    relatedCodeTopicSlug: 'road-slant-restriction',
    relatedCodeTopicLabel: '道路斜線制限',
  },
  {
    id: 'shadow-regulation',
    slug: 'shadow-regulation',
    termJa: '日影規制',
    reading: 'にちえいきせい',
    termZh: '日影规制',
    termEn: 'Shadow Regulation',
    category: 'environment',
    shortDefinitionZh: '通过一定时间和测定面评价建筑阴影影响的居住环境控制规则。',
    shortDefinitionJa: '一定時間と測定面により、建築物の影の影響を評価する住環境の規制です。',
    shortDefinitionEn: 'A rule that evaluates a building shadow over specified time periods and measurement planes.',
    relatedCodeTopicSlug: 'north-side-slant-restriction',
    relatedCodeTopicLabel: '北側斜線制限',
  },
  {
    id: 'daylighting',
    slug: 'daylighting',
    termJa: '採光',
    reading: 'さいこう',
    termZh: '采光',
    termEn: 'Daylighting',
    category: 'environment',
    shortDefinitionZh: '室内取得自然光的条件，是居室环境和开口部设计的重要概念。',
    shortDefinitionJa: '室内に自然光を取り入れる条件。居室環境や開口部設計に関わります。',
    shortDefinitionEn: 'The provision of natural light to interior spaces, important for habitable rooms and openings.',
  },
  {
    id: 'ventilation',
    slug: 'ventilation',
    termJa: '換気',
    reading: 'かんき',
    termZh: '通风',
    termEn: 'Ventilation',
    category: 'environment',
    shortDefinitionZh: '通过自然或机械方式交换室内外空气，维持卫生和舒适性的基本条件。',
    shortDefinitionJa: '自然または機械により室内外の空気を入れ替える、衛生と快適性の基本条件です。',
    shortDefinitionEn: 'The exchange of indoor and outdoor air by natural or mechanical means for health and comfort.',
  },
  {
    id: 'evacuation',
    slug: 'evacuation',
    termJa: '避難',
    reading: 'ひなん',
    termZh: '避难',
    termEn: 'Evacuation',
    category: 'fire',
    shortDefinitionZh: '火灾或灾害时人员从建筑内安全离开的行动和路径规划。',
    shortDefinitionJa: '火災や災害時に、人が建築物から安全に逃げるための行動と経路計画です。',
    shortDefinitionEn: 'The movement and route planning that allow people to leave a building safely during fire or disaster.',
    relatedCodeTopicSlug: 'road-access-obligation',
    relatedCodeTopicLabel: '接道義務',
  },
  {
    id: 'fire-resistant-building',
    slug: 'fire-resistant-building',
    termJa: '耐火建築物',
    reading: 'たいかけんちくぶつ',
    termZh: '耐火建筑物',
    termEn: 'Fire-resistant Building',
    category: 'fire',
    shortDefinitionZh: '主要结构部等具有较高耐火性能的建筑类型，常与防火地域要求相关。',
    shortDefinitionJa: '主要構造部などに高い耐火性能を持つ建築物。防火地域の要求と関係します。',
    shortDefinitionEn: 'A building with high fire-resistant performance in major structural parts and related elements.',
    relatedCodeTopicSlug: 'fire-prevention-district',
    relatedCodeTopicLabel: '防火地域',
  },
  {
    id: 'quasi-fire-resistant-building',
    slug: 'quasi-fire-resistant-building',
    termJa: '準耐火建築物',
    reading: 'じゅんたいかけんちくぶつ',
    termZh: '准耐火建筑物',
    termEn: 'Quasi-fire-resistant Building',
    category: 'fire',
    shortDefinitionZh: '耐火性能低于耐火建筑物但满足一定防火要求的建筑类型。',
    shortDefinitionJa: '耐火建築物ほどではないが、一定の防火性能を満たす建築物です。',
    shortDefinitionEn: 'A building type that meets specified fire performance below full fire-resistant construction.',
    relatedCodeTopicSlug: 'quasi-fire-prevention-district',
    relatedCodeTopicLabel: '準防火地域',
  },
  {
    id: 'fire-protective-construction',
    slug: 'fire-protective-construction',
    termJa: '防火構造',
    reading: 'ぼうかこうぞう',
    termZh: '防火构造',
    termEn: 'Fire-protective Construction',
    category: 'fire',
    shortDefinitionZh: '用于抑制火灾蔓延的构造做法，常涉及外墙、屋顶和开口部。',
    shortDefinitionJa: '延焼を抑えるための構造。外壁、屋根、開口部などに関係します。',
    shortDefinitionEn: 'Construction designed to prevent or slow fire spread, often involving walls, roofs, and openings.',
    relatedCodeTopicSlug: 'quasi-fire-prevention-district',
    relatedCodeTopicLabel: '準防火地域',
  },
  {
    id: 'major-structural-parts',
    slug: 'major-structural-parts',
    termJa: '主要構造部',
    reading: 'しゅようこうぞうぶ',
    termZh: '主要结构部',
    termEn: 'Major Structural Parts',
    category: 'building-part',
    shortDefinitionZh: '建筑中承担结构和防火判断的重要部分，如墙、柱、梁、楼板、屋顶、楼梯等。',
    shortDefinitionJa: '壁、柱、梁、床、屋根、階段など、構造と防火判断で重要になる部分です。',
    shortDefinitionEn: 'Key building parts such as walls, columns, beams, floors, roofs, and stairs used in structural and fire judgments.',
    relatedCodeTopicSlug: 'fire-prevention-district',
    relatedCodeTopicLabel: '防火地域',
  },
  {
    id: 'opening',
    slug: 'opening',
    termJa: '開口部',
    reading: 'かいこうぶ',
    termZh: '开口部',
    termEn: 'Opening',
    category: 'building-part',
    shortDefinitionZh: '墙体或外皮上的窗、门等开口，是采光、通风和防火设计的关键部位。',
    shortDefinitionJa: '窓や扉など、壁や外皮に設けられる開口。採光、換気、防火に関係します。',
    shortDefinitionEn: 'Windows, doors, and other openings in walls or envelopes, important for light, air, and fire safety.',
    relatedCodeTopicSlug: 'quasi-fire-prevention-district',
    relatedCodeTopicLabel: '準防火地域',
  },
  {
    id: 'exterior-wall',
    slug: 'exterior-wall',
    termJa: '外壁',
    reading: 'がいへき',
    termZh: '外墙',
    termEn: 'Exterior Wall',
    category: 'building-part',
    shortDefinitionZh: '建筑外部围护墙体，关系到结构、保温、防火、街道界面和立面表现。',
    shortDefinitionJa: '建築物の外側を構成する壁。構造、断熱、防火、街路景観に関係します。',
    shortDefinitionEn: 'The outer wall of a building, relevant to structure, insulation, fire safety, and facade expression.',
    relatedCodeTopicSlug: 'quasi-fire-prevention-district',
    relatedCodeTopicLabel: '準防火地域',
  },
  {
    id: 'stairs',
    slug: 'stairs',
    termJa: '階段',
    reading: 'かいだん',
    termZh: '楼梯',
    termEn: 'Stairs',
    category: 'building-part',
    shortDefinitionZh: '连接不同楼层的竖向交通构件，也是避难路径设计的重要组成。',
    shortDefinitionJa: '階をつなぐ垂直動線。避難経路の計画でも重要な要素です。',
    shortDefinitionEn: 'Vertical circulation elements connecting floors, also important in evacuation planning.',
  },
  {
    id: 'habitable-room',
    slug: 'habitable-room',
    termJa: '居室',
    reading: 'きょしつ',
    termZh: '居室',
    termEn: 'Habitable Room',
    category: 'use',
    shortDefinitionZh: '供居住、工作、学习等持续使用的房间，常与采光、通风和卫生条件相关。',
    shortDefinitionJa: '居住、作業、学習など継続的に使用される室。採光、換気、衛生条件に関係します。',
    shortDefinitionEn: 'A room used continuously for living, working, study, or similar activities, tied to light and ventilation rules.',
  },
  {
    id: 'apartment-house',
    slug: 'apartment-house',
    termJa: '共同住宅',
    reading: 'きょうどうじゅうたく',
    termZh: '共同住宅',
    termEn: 'Apartment House',
    category: 'use',
    shortDefinitionZh: '多个住户共同使用同一建筑的住宅类型，常与用途地域、避难、防火和共用部分相关。',
    shortDefinitionJa: '複数の住戸が一つの建築物に入る住宅形式。用途地域、避難、防火、共用部に関係します。',
    shortDefinitionEn: 'A residential building containing multiple dwelling units, relevant to zoning, evacuation, fire safety, and shared areas.',
    relatedCodeTopicSlug: 'zoning-districts',
    relatedCodeTopicLabel: '用途地域',
  },
  {
    id: 'commercial-district',
    slug: 'commercial-district',
    termJa: '商業地域',
    reading: 'しょうぎょうちいき',
    termZh: '商业地域',
    termEn: 'Commercial District',
    category: 'planning',
    shortDefinitionZh: '以商业、办公和高密度城市活动为主的用途地域之一。',
    shortDefinitionJa: '商業、業務、高密度な都市活動を受け止める用途地域の一つです。',
    shortDefinitionEn: 'A zoning district intended for commerce, offices, and dense urban activity.',
    relatedCodeTopicSlug: 'zoning-districts',
    relatedCodeTopicLabel: '用途地域',
  },
  {
    id: 'category-one-low-rise-residential-district',
    slug: 'category-one-low-rise-residential-district',
    termJa: '第一種低層住居専用地域',
    reading: 'だいいっしゅていそうじゅうきょせんようちいき',
    termZh: '第一种低层住居专用地域',
    termEn: 'Category I Low-rise Exclusive Residential District',
    category: 'planning',
    shortDefinitionZh: '强烈保护低层住宅环境的用途地域，常与高度、北侧斜线和低密度住宅相关。',
    shortDefinitionJa: '低層住宅の良好な住環境を守る性格が強い用途地域です。',
    shortDefinitionEn: 'A zoning district strongly focused on protecting low-rise residential environments.',
    relatedCodeTopicSlug: 'zoning-districts',
    relatedCodeTopicLabel: '用途地域',
  },
]

const searchKeywordsByTermId: Record<string, string[]> = {
  'floor-area-ratio': ['FAR', 'Floor Area Ratio', 'ようせきりつ', '容积率', '容積率', '容積', 'total floor area ratio'],
  'building-coverage-ratio': ['BCR', 'Building Coverage Ratio', '建ぺい率', '建蔽率', 'けんぺいりつ', 'coverage ratio', 'building footprint'],
  'zoning-districts': ['zoning', 'land use zone', 'zoning districts', 'ようとちいき', '用途地域', '土地利用', 'use district'],
  'road-access-obligation': ['接道义务', '接道義務', 'せつどうぎむ', 'road access', '2m road access', 'site access', 'Article 43'],
  'road-slant-restriction': ['道路斜线限制', '道路斜線制限', 'どうろしゃせんせいげん', 'road slant', 'road setback', 'height control', '道路斜線'],
  'north-side-slant-restriction': ['北侧斜线限制', '北側斜線制限', 'きたがわしゃせんせいげん', 'north side slant', 'north-side height control', '北側斜線'],
  'fire-prevention-district': ['防火地域', 'ぼうかちいき', 'fire district', 'fire prevention zone', 'fire safety district'],
  'quasi-fire-prevention-district': ['準防火地域', '准防火地域', 'じゅんぼうかちいき', 'quasi fire prevention', 'semi fire prevention district'],
  'building-area': ['建築面積', '建筑面积', 'けんちくめんせき', 'building footprint', 'projected area'],
  'total-floor-area': ['延べ面積', '延べ面积', 'のべめんせき', 'total floor area', 'gross floor area', 'GFA'],
  'site-area': ['敷地面積', '基地面积', 'しきちめんせき', 'site area', 'lot area', 'plot area'],
  'front-road': ['前面道路', 'ぜんめんどうろ', 'front road', 'adjacent road', 'frontage road'],
  'road-width': ['道路幅員', '道路宽度', 'どうろふくいん', 'road width', 'street width', 'width of road'],
  'corner-lot-relaxation': ['角地緩和', '角地缓和', 'かどちかんわ', 'corner lot relaxation', 'corner lot', 'relaxation'],
  'sky-factor': ['天空率', 'てんくうりつ', 'sky factor', 'sky exposure', 'alternative slant review'],
  'shadow-regulation': ['日影規制', '日影规制', 'にちえいきせい', 'shadow regulation', 'sun shadow control', '日影'],
  'daylighting': ['採光', '采光', 'さいこう', 'daylighting', 'natural light', 'light opening'],
  'ventilation': ['換気', '通风', 'かんき', 'ventilation', 'air exchange', 'natural ventilation'],
  'evacuation': ['避難', '避难', 'ひなん', 'evacuation', 'escape route', 'egress'],
  'fire-resistant-building': ['耐火建築物', '耐火建筑物', 'たいかけんちくぶつ', 'fire-resistant building', 'fireproof building'],
  'quasi-fire-resistant-building': ['準耐火建築物', '准耐火建筑物', 'じゅんたいかけんちくぶつ', 'quasi fire-resistant building', 'semi fire-resistant building'],
  'fire-protective-construction': ['防火構造', '防火构造', 'ぼうかこうぞう', 'fire-protective construction', 'fire protective structure'],
  'major-structural-parts': ['主要構造部', '主要结构部', 'しゅようこうぞうぶ', 'major structural parts', 'principal structural parts'],
  'opening': ['開口部', '开口部', 'かいこうぶ', 'opening', 'window opening', 'door opening'],
  'exterior-wall': ['外壁', '外墙', 'がいへき', 'exterior wall', 'external wall', 'outer wall'],
  'stairs': ['階段', '楼梯', 'かいだん', 'stairs', 'staircase', 'stair'],
  'habitable-room': ['居室', 'きょしつ', 'habitable room', 'occupied room', 'living room'],
  'apartment-house': ['共同住宅', 'きょうどうじゅうたく', 'apartment house', 'multi-family housing', 'collective housing'],
  'commercial-district': ['商業地域', '商业地域', 'しょうぎょうちいき', 'commercial district', 'commercial zone'],
  'category-one-low-rise-residential-district': ['第一種低層住居専用地域', '第一种低层住居专用地域', 'だいいっしゅていそうじゅうきょせんようちいき', 'category one low-rise residential district', 'low-rise residential zone'],
}

export const glossaryTerms: GlossaryTerm[] = baseGlossaryTerms.map(term => ({
  ...term,
  searchKeywords: searchKeywordsByTermId[term.id] || [],
}))
