-- Graduation disaster memorial batch 002: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=disaster-memorial-002).
-- Scope: 0 new architects, 1 buildings, 1 images,
-- 1 profiles, 1 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation disaster memorial batch 002 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', '隈研吾', 'Kengo Kuma', '隈研吾', NULL, false);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('c63e9862-b1e9-554c-8765-5fff3f65d408'::uuid, 'CASE-015', 'minamisanriku-311-memorial', '南三陆311纪念馆', 'Minamisanriku 311 Memorial', '南三陸311メモリアル', '51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', 2022, 'published', '南三陆', '日本', 'JP', 'cultural', 'https://kkaa.co.jp/en/project/minamisanriku-311-memorial/');

CREATE TEMP TABLE reused_building_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE) ON COMMIT DROP;


CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('fc630fa4-832d-5edc-b5e8-2772697b14b1'::uuid, 'c63e9862-b1e9-554c-8765-5fff3f65d408'::uuid, 'minamisanriku-311-memorial', 'CASE-015', '/images/graduation/cases/case-015-minamisanriku-311-memorial.jpg', 'Yasu', 'Wikimedia Commons', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Minamisanriku_311_Memorial.jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL, building_slug text NOT NULL, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-015', 'c63e9862-b1e9-554c-8765-5fff3f65d408'::uuid, 'minamisanriku-311-memorial', '灾后公共设施把记忆、避难、交流和地区复兴放在同一空间框架内。', NULL, 'Minamisanriku 311 Memorial is a reference case for reading disaster prevention, Design topic: 复兴, publicfacility, Design topic: 平灾结合. It can inform thesis thinking about mixed programs, operation, and place-making.', '震災の記憶、学習、地域の再出発を公共施設として受け止める事例。防災を非常時だけでなく、日常の理解へつなげる参考になる。', ARRAY['防灾', '复兴', '公共设施', '平灾结合', '避难']::text[], '{}'::text[], ARRAY['disaster prevention', 'Design topic: 复兴', 'publicfacility', 'Design topic: 平灾结合', 'evacuation']::text[], ARRAY['防災', '復興', '公共施設', '平時利用と災害対応', '避難']::text[], NULL, NULL, 'https://kkaa.co.jp/en/project/minamisanriku-311-memorial/', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('c63e9862-b1e9-554c-8765-5fff3f65d408'::uuid, 'minamisanriku-311-memorial', 'museum', true, 1.000, 'https://kkaa.co.jp/en/project/minamisanriku-311-memorial/', 'Kengo Kuma and Associates identifies the completed 2022 Miyagi project as Minamisanriku 311 Memorial, a 1433 square metre two-storey facility designed as the culmination of the town reconstruction plan. The official description states that disaster memories and artworks are displayed inside, supporting the museum function without inventing a separate memorial taxonomy.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  reused_building_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  invalid_profile_buildings integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 1
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 0
    OR (SELECT count(*) FROM building_seed) <> 1
    OR (SELECT count(*) FROM reused_building_seed) <> 0
    OR (SELECT count(*) FROM image_seed) <> 1
    OR (SELECT count(*) FROM profile_seed) <> 1
    OR (SELECT count(*) FROM assignment_seed) <> 1 THEN
    RAISE EXCEPTION 'Graduation disaster memorial batch 002 seed count mismatch';
  END IF;

  SELECT count(*) INTO reused_building_matches
  FROM reused_building_seed seed JOIN public.buildings target USING (id, slug);
  IF reused_building_matches <> 0 THEN
    RAISE EXCEPTION 'Reused building UUID/slug pairs drifted: matched %', reused_building_matches;
  END IF;

  SELECT count(*) INTO invalid_profile_buildings
  FROM profile_seed profile
  LEFT JOIN building_seed created ON created.id = profile.building_id AND created.slug = profile.building_slug
  LEFT JOIN reused_building_seed reused ON reused.id = profile.building_id AND reused.slug = profile.building_slug
  WHERE created.id IS NULL AND reused.id IS NULL;
  IF invalid_profile_buildings <> 0 THEN
    RAISE EXCEPTION 'Profile seed references % unreviewed canonical buildings', invalid_profile_buildings;
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 1 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['museum']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['cultural']::text[]);
  IF required_function_matches <> 1
    OR required_type_matches <> 1 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation disaster memorial batch 002 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 0
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 1
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 1
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 1
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 1
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 1
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 1 THEN
    RAISE EXCEPTION 'Graduation disaster memorial batch 002 post-write verification failed';
  END IF;
END $$;

COMMIT;
