-- Graduation public space batch 001: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=public-space-001).
-- Scope: 3 new architects, 4 buildings, 4 images,
-- 4 profiles, 5 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation public space batch 001 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('7b4d4634-ff08-5fed-a9ea-45c289384608'::uuid, 'taisei-design-nikken-sekkei', '大成设计＋日建设计', 'TAISEI DESIGN + Nikken Sekkei', '大成建設設計本部＋日建設計', 'https://www.mitsuifudosan.co.jp/english/corporate/news/2020/0623/', true),
  ('4a1fdf1b-ed02-45f6-9b9c-95ae623972df'::uuid, 'mvrdv', 'MVRDV', 'MVRDV', 'MVRDV', NULL, false),
  ('6258c77f-1ef7-57e3-8917-22561599ae74'::uuid, 'field-operations-dsr-piet-oudolf', 'Field Operations＋Diller Scofidio + Renfro＋Piet Oudolf', 'Field Operations + Diller Scofidio + Renfro + Piet Oudolf', 'Field Operations＋Diller Scofidio + Renfro＋Piet Oudolf', 'https://www.fieldoperations.net/project/high-line', true),
  ('c77e7b8f-52ab-531a-ab3f-ea79257ccf06'::uuid, 'big-topotek1-superflex', 'BIG＋Topotek 1＋Superflex', 'BIG + Topotek 1 + Superflex', 'BIG＋Topotek 1＋Superflex', 'https://big.dk/projects/superkilen-1621', true);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('ecb4c07e-f79f-5cf2-9caf-634daf04e4fd'::uuid, 'CASE-050', 'hisaya-odori-park', '久屋大通公园', 'Hisaya-odori Park', '久屋大通公園', '7b4d4634-ff08-5fed-a9ea-45c289384608'::uuid, 'taisei-design-nikken-sekkei', 2020, 'published', '名古屋', '日本', 'JP', 'public-space', 'https://www.mitsuifudosan.co.jp/english/corporate/news/2020/0623/'),
  ('8c31e437-334d-5827-ad79-f7e033f7007e'::uuid, 'CASE-056', 'tainan-spring', '台南河乐广场', 'Tainan Spring', '台南スプリング', '4a1fdf1b-ed02-45f6-9b9c-95ae623972df'::uuid, 'mvrdv', 2020, 'published', '台南', '台湾', 'TW', 'public-space', 'https://www.mvrdv.com/projects/272/tainan-axis'),
  ('391ace91-3a5b-50be-9901-f93c94908241'::uuid, 'CASE-110', 'the-high-line', '纽约高线公园', 'The High Line', 'ハイライン', '6258c77f-1ef7-57e3-8917-22561599ae74'::uuid, 'field-operations-dsr-piet-oudolf', 2009, 'published', '纽约', '美国', 'US', 'public-space', 'https://www.fieldoperations.net/project/high-line'),
  ('0a9fb5da-a1ee-59a4-812a-1167e5dca6cd'::uuid, 'CASE-111', 'superkilen', 'Superkilen 多元文化公园', 'Superkilen', 'スーパーキーレン', 'c77e7b8f-52ab-531a-ab3f-ea79257ccf06'::uuid, 'big-topotek1-superflex', 2012, 'published', '哥本哈根', '丹麦', 'DK', 'public-space', 'https://big.dk/projects/superkilen-1621');

CREATE TEMP TABLE reused_building_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE) ON COMMIT DROP;


CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('11f78fb4-75af-5ead-b872-d89bea246e17'::uuid, 'ecb4c07e-f79f-5cf2-9caf-634daf04e4fd'::uuid, 'hisaya-odori-park', 'CASE-050', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Media_Hiroba_of_Hisaya-odori_Park_and_Nagoya_TV_Tower_-_2.jpg', 'KKPCW', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Media_Hiroba_of_Hisaya-odori_Park_and_Nagoya_TV_Tower_-_2.jpg', 'exterior', true),
  ('8cc50323-2214-5e4e-b023-914703553849'::uuid, '8c31e437-334d-5827-ad79-f7e033f7007e'::uuid, 'tainan-spring', 'CASE-056', '/images/graduation/cases/case-056-tainan-spring.jpg', 'Pbdragonwang', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:%E8%87%BA%E5%8D%97%E6%B2%B3%E6%A8%82%E5%BB%A3%E5%A0%B4.jpg', 'exterior', true),
  ('505bb7d4-90a9-5805-9f28-7844cd7d1606'::uuid, '391ace91-3a5b-50be-9901-f93c94908241'::uuid, 'the-high-line', 'CASE-110', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/High_Line_20th_Street_looking_downtown.jpg', 'Beyond My Ken', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:High_Line_20th_Street_looking_downtown.jpg', 'exterior', true),
  ('9381f97a-cb7f-527a-a9f3-74aa26945a6a'::uuid, '0a9fb5da-a1ee-59a4-812a-1167e5dca6cd'::uuid, 'superkilen', 'CASE-111', '/images/graduation/cases/case-111-superkilen.jpg', 'Emily', 'Wikimedia Commons', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Superkilen_hill-top_view.jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL, building_slug text NOT NULL, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-050', 'ecb4c07e-f79f-5cf2-9caf-634daf04e4fd'::uuid, 'hisaya-odori-park', '久屋大通公园再整备把线性公园、店铺和活动场连接，形成城市中心的日常公共轴。', NULL, 'Hisaya-odori Park is a reference case for reading Design topic: 线性park, Design topic: 商业复合, urbancenter, Design topic: 步行. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Hisaya-odori Park」は、線性公園・商業複合・都市センター・歩行の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['线性公园', '商业复合', '城市中心', '步行', '活动']::text[], '{}'::text[], ARRAY['Design topic: 线性park', 'Design topic: 商业复合', 'urbancenter', 'Design topic: 步行', 'activity']::text[], ARRAY['線形公園', '商業複合', '都心', '歩行', '活動']::text[], NULL, NULL, 'https://rhp.nagoya/', 'published'),
  ('CASE-056', '8c31e437-334d-5827-ad79-f7e033f7007e'::uuid, 'tainan-spring', '旧购物中心拆除后转化为城市水景公园，重新连接城市、记忆和可停留公共空间。', NULL, 'Tainan Spring is a reference case for reading Design topic: 旧商业体, water landscape, park, urbanrenewal. It can inform thesis thinking about mixed programs, operation, and place-making.', '旧商業施設の跡地を、水辺と公園の公共空間へ変えた都市更新。雨水、涼しさ、滞在を街の中心に戻す事例として読める。', ARRAY['旧商业体', '水景', '公园', '城市更新', '慢行']::text[], '{}'::text[], ARRAY['Design topic: 旧商业体', 'water landscape', 'park', 'urbanrenewal', 'Design topic: 慢行']::text[], ARRAY['水辺', '公園', '都市更新', '雨水', '公共空間']::text[], NULL, NULL, 'https://www.mvrdv.com/projects/272/tainan-spring', 'published'),
  ('CASE-110', '391ace91-3a5b-50be-9901-f93c94908241'::uuid, 'the-high-line', '废弃高架货运线被转化为线形公园和城市步行体验。', NULL, 'A former elevated freight line transformed into a linear park and urban walking experience.', '使われなくなった高架鉄道を、線形公園、歩行、休憩、都市眺望へ転換した事例。細長い公共空間の運営を考えられる。', ARRAY['线形公园', '高架', '步行', '都市更新', '休憩']::text[], '{}'::text[], ARRAY['linear park', 'elevated infrastructure', 'walking', 'urban renewal', 'rest']::text[], ARRAY['線形公園', '高架', '歩行', '都市更新', '休憩']::text[], NULL, NULL, 'https://www.fieldoperations.net/project/high-line', 'published'),
  ('CASE-111', '0a9fb5da-a1ee-59a4-812a-1167e5dca6cd'::uuid, 'superkilen', '多国籍な都市家具と色面で線形公園をつくり、移民地区の公共空間を可視化した事例。', NULL, 'Reference case for Superkilen: useful for comparing public program, urban interface, operation, and spatial experience.', '多国籍な都市家具と色面で線形公園をつくり、移民地区の公共空間を可視化した事例。', ARRAY['線形公園', '多文化', '都市家具', '歩行', '公共空間']::text[], '{}'::text[], ARRAY['線形公園', '多文化', '都市家具', '歩行', '公共空間']::text[], ARRAY['線形公園', '多文化', '都市家具', '歩行', '公共空間']::text[], NULL, NULL, 'https://big.dk/projects/superkilen-1621', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('ecb4c07e-f79f-5cf2-9caf-634daf04e4fd'::uuid, 'hisaya-odori-park', 'public-space', true, 1.000, 'https://www.mitsuifudosan.co.jp/english/corporate/news/2020/0623/', 'Nagoya City confirms the north and TV Tower areas reopened in 2020 as an integrated park-and-shops Park-PFI project. Mitsui Fudosan identifies Nikken Sekkei and Taisei Corporation for park design, Taisei for architectural design, and Iwama Garden Create for landscaping and planting.', '2026-07-12T00:00:00Z'::timestamptz),
  ('ecb4c07e-f79f-5cf2-9caf-634daf04e4fd'::uuid, 'hisaya-odori-park', 'mixed-use', false, 1.000, 'https://www.mitsuifudosan.co.jp/english/corporate/news/2020/0623/', 'Nagoya City confirms the north and TV Tower areas reopened in 2020 as an integrated park-and-shops Park-PFI project. Mitsui Fudosan identifies Nikken Sekkei and Taisei Corporation for park design, Taisei for architectural design, and Iwama Garden Create for landscaping and planting.', '2026-07-12T00:00:00Z'::timestamptz),
  ('8c31e437-334d-5827-ad79-f7e033f7007e'::uuid, 'tainan-spring', 'public-space', true, 1.000, 'https://www.mvrdv.com/projects/272/tainan-axis', 'MVRDV records a realised 2016–2020 public-space project in Tainan commissioned by the city government. The project transformed the former China-Town Mall basement into a sunken plaza and urban pool while retaining concrete fragments of the former structure.', '2026-07-12T00:00:00Z'::timestamptz),
  ('391ace91-3a5b-50be-9901-f93c94908241'::uuid, 'the-high-line', 'public-space', true, 1.000, 'https://www.fieldoperations.net/project/high-line', 'NYC Parks identifies James Corner Field Operations and Diller Scofidio + Renfro as lead design firms and Piet Oudolf as planting adviser. Field Operations records the first section opening in June 2009 and the continuing phased public-park project.', '2026-07-12T00:00:00Z'::timestamptz),
  ('0a9fb5da-a1ee-59a4-812a-1167e5dca6cd'::uuid, 'superkilen', 'public-space', true, 1.000, 'https://big.dk/projects/superkilen-1621', 'Copenhagen Municipality records Superkilen as a public park established in 2012 by BIG, Superflex and Topotek1. BIG identifies Topotek 1 and Superflex as project collaborators; the municipality describes the Red, Black and Green public-space sections.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  reused_building_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  invalid_profile_buildings integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 4
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 3
    OR (SELECT count(*) FROM building_seed) <> 4
    OR (SELECT count(*) FROM reused_building_seed) <> 0
    OR (SELECT count(*) FROM image_seed) <> 4
    OR (SELECT count(*) FROM profile_seed) <> 4
    OR (SELECT count(*) FROM assignment_seed) <> 5 THEN
    RAISE EXCEPTION 'Graduation public space batch 001 seed count mismatch';
  END IF;

  SELECT count(*) INTO reused_building_matches
  FROM reused_building_seed seed JOIN public.buildings target USING (id, slug);
  IF reused_building_matches <> 0 THEN
    RAISE EXCEPTION 'Reused building UUID/slug pairs drifted: matched %', reused_building_matches;
  END IF;

  SELECT count(*) INTO invalid_profile_buildings
  FROM profile_seed profile
  LEFT JOIN building_seed created ON created.id = profile.building_id AND created.slug = profile.building_slug
  LEFT JOIN reused_building_seed reused ON reused.id = profile.building_id AND reused.slug = profile.building_slug
  WHERE created.id IS NULL AND reused.id IS NULL;
  IF invalid_profile_buildings <> 0 THEN
    RAISE EXCEPTION 'Profile seed references % unreviewed canonical buildings', invalid_profile_buildings;
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 1 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['public-space', 'mixed-use']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['public-space']::text[]);
  IF required_function_matches <> 2
    OR required_type_matches <> 1 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation public space batch 001 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 3
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 4
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 4
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 4
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 5
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 4
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 4 THEN
    RAISE EXCEPTION 'Graduation public space batch 001 post-write verification failed';
  END IF;
END $$;

COMMIT;
