-- Graduation 3331 Arts Chiyoda batch 011: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=3331-arts-chiyoda-011).
-- Scope: 1 new architects, 1 buildings, 1 images,
-- 1 profiles, 1 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation 3331 Arts Chiyoda batch 011 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('0a252441-1979-5f14-a374-2f47ec8bfdec'::uuid, 'shinya-sato-mejiro-studio', '佐藤慎也＋目白工作室', 'Shinya Sato + Mejiro Studio', '佐藤慎也＋メジロスタジオ', 'https://www.3331.jp/schedule/000361.html', true);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('d5f896a2-53a8-5388-8d91-c31621248418'::uuid, 'CASE-005', '3331-arts-chiyoda', '3331 Arts Chiyoda', '3331 Arts Chiyoda', '3331 Arts Chiyoda', '0a252441-1979-5f14-a374-2f47ec8bfdec'::uuid, 'shinya-sato-mejiro-studio', 2010, 'published', '东京', '日本', 'JP', 'cultural', 'https://www.3331.jp/en/about/');

CREATE TEMP TABLE reused_building_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE) ON COMMIT DROP;


CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('0756b422-e9ef-5eca-bc3a-761e3ff48f61'::uuid, 'd5f896a2-53a8-5388-8d91-c31621248418'::uuid, '3331-arts-chiyoda', 'CASE-005', '/images/graduation/cases/case-005-3331-arts-chiyoda.jpg', 'Ootahara', 'Wikimedia Commons', 'CC0', 'https://commons.wikimedia.org/wiki/File:3331_Arts_Chiyoda.JPG', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL, building_slug text NOT NULL, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-005', 'd5f896a2-53a8-5388-8d91-c31621248418'::uuid, '3331-arts-chiyoda', '由旧学校改造为艺术、展览和社区活动复合空间，保留教育建筑记忆；该艺术中心已于 2023 年闭馆，本案例按历史项目研究。', NULL, '3331 Arts Chiyoda reused a former school for art, exhibitions, making and community activity. The art center closed in 2023 and is treated here as a historical reuse case.', '旧学校の教室や廊下を展示、制作、市民活動へ転用した事例。アートセンターは2023年に閉館しており、既存建物の記憶と地域への開き方を歴史的事例として読む。', ARRAY['废校', '艺术', '社区', '再利用', '创作']::text[], '{}'::text[], ARRAY['Design topic: 废校', 'art', 'community', 'reuse', 'creative production']::text[], ARRAY['廃校', 'アート', 'コミュニティ', '再利用', '創作']::text[], NULL, NULL, 'https://www.3331.jp/en/', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('d5f896a2-53a8-5388-8d91-c31621248418'::uuid, '3331-arts-chiyoda', 'art-center', true, 1.000, 'https://www.3331.jp/en/about/', '3331 identifies the facility as an independent art center created by renovating the former Chiyoda City Rensei Junior High School and operating from 2010 until 2023. The official 3331 Architectural Document states that Shinya Sato and Mejiro Studio were responsible for the renovation design. Galleries, studios, creative offices, workshops, community areas, a cafe and a shop form the program of one art center; they do not make the project a museum or generic mixed-use complex.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  reused_building_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  invalid_profile_buildings integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 1
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 1
    OR (SELECT count(*) FROM building_seed) <> 1
    OR (SELECT count(*) FROM reused_building_seed) <> 0
    OR (SELECT count(*) FROM image_seed) <> 1
    OR (SELECT count(*) FROM profile_seed) <> 1
    OR (SELECT count(*) FROM assignment_seed) <> 1 THEN
    RAISE EXCEPTION 'Graduation 3331 Arts Chiyoda batch 011 seed count mismatch';
  END IF;

  SELECT count(*) INTO reused_building_matches
  FROM reused_building_seed seed JOIN public.buildings target USING (id, slug);
  IF reused_building_matches <> 0 THEN
    RAISE EXCEPTION 'Reused building UUID/slug pairs drifted: matched %', reused_building_matches;
  END IF;

  SELECT count(*) INTO invalid_profile_buildings
  FROM profile_seed profile
  LEFT JOIN building_seed created ON created.id = profile.building_id AND created.slug = profile.building_slug
  LEFT JOIN reused_building_seed reused ON reused.id = profile.building_id AND reused.slug = profile.building_slug
  WHERE created.id IS NULL AND reused.id IS NULL;
  IF invalid_profile_buildings <> 0 THEN
    RAISE EXCEPTION 'Profile seed references % unreviewed canonical buildings', invalid_profile_buildings;
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 0 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['art-center']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['cultural']::text[]);
  IF required_function_matches <> 1
    OR required_type_matches <> 1 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation 3331 Arts Chiyoda batch 011 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 1
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 1
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 1
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 1
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 1
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 1
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 1 THEN
    RAISE EXCEPTION 'Graduation 3331 Arts Chiyoda batch 011 post-write verification failed';
  END IF;
END $$;

COMMIT;
