-- Graduation retail mixed-use batch 002: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=retail-mixed-use-002).
-- Scope: 1 new architects, 2 buildings, 2 images,
-- 2 profiles, 5 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation retail mixed-use batch 002 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('c358fc57-68cd-5715-8a3c-b5732065e727'::uuid, 'klein-dytham-architecture', 'Klein Dytham architecture', 'Klein Dytham architecture', 'クライン・ダイサム・アーキテクツ', 'https://www.klein-dytham.com/', true),
  ('4a1fdf1b-ed02-45f6-9b9c-95ae623972df'::uuid, 'mvrdv', 'MVRDV', 'MVRDV', 'MVRDV', NULL, false);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('c033bd48-f416-5c0f-a026-36ac1e0b9a60'::uuid, 'CASE-074', 'daikanyama-t-site', '代官山 T-SITE', 'Daikanyama T-SITE', '代官山 T-SITE', 'c358fc57-68cd-5715-8a3c-b5732065e727'::uuid, 'klein-dytham-architecture', 2011, 'published', '东京', '日本', 'JP', 'mixed-use', 'https://www.klein-dytham.com/daikanyama-t-site'),
  ('813079df-4752-5a8f-b3cd-b16e07233cb5'::uuid, 'CASE-116', 'markthal-rotterdam', '鹿特丹市场大厅', 'Markthal Rotterdam', 'ロッテルダム・マルクトハル', '4a1fdf1b-ed02-45f6-9b9c-95ae623972df'::uuid, 'mvrdv', 2014, 'published', '鹿特丹', '荷兰', 'NL', 'mixed-use', 'https://www.mvrdv.com/projects/115/markthal');

CREATE TEMP TABLE reused_building_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE) ON COMMIT DROP;


CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('a922c9cd-87d6-5187-a64f-c03b5aa21647'::uuid, 'c033bd48-f416-5c0f-a026-36ac1e0b9a60'::uuid, 'daikanyama-t-site', 'CASE-074', '/images/graduation/cases/case-074-daikanyama-t-site.jpg', 'Jonathan Lin', 'Wikimedia Commons', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Daikanyama_T-SITE_2016-04-04.jpg', 'exterior', true),
  ('f7a58c75-b3a3-5eec-86aa-0286701b9d7c'::uuid, '813079df-4752-5a8f-b3cd-b16e07233cb5'::uuid, 'markthal-rotterdam', 'CASE-116', '/images/graduation/cases/case-116-markthal-rotterdam.jpg', 'Michielverbeek', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Rotterdam,_het_Potlood_door_de_Markthallen_heen_foto5_2016-02-28_10.46.jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL, building_slug text NOT NULL, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-074', 'c033bd48-f416-5c0f-a026-36ac1e0b9a60'::uuid, 'daikanyama-t-site', '书店、咖啡、影音和庭院被组织成低层文化街区，提供消费之外的长时间停留体验。', NULL, 'Daikanyama T-SITE is a reference case for reading bookstore, cultural complex, cafe, Design topic: 低层neighborhood. It can inform thesis thinking about mixed programs, operation, and place-making.', '「Daikanyama T-SITE」は、書店・文化複合・カフェ・低層街区の関係を読み取る参考事例。用途の複合、運営、居場所のつくり方を卒業設計に転用して考えられる。', ARRAY['书店', '文化复合', '咖啡', '低层街区', '第三空间']::text[], '{}'::text[], ARRAY['bookstore', 'cultural complex', 'cafe', 'Design topic: 低层neighborhood', 'third place']::text[], ARRAY['書店', '文化複合', 'カフェ', '低層街区', '第三空間']::text[], NULL, NULL, 'https://www.klein-dytham.com/daikanyama-t-site', 'published'),
  ('CASE-116', '813079df-4752-5a8f-b3cd-b16e07233cb5'::uuid, 'markthal-rotterdam', '市場、住宅、観光、都市広場を大きなアーチの中にまとめた事例。日常の食と都市の賑わいを扱える。', NULL, 'Reference case for Markthal Rotterdam: useful for comparing public program, urban interface, operation, and spatial experience.', '市場、住宅、観光、都市広場を大きなアーチの中にまとめた事例。日常の食と都市の賑わいを扱える。', ARRAY['市場', '大屋根', '食文化', '都市広場', '複合用途']::text[], '{}'::text[], ARRAY['市場', '大屋根', '食文化', '都市広場', '複合用途']::text[], ARRAY['市場', '大屋根', '食文化', '都市広場', '複合用途']::text[], NULL, NULL, 'https://www.mvrdv.com/projects/115/markthal', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('c033bd48-f416-5c0f-a026-36ac1e0b9a60'::uuid, 'daikanyama-t-site', 'retail', true, 1.000, 'https://www.klein-dytham.com/daikanyama-t-site', 'Klein Dytham architecture identifies Daikanyama T-SITE as its project in Daikanyama, Shibuya-ku, Tokyo and lists the principal use as retail and apartments. The official project page states that the campus-like Tsutaya complex opened to the public in December 2011 and credits architecture and interior design to Klein Dytham architecture.', '2026-07-12T00:00:00Z'::timestamptz),
  ('c033bd48-f416-5c0f-a026-36ac1e0b9a60'::uuid, 'daikanyama-t-site', 'mixed-use', false, 1.000, 'https://www.klein-dytham.com/daikanyama-t-site', 'Klein Dytham architecture identifies Daikanyama T-SITE as its project in Daikanyama, Shibuya-ku, Tokyo and lists the principal use as retail and apartments. The official project page states that the campus-like Tsutaya complex opened to the public in December 2011 and credits architecture and interior design to Klein Dytham architecture.', '2026-07-12T00:00:00Z'::timestamptz),
  ('813079df-4752-5a8f-b3cd-b16e07233cb5'::uuid, 'markthal-rotterdam', 'retail', true, 1.000, 'https://www.mvrdv.com/projects/115/markthal', 'MVRDV identifies Markthal as a realised Rotterdam project completed in 2014, combining food, leisure, living and parking. The official project page lists retail and residential programs and describes the central market hall as a covered public square beneath the apartment arch.', '2026-07-12T00:00:00Z'::timestamptz),
  ('813079df-4752-5a8f-b3cd-b16e07233cb5'::uuid, 'markthal-rotterdam', 'mixed-use', false, 1.000, 'https://www.mvrdv.com/projects/115/markthal', 'MVRDV identifies Markthal as a realised Rotterdam project completed in 2014, combining food, leisure, living and parking. The official project page lists retail and residential programs and describes the central market hall as a covered public square beneath the apartment arch.', '2026-07-12T00:00:00Z'::timestamptz),
  ('813079df-4752-5a8f-b3cd-b16e07233cb5'::uuid, 'markthal-rotterdam', 'public-space', false, 1.000, 'https://www.mvrdv.com/projects/115/markthal', 'MVRDV identifies Markthal as a realised Rotterdam project completed in 2014, combining food, leisure, living and parking. The official project page lists retail and residential programs and describes the central market hall as a covered public square beneath the apartment arch.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  reused_building_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  invalid_profile_buildings integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 2
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 1
    OR (SELECT count(*) FROM building_seed) <> 2
    OR (SELECT count(*) FROM reused_building_seed) <> 0
    OR (SELECT count(*) FROM image_seed) <> 2
    OR (SELECT count(*) FROM profile_seed) <> 2
    OR (SELECT count(*) FROM assignment_seed) <> 5 THEN
    RAISE EXCEPTION 'Graduation retail mixed-use batch 002 seed count mismatch';
  END IF;

  SELECT count(*) INTO reused_building_matches
  FROM reused_building_seed seed JOIN public.buildings target USING (id, slug);
  IF reused_building_matches <> 0 THEN
    RAISE EXCEPTION 'Reused building UUID/slug pairs drifted: matched %', reused_building_matches;
  END IF;

  SELECT count(*) INTO invalid_profile_buildings
  FROM profile_seed profile
  LEFT JOIN building_seed created ON created.id = profile.building_id AND created.slug = profile.building_slug
  LEFT JOIN reused_building_seed reused ON reused.id = profile.building_id AND reused.slug = profile.building_slug
  WHERE created.id IS NULL AND reused.id IS NULL;
  IF invalid_profile_buildings <> 0 THEN
    RAISE EXCEPTION 'Profile seed references % unreviewed canonical buildings', invalid_profile_buildings;
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 1 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['retail', 'mixed-use', 'public-space']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['mixed-use']::text[]);
  IF required_function_matches <> 3
    OR required_type_matches <> 1 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation retail mixed-use batch 002 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 1
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 2
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 2
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 2
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 5
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 2
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 2 THEN
    RAISE EXCEPTION 'Graduation retail mixed-use batch 002 post-write verification failed';
  END IF;
END $$;

COMMIT;
