-- Graduation Fast batch 012: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=fast-batch-012).
-- Scope: 3 new architects, 3 buildings, 3 images,
-- 3 profiles, 4 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation Fast batch 012 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('b684977c-b4f7-5770-9793-205fd676e725'::uuid, 'atelier-bow-wow-tsukamoto-lab', 'Atelier Bow-Wow＋东京工业大学塚本研究室', 'Atelier Bow-Wow + Tokyo Institute of Technology Tsukamoto Lab', 'アトリエ・ワン＋東京工業大学塚本研究室', 'https://www.bow-wow.jp/profile/2011/MiyashitaPark/index.html', true),
  ('764ac6cc-04c1-5249-be15-dbecb2a2c03f'::uuid, 'kono-designs', 'Kono Designs', 'Kono Designs', 'Kono Designs', 'https://konodesigns.com/', true),
  ('8c177e90-4b08-53cb-90d1-24866e9a5aa9'::uuid, 'hof-van-cartesius-cooperative', 'Hof van Cartesius 合作社', 'Hof van Cartesius Cooperative', 'Hof van Cartesius 協同組合', 'https://www.hofvancartesius.nl/', true);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('fe73d607-773c-56b2-a2df-e10df13183a9'::uuid, 'CASE-068', 'miyashita-park-2011', '宫下公园（2011）', 'Miyashita Park (2011)', 'みやしたこうえん（2011）', 'b684977c-b4f7-5770-9793-205fd676e725'::uuid, 'atelier-bow-wow-tsukamoto-lab', 2011, 'published', '东京', '日本', 'JP', 'public-space', 'https://www.bow-wow.jp/profile/2011/MiyashitaPark/index.html'),
  ('9f56bc37-7db9-5942-97df-db5e540e8f6c'::uuid, 'CASE-077', 'pasona-urban-farm', 'Pasona 都市农场', 'Pasona Urban Farm', 'パソナ・アーバンファーム', '764ac6cc-04c1-5249-be15-dbecb2a2c03f'::uuid, 'kono-designs', 2010, 'published', '东京', '日本', 'JP', 'office', 'https://konodesigns.com/urban-farm/'),
  ('b99e82b8-dfbe-5ada-8778-aa368b227f62'::uuid, 'CASE-089', 'het-hof-van-cartesius', 'Het Hof van Cartesius', 'Het Hof van Cartesius', 'Het Hof van Cartesius', '8c177e90-4b08-53cb-90d1-24866e9a5aa9'::uuid, 'hof-van-cartesius-cooperative', 2017, 'published', '乌得勒支', '荷兰', 'NL', 'office', 'https://www.hofvancartesius.nl/blog/hof-van-cartesius-a-place-where-people-thrive');

CREATE TEMP TABLE reused_building_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE) ON COMMIT DROP;


CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('63c546bd-e863-5d63-9315-f97cbb5be93c'::uuid, 'fe73d607-773c-56b2-a2df-e10df13183a9'::uuid, 'miyashita-park-2011', 'CASE-068', '/images/graduation/cases/case-068-miyashita-park-atelier-bow-wow.jpg', 'Douglas P. Perkins', 'Wikimedia Commons', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Miyashita_Park.jpg', 'exterior', true),
  ('4050256b-e24a-50c2-82f2-5a8bf850f201'::uuid, '9f56bc37-7db9-5942-97df-db5e540e8f6c'::uuid, 'pasona-urban-farm', 'CASE-077', '/images/graduation/cases/case-077-pasona-urban-farm.jpg', '螺钉', 'Wikimedia Commons', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Pasona_building.JPG', 'exterior', true),
  ('52122937-b27f-55ba-a05d-5bc430ff6153'::uuid, 'b99e82b8-dfbe-5ada-8778-aa368b227f62'::uuid, 'het-hof-van-cartesius', 'CASE-089', '/images/graduation/cases/case-089-het-hof-van-cartesius.jpg', 'nandasluijsmans', 'Flickr', 'CC BY-SA 2.0', 'https://www.flickr.com/photos/141420435@N08/52620631677', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL, building_slug text NOT NULL, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-068', 'fe73d607-773c-56b2-a2df-e10df13183a9'::uuid, 'miyashita-park-2011', '线状公园更新把运动设施和城市缝隙连接起来，讨论青年活动与公共管理关系。', NULL, 'Miyashita Park Atelier Bow-Wow is a reference case for reading Design topic: 高架下, park, Design topic: youth运动, Design topic: urban缝隙. It can inform thesis thinking about mixed programs, operation, and place-making.', '高架下の公園空間を若者の運動や都市の余白として扱う事例。インフラ下の公共性、管理、活動の関係を比較できる。', ARRAY['高架下', '公园', '青年运动', '城市缝隙', '公共管理']::text[], '{}'::text[], ARRAY['Design topic: 高架下', 'park', 'Design topic: youth运动', 'Design topic: urban缝隙', 'Design topic: public管理']::text[], ARRAY['高架下', '公園', '若者運動', '都市の余白', '公共性']::text[], NULL, NULL, 'https://www.bow-wow.jp/profile/2011/MiyashitaPark/index.html', 'published'),
  ('CASE-077', '9f56bc37-7db9-5942-97df-db5e540e8f6c'::uuid, 'pasona-urban-farm', '办公楼改造中嵌入都市农场、屋顶花园和食物教育，把工作场所与城市农业连接起来。', NULL, 'Pasona Urban Farm is a reference case for reading Design topic: 都市农业, Design topic: 办公, food education, Design topic: roof花园. It can inform thesis thinking about mixed programs, operation, and place-making.', '都市農業をオフィス空間に埋め込んだ事例。食の生産を見える日常に変え、働く場所と食育を結びつけている。', ARRAY['都市农业', '办公', '食育', '屋顶花园', '环境教育']::text[], '{}'::text[], ARRAY['Design topic: 都市农业', 'Design topic: 办公', 'food education', 'Design topic: roof花园', 'environmental education']::text[], ARRAY['都市農業', 'オフィス', '食育', '屋上庭園', '環境教育']::text[], NULL, NULL, 'https://konodesigns.com/urban-farm/', 'published'),
  ('CASE-089', 'b99e82b8-dfbe-5ada-8778-aa368b227f62'::uuid, 'het-hof-van-cartesius', '循环经济合作社用二手和生物基材料建造创意工坊群，展示修理、再利用和小企业共生模式。', NULL, 'Het Hof van Cartesius is a reference case for reading circular economy, repairworkshop, reuse, Design topic: 创意industry. It can inform thesis thinking about mixed programs, operation, and place-making.', '再利用材を使った小規模事業者と制作コミュニティの拠点。仕事、制作、交流が段階的に増殖する運営モデルを比較できる。', ARRAY['循环经济', '修理工坊', '再利用', '创意产业', '合作社']::text[], '{}'::text[], ARRAY['circular economy', 'repairworkshop', 'reuse', 'Design topic: 创意industry', 'Design topic: 合作社']::text[], ARRAY['共創', '再利用', '小規模事業', '制作', '循環']::text[], NULL, NULL, 'https://www.hofvancartesius.nl/blog/hof-van-cartesius-a-place-where-people-thrive', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('fe73d607-773c-56b2-a2df-e10df13183a9'::uuid, 'miyashita-park-2011', 'public-space', true, 1.000, 'https://www.bow-wow.jp/profile/2011/MiyashitaPark/index.html', 'Atelier Bow-Wow identifies the 2011 Shibuya project as Miyashita Park, designed with Tokyo Institute of Technology Tsukamoto Lab, with a 14,000 square metre park area. This historical 2011 park is distinct from the 2020 MIYASHITA PARK canonical building already in production. The image accurately shows the covered sports and circulation space of the 2011 park; Commons identifies Douglas P. Perkins as the own-work creator and licenses it CC BY 3.0.', '2026-07-12T00:00:00Z'::timestamptz),
  ('9f56bc37-7db9-5942-97df-db5e540e8f6c'::uuid, 'pasona-urban-farm', 'mixed-use', true, 1.000, 'https://konodesigns.com/urban-farm/', 'Kono Designs identifies Pasona HQ as a nine-storey corporate office renovation integrating offices, auditorium, cafeterias, rooftop garden and urban farming facilities. Mixed-use is approved as the available function that accurately expresses the deliberate office, food, education and farming combination; the broad building type remains office. The local image clearly shows the exact Pasona building and planted facade; Commons identifies 螺钉 own work, 3648 by 2736, CC BY-SA 3.0.', '2026-07-12T00:00:00Z'::timestamptz),
  ('b99e82b8-dfbe-5ada-8778-aa368b227f62'::uuid, 'het-hof-van-cartesius', 'mixed-use', true, 1.000, 'https://www.hofvancartesius.nl/blog/hof-van-cartesius-a-place-where-people-thrive', 'The cooperative describes an affordable modular working environment for creative entrepreneurs, self-built from waste and second-hand materials around a regenerative garden. The official case study explicitly describes a publicly accessible courtyard and social-cultural events, supporting mixed-use primary and public-space secondary while the broad type remains office. The local image accurately shows the circular material facade and courtyard; the Flickr page identifies nandasluijsmans and CC BY-SA 2.0, with an original 3180 by 2580 image.', '2026-07-12T00:00:00Z'::timestamptz),
  ('b99e82b8-dfbe-5ada-8778-aa368b227f62'::uuid, 'het-hof-van-cartesius', 'public-space', false, 1.000, 'https://www.hofvancartesius.nl/blog/hof-van-cartesius-a-place-where-people-thrive', 'The cooperative describes an affordable modular working environment for creative entrepreneurs, self-built from waste and second-hand materials around a regenerative garden. The official case study explicitly describes a publicly accessible courtyard and social-cultural events, supporting mixed-use primary and public-space secondary while the broad type remains office. The local image accurately shows the circular material facade and courtyard; the Flickr page identifies nandasluijsmans and CC BY-SA 2.0, with an original 3180 by 2580 image.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  reused_building_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  invalid_profile_buildings integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 3
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 3
    OR (SELECT count(*) FROM building_seed) <> 3
    OR (SELECT count(*) FROM reused_building_seed) <> 0
    OR (SELECT count(*) FROM image_seed) <> 3
    OR (SELECT count(*) FROM profile_seed) <> 3
    OR (SELECT count(*) FROM assignment_seed) <> 4 THEN
    RAISE EXCEPTION 'Graduation Fast batch 012 seed count mismatch';
  END IF;

  SELECT count(*) INTO reused_building_matches
  FROM reused_building_seed seed JOIN public.buildings target USING (id, slug);
  IF reused_building_matches <> 0 THEN
    RAISE EXCEPTION 'Reused building UUID/slug pairs drifted: matched %', reused_building_matches;
  END IF;

  SELECT count(*) INTO invalid_profile_buildings
  FROM profile_seed profile
  LEFT JOIN building_seed created ON created.id = profile.building_id AND created.slug = profile.building_slug
  LEFT JOIN reused_building_seed reused ON reused.id = profile.building_id AND reused.slug = profile.building_slug
  WHERE created.id IS NULL AND reused.id IS NULL;
  IF invalid_profile_buildings <> 0 THEN
    RAISE EXCEPTION 'Profile seed references % unreviewed canonical buildings', invalid_profile_buildings;
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 0 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['public-space', 'mixed-use']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['public-space', 'office']::text[]);
  IF required_function_matches <> 2
    OR required_type_matches <> 2 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation Fast batch 012 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 3
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 3
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 3
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 3
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 4
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 3
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 3 THEN
    RAISE EXCEPTION 'Graduation Fast batch 012 post-write verification failed';
  END IF;
END $$;

COMMIT;
