-- Graduation Final review batch 014: reviewed canonical entities and relations.
-- Generated by scripts/prepare-graduation-library-batch-002.mjs (GRADUATION_REVIEW_BATCH=final-review-batch-014).
-- Scope: 2 new architects, 3 buildings, 3 images,
-- 3 profiles, 7 approved function assignments.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.graduation_case_profiles') IS NULL
    OR to_regclass('public.building_functions') IS NULL
    OR to_regclass('public.building_function_assignments') IS NULL
    OR to_regclass('public.architects') IS NULL
    OR to_regclass('public.buildings') IS NULL
    OR to_regclass('public.images') IS NULL THEN
    RAISE EXCEPTION 'Graduation Final review batch 014 prerequisites are missing';
  END IF;
END $$;

CREATE TEMP TABLE architect_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, official_url text, is_new boolean NOT NULL) ON COMMIT DROP;
INSERT INTO architect_seed VALUES
  ('51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', '隈研吾', 'Kengo Kuma', '隈研吾', NULL, false),
  ('47b27161-6976-5ecb-b05e-3f74538c44db'::uuid, 'j-mayer-h-architects', 'J. MAYER H. 建筑事务所', 'J. MAYER H. Architects', 'J. MAYER H. アーキテクツ', 'https://jmayerh.de/', true),
  ('cb364427-cc97-5696-88a1-22aaf2b07352'::uuid, 'lab-architecture-studio-bates-smart', 'Lab Architecture Studio＋Bates Smart', 'Lab Architecture Studio + Bates Smart', 'Lab Architecture Studio＋Bates Smart', 'https://fedsquare.com/history-design', true);

CREATE TEMP TABLE building_seed (id uuid PRIMARY KEY, case_id text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, name_zh text, name_en text NOT NULL, name_ja text, architect_id uuid NOT NULL, architect_slug text NOT NULL, year_start integer NOT NULL, status text NOT NULL, city text NOT NULL, country text NOT NULL, country_code text NOT NULL, type_slug text NOT NULL, official_url text NOT NULL) ON COMMIT DROP;
INSERT INTO building_seed VALUES
  ('be6b9af1-a699-5e5e-978a-eb1f17b2fbc4'::uuid, 'CASE-100', 'portland-japanese-garden-cultural-village', '波特兰日本庭园文化村', 'Portland Japanese Garden Cultural Village', 'ポートランド日本庭園カルチュラル・ビレッジ', '51797239-be38-4dbd-9d7e-e413ddf3c78a'::uuid, 'kengo-kuma', 2017, 'published', '波特兰', '美国', 'US', 'cultural', 'https://kkaa.co.jp/en/project/portland-japanese-garden-cultural-village/'),
  ('87d4871f-1307-5d8a-b948-56f69a404e0f'::uuid, 'CASE-126', 'metropol-parasol', '都市阳伞', 'Metropol Parasol', 'メトロポール・パラソル', '47b27161-6976-5ecb-b05e-3f74538c44db'::uuid, 'j-mayer-h-architects', 2011, 'published', '塞维利亚', '西班牙', 'ES', 'mixed-use', 'https://jmayerh.de/metropol-parasol/?n=0'),
  ('a5d4f96c-ca21-57d9-9b38-b818a23540dd'::uuid, 'CASE-136', 'federation-square', '联邦广场', 'Federation Square', 'フェデレーション・スクエア', 'cb364427-cc97-5696-88a1-22aaf2b07352'::uuid, 'lab-architecture-studio-bates-smart', 2002, 'published', '墨尔本', '澳大利亚', 'AU', 'civic-public', 'https://fedsquare.com/history-design');

CREATE TEMP TABLE reused_building_seed (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE) ON COMMIT DROP;


CREATE TEMP TABLE image_seed (id uuid PRIMARY KEY, building_id uuid NOT NULL UNIQUE, building_slug text NOT NULL UNIQUE, case_id text NOT NULL UNIQUE, url_original text NOT NULL, photographer text NOT NULL, source text NOT NULL, license text NOT NULL, source_url text NOT NULL UNIQUE, img_type text NOT NULL, is_primary boolean NOT NULL) ON COMMIT DROP;
INSERT INTO image_seed VALUES
  ('708879a7-7e39-5952-88ee-70bd181cbdc3'::uuid, 'be6b9af1-a699-5e5e-978a-eb1f17b2fbc4'::uuid, 'portland-japanese-garden-cultural-village', 'CASE-100', '/images/graduation/cases/case-100-portland-japanese-garden-cultural-village.jpg', 'WLernerPJG', 'Wikimedia Commons', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Tsubo-Niwa_at_Portland_Japanese_Garden.jpg', 'exterior', true),
  ('0e3f712d-732a-5bd3-a0a0-8d3f8ea2818f'::uuid, '87d4871f-1307-5d8a-b948-56f69a404e0f'::uuid, 'metropol-parasol', 'CASE-126', '/images/graduation/cases/case-126-metropol-parasol.jpg', 'Arup', 'Wikimedia Commons', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Metropol_Parasol.JPG', 'exterior', true),
  ('1cd70029-d1a2-56ad-8458-6869b205369c'::uuid, 'a5d4f96c-ca21-57d9-9b38-b818a23540dd'::uuid, 'federation-square', 'CASE-136', '/images/graduation/cases/case-136-federation-square.jpg', 'Alpha / Wikimedia Commons (Flickr)', 'Wikimedia Commons', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Federation_Square_Melbourne.jpg', 'exterior', true);

CREATE TEMP TABLE profile_seed (case_id text PRIMARY KEY, building_id uuid NOT NULL, building_slug text NOT NULL, concept_zh text NOT NULL, concept_zh_hant text, concept_en text, concept_ja text, keywords_zh text[] NOT NULL, keywords_zh_hant text[] NOT NULL, keywords_en text[] NOT NULL, keywords_ja text[] NOT NULL, plan_url text, section_url text, source_url text NOT NULL, publication_status text NOT NULL) ON COMMIT DROP;
INSERT INTO profile_seed VALUES
  ('CASE-100', 'be6b9af1-a699-5e5e-978a-eb1f17b2fbc4'::uuid, 'portland-japanese-garden-cultural-village', '文化村以庭院和小尺度建筑组织学习、接待和自然体验，连接跨文化教育与景观公共性。', NULL, 'Portland Japanese Garden Cultural Village is a reference case for reading Design topic: 跨culture, courtyard, natureeducation, Design topic: culture村. It can inform thesis thinking about mixed programs, operation, and place-making.', '庭園、学習、接待を小さな建築群で組み立てる文化村。自然体験と文化理解を、説明よりも滞在の流れで伝えている。', ARRAY['跨文化', '庭院', '自然教育', '文化村', '接待']::text[], '{}'::text[], ARRAY['Design topic: 跨culture', 'courtyard', 'natureeducation', 'Design topic: culture村', 'Design topic: 接待']::text[], ARRAY['多文化', '庭園', '自然教育', '文化村', '接待']::text[], NULL, NULL, 'https://kkaa.co.jp/en/project/portland-japanese-garden-cultural-village/', 'published'),
  ('CASE-126', '87d4871f-1307-5d8a-b948-56f69a404e0f'::uuid, 'metropol-parasol', '大きな木質構造で市場、広場、展望、日陰をつくる事例。暑熱環境と公共活動を同時に扱える。', NULL, 'Reference case for Metropol Parasol: useful for comparing public program, urban interface, operation, and spatial experience.', '大きな木質構造で市場、広場、展望、日陰をつくる事例。暑熱環境と公共活動を同時に扱える。', ARRAY['大屋根', '市場', '日陰', '市民広場', '木構造']::text[], '{}'::text[], ARRAY['大屋根', '市場', '日陰', '市民広場', '木構造']::text[], ARRAY['大屋根', '市場', '日陰', '市民広場', '木構造']::text[], NULL, NULL, 'https://www.jmayerh.de/projects/metropol-parasol', 'published'),
  ('CASE-136', 'a5d4f96c-ca21-57d9-9b38-b818a23540dd'::uuid, 'federation-square', '広場、文化施設、交通結節点をまとめた都市の公共室。中心市街地の滞在とイベントを考える参考になる。', NULL, 'Reference case for Federation Square: useful for comparing public program, urban interface, operation, and spatial experience.', '広場、文化施設、交通結節点をまとめた都市の公共室。中心市街地の滞在とイベントを考える参考になる。', ARRAY['市民広場', '文化施設', '交通結節点', 'イベント', '都市リビング']::text[], '{}'::text[], ARRAY['市民広場', '文化施設', '交通結節点', 'イベント', '都市リビング']::text[], ARRAY['市民広場', '文化施設', '交通結節点', 'イベント', '都市リビング']::text[], NULL, NULL, 'https://fedsquare.com/', 'published');

CREATE TEMP TABLE assignment_seed (building_id uuid NOT NULL, building_slug text NOT NULL, function_slug text NOT NULL, is_primary boolean NOT NULL, confidence numeric(4,3) NOT NULL, evidence_url text NOT NULL, evidence_note text NOT NULL, reviewed_at timestamptz NOT NULL, PRIMARY KEY (building_id, function_slug)) ON COMMIT DROP;
INSERT INTO assignment_seed VALUES
  ('be6b9af1-a699-5e5e-978a-eb1f17b2fbc4'::uuid, 'portland-japanese-garden-cultural-village', 'public-space', true, 1.000, 'https://kkaa.co.jp/en/project/portland-japanese-garden-cultural-village/', 'KKAA identifies the completed 2017 Oregon civic project as four buildings arranged around a courtyard plaza and credits Kengo Kuma and Associates with named collaborators. Commons keywords identify the photographed Tsubo-Niwa as the Cultural Village Tateuchi courtyard; visual review confirms the courtyard building context.', '2026-07-12T00:00:00Z'::timestamptz),
  ('87d4871f-1307-5d8a-b948-56f69a404e0f'::uuid, 'metropol-parasol', 'mixed-use', true, 1.000, 'https://jmayerh.de/metropol-parasol/?n=0', 'J.MAYER.H identifies its 2004-2011 Seville project and documents the archaeological museum, farmers market, elevated plaza, food venues and panorama terrace. The Commons own-work photograph by Arup clearly shows the exact timber parasol structure.', '2026-07-12T00:00:00Z'::timestamptz),
  ('87d4871f-1307-5d8a-b948-56f69a404e0f'::uuid, 'metropol-parasol', 'public-space', false, 1.000, 'https://jmayerh.de/metropol-parasol/?n=0', 'J.MAYER.H identifies its 2004-2011 Seville project and documents the archaeological museum, farmers market, elevated plaza, food venues and panorama terrace. The Commons own-work photograph by Arup clearly shows the exact timber parasol structure.', '2026-07-12T00:00:00Z'::timestamptz),
  ('87d4871f-1307-5d8a-b948-56f69a404e0f'::uuid, 'metropol-parasol', 'museum', false, 1.000, 'https://jmayerh.de/metropol-parasol/?n=0', 'J.MAYER.H identifies its 2004-2011 Seville project and documents the archaeological museum, farmers market, elevated plaza, food venues and panorama terrace. The Commons own-work photograph by Arup clearly shows the exact timber parasol structure.', '2026-07-12T00:00:00Z'::timestamptz),
  ('87d4871f-1307-5d8a-b948-56f69a404e0f'::uuid, 'metropol-parasol', 'retail', false, 1.000, 'https://jmayerh.de/metropol-parasol/?n=0', 'J.MAYER.H identifies its 2004-2011 Seville project and documents the archaeological museum, farmers market, elevated plaza, food venues and panorama terrace. The Commons own-work photograph by Arup clearly shows the exact timber parasol structure.', '2026-07-12T00:00:00Z'::timestamptz),
  ('a5d4f96c-ca21-57d9-9b38-b818a23540dd'::uuid, 'federation-square', 'public-space', true, 1.000, 'https://fedsquare.com/history-design', 'Fed Square documents the civic-space competition, cultural and commercial program, Lab architecture studio partnership with Bates Smart, and opening on 26 October 2002. The Flickr-origin Commons image by Alpha clearly shows the main square and complex facades.', '2026-07-12T00:00:00Z'::timestamptz),
  ('a5d4f96c-ca21-57d9-9b38-b818a23540dd'::uuid, 'federation-square', 'mixed-use', false, 1.000, 'https://fedsquare.com/history-design', 'Fed Square documents the civic-space competition, cultural and commercial program, Lab architecture studio partnership with Bates Smart, and opening on 26 October 2002. The Flickr-origin Commons image by Alpha clearly shows the main square and complex facades.', '2026-07-12T00:00:00Z'::timestamptz);

DO $$
DECLARE
  existing_architect_matches integer;
  reused_building_matches integer;
  required_function_matches integer;
  required_type_matches integer;
  invalid_profile_buildings integer;
  conflicts integer;
BEGIN
  IF (SELECT count(*) FROM architect_seed) <> 3
    OR (SELECT count(*) FROM architect_seed WHERE is_new) <> 2
    OR (SELECT count(*) FROM building_seed) <> 3
    OR (SELECT count(*) FROM reused_building_seed) <> 0
    OR (SELECT count(*) FROM image_seed) <> 3
    OR (SELECT count(*) FROM profile_seed) <> 3
    OR (SELECT count(*) FROM assignment_seed) <> 7 THEN
    RAISE EXCEPTION 'Graduation Final review batch 014 seed count mismatch';
  END IF;

  SELECT count(*) INTO reused_building_matches
  FROM reused_building_seed seed JOIN public.buildings target USING (id, slug);
  IF reused_building_matches <> 0 THEN
    RAISE EXCEPTION 'Reused building UUID/slug pairs drifted: matched %', reused_building_matches;
  END IF;

  SELECT count(*) INTO invalid_profile_buildings
  FROM profile_seed profile
  LEFT JOIN building_seed created ON created.id = profile.building_id AND created.slug = profile.building_slug
  LEFT JOIN reused_building_seed reused ON reused.id = profile.building_id AND reused.slug = profile.building_slug
  WHERE created.id IS NULL AND reused.id IS NULL;
  IF invalid_profile_buildings <> 0 THEN
    RAISE EXCEPTION 'Profile seed references % unreviewed canonical buildings', invalid_profile_buildings;
  END IF;

  SELECT count(*) INTO existing_architect_matches
  FROM architect_seed seed JOIN public.architects target USING (id, slug)
  WHERE seed.is_new = false;
  IF existing_architect_matches <> 1 THEN
    RAISE EXCEPTION 'Existing architect UUID/slug pairs drifted: matched %', existing_architect_matches;
  END IF;

  SELECT count(*) INTO required_function_matches
  FROM public.building_functions
  WHERE slug = ANY (ARRAY['public-space', 'mixed-use', 'museum', 'retail']::text[]) AND is_active = true;
  SELECT count(*) INTO required_type_matches
  FROM public.building_types
  WHERE slug = ANY (ARRAY['cultural', 'mixed-use', 'civic-public']::text[]);
  IF required_function_matches <> 4
    OR required_type_matches <> 3 THEN
    RAISE EXCEPTION 'Required building type or functions are missing';
  END IF;

  SELECT
    (SELECT count(*) FROM public.architects target JOIN architect_seed seed ON seed.is_new AND (target.id = seed.id OR target.slug = seed.slug))
    + (SELECT count(*) FROM public.buildings target JOIN building_seed seed ON target.id = seed.id OR target.slug = seed.slug)
    + (SELECT count(*) FROM public.images target JOIN image_seed seed ON target.id = seed.id OR target.source_url = seed.source_url)
    + (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed ON target.case_id = seed.case_id)
    + (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug))
  INTO conflicts;
  IF conflicts <> 0 THEN
    RAISE EXCEPTION 'Graduation Final review batch 014 requires empty target keys; found % conflicts', conflicts;
  END IF;
END $$;

INSERT INTO public.architects (id, slug, name_zh, name_en, name_ja, official_url)
SELECT id, slug, name_zh, name_en, name_ja, official_url FROM architect_seed WHERE is_new;

INSERT INTO public.buildings (id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url)
SELECT id, slug, name_zh, name_en, name_ja, architect_id, architect_slug, year_start, status, city, country, country_code, type_slug, official_url FROM building_seed;

INSERT INTO public.images (id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary)
SELECT id, building_id, url_original, photographer, source, license, source_url, img_type, is_primary FROM image_seed;

INSERT INTO public.graduation_case_profiles (case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status)
SELECT case_id, building_id, concept_zh, concept_zh_hant, concept_en, concept_ja, keywords_zh, keywords_zh_hant, keywords_en, keywords_ja, plan_url, section_url, source_url, publication_status FROM profile_seed;

INSERT INTO public.building_function_assignments (building_id, function_slug, is_primary, confidence, review_status, assignment_method, evidence_url, evidence_note, reviewed_at)
SELECT building_id, function_slug, is_primary, confidence, 'approved', 'source-derived', evidence_url, evidence_note, reviewed_at FROM assignment_seed;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.architects target JOIN architect_seed seed USING (id, slug) WHERE seed.is_new) <> 2
    OR (SELECT count(*) FROM public.buildings target JOIN building_seed seed USING (id, slug)) <> 3
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (id, building_id, source_url)) <> 3
    OR (SELECT count(*) FROM public.graduation_case_profiles target JOIN profile_seed seed USING (case_id, building_id)) <> 3
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.review_status = 'approved') <> 7
    OR (SELECT count(*) FROM public.images target JOIN image_seed seed USING (building_id) WHERE target.is_primary) <> 3
    OR (SELECT count(*) FROM public.building_function_assignments target JOIN assignment_seed seed USING (building_id, function_slug) WHERE target.is_primary) <> 3 THEN
    RAISE EXCEPTION 'Graduation Final review batch 014 post-write verification failed';
  END IF;
END $$;

COMMIT;
